///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BuyerProductModelData {
  /*
{
  "ID": "1185",
  "nama": "Skincare Pria",
  "harga": "467000",
  "kode_produk": "002",
  "size": "",
  "qty": "19",
  "deskripsi": "Membuat kulit cerah",
  "SellerID": "196",
  "SellerNama": "Atria Seller",
  "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
  "IDKategori": "1",
  "NamaKategori": "Consumable"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? SellerNama;
  String? foto;
  String? IDKategori;
  String? NamaKategori;
  String? terjual;

  BuyerProductModelData({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.SellerNama,
    this.foto,
    this.IDKategori,
    this.NamaKategori,
    this.terjual,
  });
  BuyerProductModelData.fromJson(Map<String, dynamic> json) {
    ID = json['id']?.toString() ?? json['ID']?.toString();
    nama = json['name']?.toString() ?? json['nama']?.toString();
    harga = json['price']?.toString() ?? json['harga']?.toString();
    kodeProduk =
        json['product_code']?.toString() ?? json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi =
        json['description']?.toString() ?? json['deskripsi']?.toString();

    // Seller nested atau flat
    if (json['seller'] != null) {
      SellerID = json['seller']['id']?.toString();
      SellerNama = json['seller']['name']?.toString();
    } else {
      SellerID = json['SellerID']?.toString();
      SellerNama = json['SellerNama']?.toString();
    }

    foto = json['photo']?.toString() ?? json['foto']?.toString();

    // Category nested atau flat
    if (json['category'] != null) {
      IDKategori = json['category']['id']?.toString();
      NamaKategori = json['category']['name']?.toString();
    } else {
      IDKategori = json['IDKategori']?.toString();
      NamaKategori = json['NamaKategori']?.toString();
    }

    terjual = json['terjual']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['SellerNama'] = SellerNama;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['NamaKategori'] = NamaKategori;
    data['terjual'] = terjual;
    return data;
  }
}

class BuyerProductModel {
  /*
{
  "result": "success",
  "data": [
    {
      "ID": "1185",
      "nama": "Skincare Pria",
      "harga": "467000",
      "kode_produk": "002",
      "size": "",
      "qty": "19",
      "deskripsi": "Membuat kulit cerah",
      "SellerID": "196",
      "SellerNama": "Atria Seller",
      "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
      "IDKategori": "1",
      "NamaKategori": "Consumable"
    }
  ]
}
*/

  String? result;
  List<BuyerProductModelData?>? data;

  BuyerProductModel({this.result, this.data});
  BuyerProductModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BuyerProductModelData>[];
      v.forEach((v) {
        arr0.add(BuyerProductModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
