///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeAdminModelDataTseller {
/*
{
  "email": "singoyudhonusantara@gmail.com",
  "qty": "46",
  "harga": "26039500"
} 
*/

  String? email;
  String? qty;
  String? harga;

  HomeAdminModelDataTseller({
    this.email,
    this.qty,
    this.harga,
  });
  HomeAdminModelDataTseller.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    qty = json['qty']?.toString();
    harga = json['harga']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['qty'] = qty;
    data['harga'] = harga;
    return data;
  }
}

class HomeAdminModelDataTbuyer {
/*
{
  "email": "jaenalpanji.r@gmail.com",
  "qty": "46",
  "harga": "26039500"
} 
*/

  String? email;
  String? qty;
  String? harga;

  HomeAdminModelDataTbuyer({
    this.email,
    this.qty,
    this.harga,
  });
  HomeAdminModelDataTbuyer.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    qty = json['qty']?.toString();
    harga = json['harga']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['qty'] = qty;
    data['harga'] = harga;
    return data;
  }
}

class HomeAdminModelDataTproduk {
/*
{
  "nama": "PLAT BESI 20MM x 4INCH x 8INCH",
  "qty": "1",
  "harga": "8360000"
} 
*/

  String? nama;
  String? qty;
  String? harga;

  HomeAdminModelDataTproduk({
    this.nama,
    this.qty,
    this.harga,
  });
  HomeAdminModelDataTproduk.fromJson(Map<String, dynamic> json) {
    nama = json['nama']?.toString();
    qty = json['qty']?.toString();
    harga = json['harga']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nama'] = nama;
    data['qty'] = qty;
    data['harga'] = harga;
    return data;
  }
}

class HomeAdminModelData {
/*
{
  "total_user": "52",
  "total_seller": "38",
  "total_buyer": "10",
  "pembelian": [
    0
  ],
  "transaksi": [
    104
  ],
  "transaksi_nominal": [
    2750069562
  ],
  "transaksi_label": [
    "Total"
  ],
  "tproduk": [
    {
      "nama": "PLAT BESI 20MM x 4INCH x 8INCH",
      "qty": "1",
      "harga": "8360000"
    }
  ],
  "tbuyer": [
    {
      "email": "jaenalpanji.r@gmail.com",
      "qty": "46",
      "harga": "26039500"
    }
  ],
  "tseller": [
    {
      "email": "singoyudhonusantara@gmail.com",
      "qty": "46",
      "harga": "26039500"
    }
  ]
} 
*/

  String? totalUser;
  String? totalSeller;
  String? totalBuyer;
  List<int?>? pembelian;
  List<int?>? transaksi;
  List<int?>? transaksiNominal;
  List<String?>? transaksiLabel;
  List<HomeAdminModelDataTproduk?>? tproduk;
  List<HomeAdminModelDataTbuyer?>? tbuyer;
  List<HomeAdminModelDataTseller?>? tseller;

  HomeAdminModelData({
    this.totalUser,
    this.totalSeller,
    this.totalBuyer,
    this.pembelian,
    this.transaksi,
    this.transaksiNominal,
    this.transaksiLabel,
    this.tproduk,
    this.tbuyer,
    this.tseller,
  });
  HomeAdminModelData.fromJson(Map<String, dynamic> json) {
    totalUser = json['total_user']?.toString();
    totalSeller = json['total_seller']?.toString();
    totalBuyer = json['total_buyer']?.toString();
    if (json['pembelian'] != null) {
      final v = json['pembelian'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      pembelian = arr0;
    }
    if (json['transaksi'] != null) {
      final v = json['transaksi'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      transaksi = arr0;
    }
    if (json['transaksi_nominal'] != null) {
      final v = json['transaksi_nominal'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      transaksiNominal = arr0;
    }
    if (json['transaksi_label'] != null) {
      final v = json['transaksi_label'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      transaksiLabel = arr0;
    }
    if (json['tproduk'] != null) {
      final v = json['tproduk'];
      final arr0 = <HomeAdminModelDataTproduk>[];
      v.forEach((v) {
        arr0.add(HomeAdminModelDataTproduk.fromJson(v));
      });
      tproduk = arr0;
    }
    if (json['tbuyer'] != null) {
      final v = json['tbuyer'];
      final arr0 = <HomeAdminModelDataTbuyer>[];
      v.forEach((v) {
        arr0.add(HomeAdminModelDataTbuyer.fromJson(v));
      });
      tbuyer = arr0;
    }
    if (json['tseller'] != null) {
      final v = json['tseller'];
      final arr0 = <HomeAdminModelDataTseller>[];
      v.forEach((v) {
        arr0.add(HomeAdminModelDataTseller.fromJson(v));
      });
      tseller = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_user'] = totalUser;
    data['total_seller'] = totalSeller;
    data['total_buyer'] = totalBuyer;
    if (pembelian != null) {
      final v = pembelian;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['pembelian'] = arr0;
    }
    if (transaksi != null) {
      final v = transaksi;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['transaksi'] = arr0;
    }
    if (transaksiNominal != null) {
      final v = transaksiNominal;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['transaksi_nominal'] = arr0;
    }
    if (transaksiLabel != null) {
      final v = transaksiLabel;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['transaksi_label'] = arr0;
    }
    if (tproduk != null) {
      final v = tproduk;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tproduk'] = arr0;
    }
    if (tbuyer != null) {
      final v = tbuyer;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tbuyer'] = arr0;
    }
    if (tseller != null) {
      final v = tseller;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tseller'] = arr0;
    }
    return data;
  }
}

class HomeAdminModel {
/*
{
  "result": "success",
  "data": {
    "total_user": "52",
    "total_seller": "38",
    "total_buyer": "10",
    "pembelian": [
      0
    ],
    "transaksi": [
      104
    ],
    "transaksi_nominal": [
      2750069562
    ],
    "transaksi_label": [
      "Total"
    ],
    "tproduk": [
      {
        "nama": "PLAT BESI 20MM x 4INCH x 8INCH",
        "qty": "1",
        "harga": "8360000"
      }
    ],
    "tbuyer": [
      {
        "email": "jaenalpanji.r@gmail.com",
        "qty": "46",
        "harga": "26039500"
      }
    ],
    "tseller": [
      {
        "email": "singoyudhonusantara@gmail.com",
        "qty": "46",
        "harga": "26039500"
      }
    ]
  }
} 
*/

  String? result;
  HomeAdminModelData? data;

  HomeAdminModel({
    this.result,
    this.data,
  });
  HomeAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null)
        ? HomeAdminModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
