///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SellerAdminModelData {
/*
{
  "ID": "196",
  "nama": "Atria Seller",
  "alamat": "",
  "lokasi": "",
  "lattitude": "",
  "longitude": "",
  "email": "atriaseller@gmail.com",
  "telp": "",
  "kbli": "",
  "nama_pemilik": "Bayu Dibya",
  "nama_cp": "",
  "telp_cp": "",
  "foto": "",
  "no_npwp": "",
  "npwp": "",
  "no_ktp": "",
  "ktp": "",
  "sp_pkp": "",
  "prov": null,
  "kota": null,
  "no_rek": "",
  "an_rek": "",
  "bank": "",
  "buku_rekening": null
}
*/

  String? ID;
  String? nama;
  String? alamat;
  String? lokasi;
  String? lattitude;
  String? longitude;
  String? email;
  String? telp;
  String? kbli;
  String? namaPemilik;
  String? namaCp;
  String? telpCp;
  String? foto;
  String? noNpwp;
  String? npwp;
  String? noKtp;
  String? ktp;
  String? spPkp;
  String? prov;
  String? kota;
  String? noRek;
  String? anRek;
  String? bank;
  String? bukuRekening;
  String? status;

  SellerAdminModelData({
    this.ID,
    this.nama,
    this.alamat,
    this.lokasi,
    this.lattitude,
    this.longitude,
    this.email,
    this.telp,
    this.kbli,
    this.namaPemilik,
    this.namaCp,
    this.telpCp,
    this.foto,
    this.noNpwp,
    this.npwp,
    this.noKtp,
    this.ktp,
    this.spPkp,
    this.prov,
    this.kota,
    this.noRek,
    this.anRek,
    this.bank,
    this.bukuRekening,
    this.status,
  });
  SellerAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    lokasi = json['lokasi']?.toString();
    lattitude = json['lattitude']?.toString();
    longitude = json['longitude']?.toString();
    email = json['email']?.toString();
    telp = json['telp']?.toString();
    kbli = json['kbli']?.toString();
    namaPemilik = json['nama_pemilik']?.toString();
    namaCp = json['nama_cp']?.toString();
    telpCp = json['telp_cp']?.toString();
    foto = json['foto']?.toString();
    noNpwp = json['no_npwp']?.toString();
    npwp = json['npwp']?.toString();
    noKtp = json['no_ktp']?.toString();
    ktp = json['ktp']?.toString();
    spPkp = json['sp_pkp']?.toString();
    prov = json['prov']?.toString();
    kota = json['kota']?.toString();
    noRek = json['no_rek']?.toString();
    anRek = json['an_rek']?.toString();
    bank = json['bank']?.toString();
    bukuRekening = json['buku_rekening']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['lokasi'] = lokasi;
    data['lattitude'] = lattitude;
    data['longitude'] = longitude;
    data['email'] = email;
    data['telp'] = telp;
    data['kbli'] = kbli;
    data['nama_pemilik'] = namaPemilik;
    data['nama_cp'] = namaCp;
    data['telp_cp'] = telpCp;
    data['foto'] = foto;
    data['no_npwp'] = noNpwp;
    data['npwp'] = npwp;
    data['no_ktp'] = noKtp;
    data['ktp'] = ktp;
    data['sp_pkp'] = spPkp;
    data['prov'] = prov;
    data['kota'] = kota;
    data['no_rek'] = noRek;
    data['an_rek'] = anRek;
    data['bank'] = bank;
    data['buku_rekening'] = bukuRekening;
    data['status'] = status;
    return data;
  }
}

class SellerAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "196",
      "nama": "Atria Seller",
      "alamat": "",
      "lokasi": "",
      "lattitude": "",
      "longitude": "",
      "email": "atriaseller@gmail.com",
      "telp": "",
      "kbli": "",
      "nama_pemilik": "Bayu Dibya",
      "nama_cp": "",
      "telp_cp": "",
      "foto": "",
      "no_npwp": "",
      "npwp": "",
      "no_ktp": "",
      "ktp": "",
      "sp_pkp": "",
      "prov": null,
      "kota": null,
      "no_rek": "",
      "an_rek": "",
      "bank": "",
      "buku_rekening": null
    }
  ]
}
*/

  String? result;
  List<SellerAdminModelData?>? data;

  SellerAdminModel({
    this.result,
    this.data,
  });
  SellerAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SellerAdminModelData>[];
      v.forEach((v) {
        arr0.add(SellerAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
