///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelData {
/*
{
  "ID": "1185",
  "nama": "Skincare Pria",
  "harga": "467000",
  "kode_produk": "002",
  "size": "",
  "qty": "19",
  "deskripsi": "Membuat kulit cerah",
  "SellerID": "196",
  "SellerNama": "Atria Seller",
  "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
  "IDKategori": "1",
  "NamaKategori": "Consumable"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? SellerNama;
  String? foto;
  String? IDKategori;
  String? NamaKategori;
  String? alamat;
  String? prov;
  String? kota;
  String? terjual;

  ProductModelData({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.SellerNama,
    this.foto,
    this.IDKategori,
    this.NamaKategori,
    this.alamat,
    this.prov,
    this.kota,
    this.terjual,
  });
  ProductModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    SellerNama = json['SellerNama']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    NamaKategori = json['NamaKategori']?.toString();
    alamat = json['alamat'];
    prov = json['prov'];
    kota = json['kota'];
    terjual = json['terjual']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['SellerNama'] = SellerNama;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['NamaKategori'] = NamaKategori;
    data['alamat'] = alamat;
    data['prov'] = prov;
    data['kota'] = kota;
    data['terjual'] = terjual;
    return data;
  }
}

class ProductModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1185",
      "nama": "Skincare Pria",
      "harga": "467000",
      "kode_produk": "002",
      "size": "",
      "qty": "19",
      "deskripsi": "Membuat kulit cerah",
      "SellerID": "196",
      "SellerNama": "Atria Seller",
      "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
      "IDKategori": "1",
      "NamaKategori": "Consumable"
    }
  ]
}
*/

  String? result;
  List<ProductModelData?>? data;

  ProductModel({
    this.result,
    this.data,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProductModelData>[];
      v.forEach((v) {
        arr0.add(ProductModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
