///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotifikasiKeuanganModelData {
/*
{
  "id": "1051",
  "activity_at": "2024-09-03 10:26:44",
  "activity_message": "Pesanan Dikirim By Seller",
  "parent_order_id": "124",
  "activity_fk_number": "0117/SPS/M-Speed/24",
  "is_read": "Terbaca",
  "foto": "https://mspeed.erdata.id/produk/woody_toy_story_4-wallpaper-1280x1280.jpg",
  "judul": "Pesanan Dikirim",
  "pesan": "Pesanan 0117/SPS/M-Speed/24 berhasil dikirim"
} 
*/

  String? id;
  String? activityAt;
  String? activityMessage;
  String? parentOrderId;
  String? activityFkNumber;
  String? isRead;
  String? foto;
  String? judul;
  String? pesan;

  NotifikasiKeuanganModelData({
    this.id,
    this.activityAt,
    this.activityMessage,
    this.parentOrderId,
    this.activityFkNumber,
    this.isRead,
    this.foto,
    this.judul,
    this.pesan,
  });
  NotifikasiKeuanganModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    activityAt = json['activity_at']?.toString();
    activityMessage = json['activity_message']?.toString();
    parentOrderId = json['parent_order_id']?.toString();
    activityFkNumber = json['activity_fk_number']?.toString();
    isRead = json['is_read']?.toString();
    foto = json['foto']?.toString();
    judul = json['judul']?.toString();
    pesan = json['pesan']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['activity_at'] = activityAt;
    data['activity_message'] = activityMessage;
    data['parent_order_id'] = parentOrderId;
    data['activity_fk_number'] = activityFkNumber;
    data['is_read'] = isRead;
    data['foto'] = foto;
    data['judul'] = judul;
    data['pesan'] = pesan;
    return data;
  }
}

class NotifikasiKeuanganModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": "1051",
      "activity_at": "2024-09-03 10:26:44",
      "activity_message": "Pesanan Dikirim By Seller",
      "parent_order_id": "124",
      "activity_fk_number": "0117/SPS/M-Speed/24",
      "is_read": "Terbaca",
      "foto": "https://mspeed.erdata.id/produk/woody_toy_story_4-wallpaper-1280x1280.jpg",
      "judul": "Pesanan Dikirim",
      "pesan": "Pesanan 0117/SPS/M-Speed/24 berhasil dikirim"
    }
  ]
} 
*/

  String? result;
  List<NotifikasiKeuanganModelData?>? data;

  NotifikasiKeuanganModel({
    this.result,
    this.data,
  });
  NotifikasiKeuanganModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotifikasiKeuanganModelData>[];
      v.forEach((v) {
        arr0.add(NotifikasiKeuanganModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
