///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PenerimaAdminModelData {
/*
{
  "ID": "135",
  "email": "noobyta2@gmail.com",
  "password": "$2y$10$iOk2yJlDSAuPA8RiRX7EZOsdVFmK8JHZwXbuxeK8Vsr8tlJ4fIleC",
  "jenis": "SUB_BUYER",
  "aktif": "0",
  "hapus": "0",
  "kelengkapan": "0",
  "nama_perusahaan": "",
  "alamat": "Jalan Probolinggo No 12",
  "tagging": "",
  "kegiatan_usaha": "",
  "pemilik_toko": "",
  "firstname": "Penerima JP2",
  "lastname": "Urip",
  "HakAksesID": "2",
  "status_pilihalamat": "0",
  "telp": "+62 812-3749-9347",
  "kabkota": "Tuban",
  "subdit_id": ""
} 
*/

  String? ID;
  String? email;
  String? password;
  String? jenis;
  String? aktif;
  String? hapus;
  String? kelengkapan;
  String? namaPerusahaan;
  String? alamat;
  String? tagging;
  String? kegiatanUsaha;
  String? pemilikToko;
  String? firstname;
  String? lastname;
  String? HakAksesID;
  String? statusPilihalamat;
  String? telp;
  String? kabkota;
  String? subditId;

  PenerimaAdminModelData({
    this.ID,
    this.email,
    this.password,
    this.jenis,
    this.aktif,
    this.hapus,
    this.kelengkapan,
    this.namaPerusahaan,
    this.alamat,
    this.tagging,
    this.kegiatanUsaha,
    this.pemilikToko,
    this.firstname,
    this.lastname,
    this.HakAksesID,
    this.statusPilihalamat,
    this.telp,
    this.kabkota,
    this.subditId,
  });
  PenerimaAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    jenis = json['jenis']?.toString();
    aktif = json['aktif']?.toString();
    hapus = json['hapus']?.toString();
    kelengkapan = json['kelengkapan']?.toString();
    namaPerusahaan = json['nama_perusahaan']?.toString();
    alamat = json['alamat']?.toString();
    tagging = json['tagging']?.toString();
    kegiatanUsaha = json['kegiatan_usaha']?.toString();
    pemilikToko = json['pemilik_toko']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    HakAksesID = json['HakAksesID']?.toString();
    statusPilihalamat = json['status_pilihalamat']?.toString();
    telp = json['telp']?.toString();
    kabkota = json['kabkota']?.toString();
    subditId = json['subdit_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['email'] = email;
    data['password'] = password;
    data['jenis'] = jenis;
    data['aktif'] = aktif;
    data['hapus'] = hapus;
    data['kelengkapan'] = kelengkapan;
    data['nama_perusahaan'] = namaPerusahaan;
    data['alamat'] = alamat;
    data['tagging'] = tagging;
    data['kegiatan_usaha'] = kegiatanUsaha;
    data['pemilik_toko'] = pemilikToko;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['HakAksesID'] = HakAksesID;
    data['status_pilihalamat'] = statusPilihalamat;
    data['telp'] = telp;
    data['kabkota'] = kabkota;
    data['subdit_id'] = subditId;
    return data;
  }
}

class PenerimaAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "135",
      "email": "noobyta2@gmail.com",
      "password": "$2y$10$iOk2yJlDSAuPA8RiRX7EZOsdVFmK8JHZwXbuxeK8Vsr8tlJ4fIleC",
      "jenis": "SUB_BUYER",
      "aktif": "0",
      "hapus": "0",
      "kelengkapan": "0",
      "nama_perusahaan": "",
      "alamat": "Jalan Probolinggo No 12",
      "tagging": "",
      "kegiatan_usaha": "",
      "pemilik_toko": "",
      "firstname": "Penerima JP2",
      "lastname": "Urip",
      "HakAksesID": "2",
      "status_pilihalamat": "0",
      "telp": "+62 812-3749-9347",
      "kabkota": "Tuban",
      "subdit_id": ""
    }
  ]
} 
*/

  String? result;
  List<PenerimaAdminModelData?>? data;

  PenerimaAdminModel({
    this.result,
    this.data,
  });
  PenerimaAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PenerimaAdminModelData>[];
      v.forEach((v) {
        arr0.add(PenerimaAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
