///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubditAdminModelData {
/*
{
  "id": "18",
  "subdit_code": "H218",
  "subdit_name": "INDUSTRIAL CLEANING"
} 
*/

  String? id;
  String? subditCode;
  String? subditName;

  SubditAdminModelData({
    this.id,
    this.subditCode,
    this.subditName,
  });
  SubditAdminModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    subditCode = json['subdit_code']?.toString();
    subditName = json['subdit_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['subdit_code'] = subditCode;
    data['subdit_name'] = subditName;
    return data;
  }
}

class SubditAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": "18",
      "subdit_code": "H218",
      "subdit_name": "INDUSTRIAL CLEANING"
    }
  ]
} 
*/

  String? result;
  List<SubditAdminModelData?>? data;

  SubditAdminModel({
    this.result,
    this.data,
  });
  SubditAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SubditAdminModelData>[];
      v.forEach((v) {
        arr0.add(SubditAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
