///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DaftarTransaksiBuyerModelDataDetail {
/*
{
  "ID": "1183",
  "nama": "Barang Atria",
  "harga": "5000",
  "kode_produk": "ATR",
  "size": "",
  "deskripsi": "Desc Barang Atria",
  "SellerID": "196",
  "hapus": "0",
  "foto": "https://mspeed.erdata.id/produk/",
  "IDKategori": "1",
  "SellerNama": "Atria Seller",
  "no_rek": "",
  "qty": "2",
  "harga_akhir": "10000",
  "diterima": "YES",
  "dikomplain": "NO",
  "komplain": "",
  "IDOrder": "710"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? SellerNama;
  String? noRek;
  String? qty;
  String? hargaAkhir;
  String? diterima;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DaftarTransaksiBuyerModelDataDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.SellerNama,
    this.noRek,
    this.qty,
    this.hargaAkhir,
    this.diterima,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DaftarTransaksiBuyerModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    SellerNama = json['SellerNama']?.toString();
    noRek = json['no_rek']?.toString();
    qty = json['qty']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    diterima = json['diterima']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['SellerNama'] = SellerNama;
    data['no_rek'] = noRek;
    data['qty'] = qty;
    data['harga_akhir'] = hargaAkhir;
    data['diterima'] = diterima;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DaftarTransaksiBuyerModelData {
/*
{
  "ID": "74",
  "Created": "2024-07-03 13:04:05",
  "Updated": "2024-07-03 13:04:05",
  "nomor_order": "0067/SPS/E-Katalog/24",
  "subtotal": "10000",
  "pajak": "1100",
  "ongkir": "0",
  "total": "11100",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Penerima JP2 Niko",
  "alamat": "Jl. Pacitan – Trenggalek Km. 55 Desa Sukorejo, Kecamatan Sudimoro, Kabupaten Pacitan",
  "telp": "089649867832",
  "status": "Pesanan Dibayar",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "COMPROATRIA2024.pdf",
  "penerimaID": "108",
  "penerimaStr": null,
  "keuanganID": null,
  "keuanganStr": null,
  "estPengiriman": "2024-07-04",
  "estPengiriman2": "2024-07-05",
  "nomor_invoice": "0067/INV/E-Katalog/24",
  "nomor_suratjalan": "0067/SJL/E-Katalog/24",
  "nomor_kwitansi": "0067/KWT/E-Katalog/24",
  "read_status": "1",
  "tgl_ttd_kwitansi": "2024-07-03 13:16:20",
  "tgl_ttd_surat_pesanan": null,
  "tgl_ttd_surat_jalan": null,
  "tgl_ttd_invoice": null,
  "jum": "1",
  "SellerNama": "Atria Seller",
  "detail": [
    {
      "ID": "1183",
      "nama": "Barang Atria",
      "harga": "5000",
      "kode_produk": "ATR",
      "size": "",
      "deskripsi": "Desc Barang Atria",
      "SellerID": "196",
      "hapus": "0",
      "foto": "https://mspeed.erdata.id/produk/",
      "IDKategori": "1",
      "SellerNama": "Atria Seller",
      "no_rek": "",
      "qty": "2",
      "harga_akhir": "10000",
      "diterima": "YES",
      "dikomplain": "NO",
      "komplain": "",
      "IDOrder": "710"
    }
  ]
}
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? jum;
  String? SellerNama;
  List<DaftarTransaksiBuyerModelDataDetail?>? detail;

  DaftarTransaksiBuyerModelData({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.jum,
    this.SellerNama,
    this.detail,
  });
  DaftarTransaksiBuyerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    jum = json['jum']?.toString();
    SellerNama = json['SellerNama']?.toString();
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <DaftarTransaksiBuyerModelDataDetail>[];
      v.forEach((v) {
        arr0.add(DaftarTransaksiBuyerModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['jum'] = jum;
    data['SellerNama'] = SellerNama;
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    return data;
  }
}

class DaftarTransaksiBuyerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "74",
      "Created": "2024-07-03 13:04:05",
      "Updated": "2024-07-03 13:04:05",
      "nomor_order": "0067/SPS/E-Katalog/24",
      "subtotal": "10000",
      "pajak": "1100",
      "ongkir": "0",
      "total": "11100",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Penerima JP2 Niko",
      "alamat": "Jl. Pacitan – Trenggalek Km. 55 Desa Sukorejo, Kecamatan Sudimoro, Kabupaten Pacitan",
      "telp": "089649867832",
      "status": "Pesanan Dibayar",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "COMPROATRIA2024.pdf",
      "penerimaID": "108",
      "penerimaStr": null,
      "keuanganID": null,
      "keuanganStr": null,
      "estPengiriman": "2024-07-04",
      "estPengiriman2": "2024-07-05",
      "nomor_invoice": "0067/INV/E-Katalog/24",
      "nomor_suratjalan": "0067/SJL/E-Katalog/24",
      "nomor_kwitansi": "0067/KWT/E-Katalog/24",
      "read_status": "1",
      "tgl_ttd_kwitansi": "2024-07-03 13:16:20",
      "tgl_ttd_surat_pesanan": null,
      "tgl_ttd_surat_jalan": null,
      "tgl_ttd_invoice": null,
      "jum": "1",
      "SellerNama": "Atria Seller",
      "detail": [
        {
          "ID": "1183",
          "nama": "Barang Atria",
          "harga": "5000",
          "kode_produk": "ATR",
          "size": "",
          "deskripsi": "Desc Barang Atria",
          "SellerID": "196",
          "hapus": "0",
          "foto": "https://mspeed.erdata.id/produk/",
          "IDKategori": "1",
          "SellerNama": "Atria Seller",
          "no_rek": "",
          "qty": "2",
          "harga_akhir": "10000",
          "diterima": "YES",
          "dikomplain": "NO",
          "komplain": "",
          "IDOrder": "710"
        }
      ]
    }
  ]
}
*/

  String? result;
  List<DaftarTransaksiBuyerModelData?>? data;

  DaftarTransaksiBuyerModel({
    this.result,
    this.data,
  });
  DaftarTransaksiBuyerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DaftarTransaksiBuyerModelData>[];
      v.forEach((v) {
        arr0.add(DaftarTransaksiBuyerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
