///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetailTransaksiBuyerModelDataTimeline {
  /*
{
  "label": "Pesanan Baru",
  "time": "2025-02-21",
  "desc": "a"
} 
*/

  String? label;
  String? time;
  String? desc;

  DetailTransaksiBuyerModelDataTimeline({this.label, this.time, this.desc});
  DetailTransaksiBuyerModelDataTimeline.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    time = json['time']?.toString();
    desc = json['desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['time'] = time;
    data['desc'] = desc;
    return data;
  }
}

class DetailTransaksiBuyerModelDataDetail {
  /*
{
  "ID": "1200",
  "nama": "Bat Base",
  "harga": "10000",
  "kode_produk": "BAT-123",
  "size": "",
  "deskripsi": "ASB",
  "SellerID": "196",
  "hapus": "0",
  "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
  "IDKategori": "4",
  "SellerNama": "Atria Seller",
  "no_rek": "",
  "qty": "1",
  "harga_akhir": "10000",
  "diterima": "NO",
  "dikomplain": "NO",
  "komplain": "",
  "IDOrder": "746"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? SellerNama;
  String? noRek;
  String? qty;
  String? hargaAkhir;
  String? diterima;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DetailTransaksiBuyerModelDataDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.SellerNama,
    this.noRek,
    this.qty,
    this.hargaAkhir,
    this.diterima,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DetailTransaksiBuyerModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    SellerNama = json['SellerNama']?.toString();
    noRek = json['no_rek']?.toString();
    qty = json['qty']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    diterima = json['diterima']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['SellerNama'] = SellerNama;
    data['no_rek'] = noRek;
    data['qty'] = qty;
    data['harga_akhir'] = hargaAkhir;
    data['diterima'] = diterima;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DetailTransaksiBuyerModelDataParentOrderModel {
  /*
{
  "ID": "105",
  "Created": "2024-08-20 10:40:34",
  "Updated": "2024-08-20 10:40:34",
  "nomor_order": "0098/SPS/E-Katalog/24",
  "subtotal": "-1000",
  "pajak": "11000",
  "ongkir": "10000",
  "total": "10000",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Atria Buyer",
  "alamat": "Jalan Surabay No 1",
  "telp": "",
  "status": "PESANAN_BARU",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "148",
  "penerimaStr": "null",
  "keuanganID": "null",
  "keuanganStr": "null",
  "estPengiriman": "2024-08-28",
  "estPengiriman2": "2024-08-30",
  "nomor_invoice": "0098/INV/E-Katalog/24",
  "nomor_suratjalan": "0098/SJL/E-Katalog/24",
  "nomor_kwitansi": "0098/KWT/E-Katalog/24",
  "read_status": "1",
  "tgl_ttd_kwitansi": "null",
  "tgl_ttd_surat_pesanan": "null",
  "tgl_ttd_surat_jalan": "null",
  "tgl_ttd_invoice": "null",
  "TempOrderID": "null",
  "SellerNama": "Atria Seller",
  "SellerAlamat": "Surabaya",
  "kelengkapan_npwp": "1",
  "PenerimaNama": "Penerima Tomy",
  "PenerimaTelp": "+62 852-4147-6413",
  "dpp": "null",
  "sp_pkp": "sppkp-2025-124720pm-loginPage1.png",
  "pic": "Sales A - 0101010101",
  "nomor_dpp": "1/DPP-SP/XII/2022",
  "jumlampiran": "0"
} 
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? TempOrderID;
  String? SellerNama;
  String? SellerAlamat;
  String? kelengkapanNpwp;
  String? PenerimaNama;
  String? PenerimaTelp;
  String? dpp;
  String? spPkp;
  String? pic;
  String? nomorDpp;
  String? jumlampiran;

  DetailTransaksiBuyerModelDataParentOrderModel({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.TempOrderID,
    this.SellerNama,
    this.SellerAlamat,
    this.kelengkapanNpwp,
    this.PenerimaNama,
    this.PenerimaTelp,
    this.dpp,
    this.spPkp,
    this.pic,
    this.nomorDpp,
    this.jumlampiran,
  });
  DetailTransaksiBuyerModelDataParentOrderModel.fromJson(
    Map<String, dynamic> json,
  ) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    TempOrderID = json['TempOrderID']?.toString();
    SellerNama = json['SellerNama']?.toString();
    SellerAlamat = json['SellerAlamat']?.toString();
    kelengkapanNpwp = json['kelengkapan_npwp']?.toString();
    PenerimaNama = json['PenerimaNama']?.toString();
    PenerimaTelp = json['PenerimaTelp']?.toString();
    dpp = json['dpp']?.toString();
    spPkp = json['sp_pkp']?.toString();
    pic = json['pic']?.toString();
    nomorDpp = json['nomor_dpp']?.toString();
    jumlampiran = json['jumlampiran']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['TempOrderID'] = TempOrderID;
    data['SellerNama'] = SellerNama;
    data['SellerAlamat'] = SellerAlamat;
    data['kelengkapan_npwp'] = kelengkapanNpwp;
    data['PenerimaNama'] = PenerimaNama;
    data['PenerimaTelp'] = PenerimaTelp;
    data['dpp'] = dpp;
    data['sp_pkp'] = spPkp;
    data['pic'] = pic;
    data['nomor_dpp'] = nomorDpp;
    data['jumlampiran'] = jumlampiran;
    return data;
  }
}

class DetailTransaksiBuyerModelData {
  /*
{
  "NamaBuyer": "a",
  "NamaDepartment": "",
  "title": "Detail Order",
  "ParentOrderModel": {
    "ID": "105",
    "Created": "2024-08-20 10:40:34",
    "Updated": "2024-08-20 10:40:34",
    "nomor_order": "0098/SPS/E-Katalog/24",
    "subtotal": "-1000",
    "pajak": "11000",
    "ongkir": "10000",
    "total": "10000",
    "BuyerID": "148",
    "SellerID": "196",
    "nama": "Atria Buyer",
    "alamat": "Jalan Surabay No 1",
    "telp": "",
    "status": "PESANAN_BARU",
    "PengajuanID": "49",
    "keterangan": "",
    "bukti": "",
    "penerimaID": "148",
    "penerimaStr": "null",
    "keuanganID": "null",
    "keuanganStr": "null",
    "estPengiriman": "2024-08-28",
    "estPengiriman2": "2024-08-30",
    "nomor_invoice": "0098/INV/E-Katalog/24",
    "nomor_suratjalan": "0098/SJL/E-Katalog/24",
    "nomor_kwitansi": "0098/KWT/E-Katalog/24",
    "read_status": "1",
    "tgl_ttd_kwitansi": "null",
    "tgl_ttd_surat_pesanan": "null",
    "tgl_ttd_surat_jalan": "null",
    "tgl_ttd_invoice": "null",
    "TempOrderID": "null",
    "SellerNama": "Atria Seller",
    "SellerAlamat": "Surabaya",
    "kelengkapan_npwp": "1",
    "PenerimaNama": "Penerima Tomy",
    "PenerimaTelp": "+62 852-4147-6413",
    "dpp": "null",
    "sp_pkp": "sppkp-2025-124720pm-loginPage1.png",
    "pic": "Sales A - 0101010101",
    "nomor_dpp": "1/DPP-SP/XII/2022",
    "jumlampiran": "0"
  },
  "lengkap": "",
  "detail": [
    {
      "ID": "1200",
      "nama": "Bat Base",
      "harga": "10000",
      "kode_produk": "BAT-123",
      "size": "",
      "deskripsi": "ASB",
      "SellerID": "196",
      "hapus": "0",
      "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
      "IDKategori": "4",
      "SellerNama": "Atria Seller",
      "no_rek": "",
      "qty": "1",
      "harga_akhir": "10000",
      "diterima": "NO",
      "dikomplain": "NO",
      "komplain": "",
      "IDOrder": "746"
    }
  ],
  "timeline": [
    {
      "label": "Pesanan Baru",
      "time": "2025-02-21",
      "desc": "a"
    }
  ],
  "hakakses": "BUYER"
} 
*/

  String? NamaBuyer;
  String? NamaDepartment;
  String? title;
  DetailTransaksiBuyerModelDataParentOrderModel? ParentOrderModel;
  String? lengkap;
  List<DetailTransaksiBuyerModelDataDetail?>? detail;
  List<DetailTransaksiBuyerModelDataTimeline?>? timeline;
  String? hakakses;

  DetailTransaksiBuyerModelData({
    this.NamaBuyer,
    this.NamaDepartment,
    this.title,
    this.ParentOrderModel,
    this.lengkap,
    this.detail,
    this.timeline,
    this.hakakses,
  });
  DetailTransaksiBuyerModelData.fromJson(Map<String, dynamic> json) {
    NamaBuyer = json['NamaBuyer']?.toString();
    NamaDepartment = json['NamaDepartment']?.toString();
    title = json['title']?.toString();
    ParentOrderModel =
        (json['ParentOrderModel'] != null)
            ? DetailTransaksiBuyerModelDataParentOrderModel.fromJson(
              json['ParentOrderModel'],
            )
            : null;
    lengkap = json['lengkap']?.toString();
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <DetailTransaksiBuyerModelDataDetail>[];
      v.forEach((v) {
        arr0.add(DetailTransaksiBuyerModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
    if (json['timeline'] != null) {
      final v = json['timeline'];
      final arr0 = <DetailTransaksiBuyerModelDataTimeline>[];
      v.forEach((v) {
        arr0.add(DetailTransaksiBuyerModelDataTimeline.fromJson(v));
      });
      timeline = arr0;
    }
    hakakses = json['hakakses']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['NamaBuyer'] = NamaBuyer;
    data['NamaDepartment'] = NamaDepartment;
    data['title'] = title;
    if (ParentOrderModel != null) {
      data['ParentOrderModel'] = ParentOrderModel!.toJson();
    }
    data['lengkap'] = lengkap;
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    if (timeline != null) {
      final v = timeline;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['timeline'] = arr0;
    }
    data['hakakses'] = hakakses;
    return data;
  }
}

class DetailTransaksiBuyerModel {
  /*
{
  "result": "success",
  "data": {
    "NamaBuyer": "a",
    "NamaDepartment": "",
    "title": "Detail Order",
    "ParentOrderModel": {
      "ID": "105",
      "Created": "2024-08-20 10:40:34",
      "Updated": "2024-08-20 10:40:34",
      "nomor_order": "0098/SPS/E-Katalog/24",
      "subtotal": "-1000",
      "pajak": "11000",
      "ongkir": "10000",
      "total": "10000",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Atria Buyer",
      "alamat": "Jalan Surabay No 1",
      "telp": "",
      "status": "PESANAN_BARU",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "148",
      "penerimaStr": "null",
      "keuanganID": "null",
      "keuanganStr": "null",
      "estPengiriman": "2024-08-28",
      "estPengiriman2": "2024-08-30",
      "nomor_invoice": "0098/INV/E-Katalog/24",
      "nomor_suratjalan": "0098/SJL/E-Katalog/24",
      "nomor_kwitansi": "0098/KWT/E-Katalog/24",
      "read_status": "1",
      "tgl_ttd_kwitansi": "null",
      "tgl_ttd_surat_pesanan": "null",
      "tgl_ttd_surat_jalan": "null",
      "tgl_ttd_invoice": "null",
      "TempOrderID": "null",
      "SellerNama": "Atria Seller",
      "SellerAlamat": "Surabaya",
      "kelengkapan_npwp": "1",
      "PenerimaNama": "Penerima Tomy",
      "PenerimaTelp": "+62 852-4147-6413",
      "dpp": "null",
      "sp_pkp": "sppkp-2025-124720pm-loginPage1.png",
      "pic": "Sales A - 0101010101",
      "nomor_dpp": "1/DPP-SP/XII/2022",
      "jumlampiran": "0"
    },
    "lengkap": "",
    "detail": [
      {
        "ID": "1200",
        "nama": "Bat Base",
        "harga": "10000",
        "kode_produk": "BAT-123",
        "size": "",
        "deskripsi": "ASB",
        "SellerID": "196",
        "hapus": "0",
        "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
        "IDKategori": "4",
        "SellerNama": "Atria Seller",
        "no_rek": "",
        "qty": "1",
        "harga_akhir": "10000",
        "diterima": "NO",
        "dikomplain": "NO",
        "komplain": "",
        "IDOrder": "746"
      }
    ],
    "timeline": [
      {
        "label": "Pesanan Baru",
        "time": "2025-02-21",
        "desc": "a"
      }
    ],
    "hakakses": "BUYER"
  }
} 
*/

  String? result;
  DetailTransaksiBuyerModelData? data;

  DetailTransaksiBuyerModel({this.result, this.data});
  DetailTransaksiBuyerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data =
        (json['data'] != null)
            ? DetailTransaksiBuyerModelData.fromJson(json['data'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
    return data;
  }
}
