///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RiwayatNegoTransaksiModelData {
/*
{
  "id": 1,
  "harga_awal": "5000",
  "nego": "4000",
  "status": "Diterima seller"
}
*/

  int? id;
  String? hargaAwal;
  String? nego;
  String? status;

  RiwayatNegoTransaksiModelData({
    this.id,
    this.hargaAwal,
    this.nego,
    this.status,
  });
  RiwayatNegoTransaksiModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    hargaAwal = json['harga_awal']?.toString();
    nego = json['nego']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['harga_awal'] = hargaAwal;
    data['nego'] = nego;
    data['status'] = status;
    return data;
  }
}

class RiwayatNegoTransaksiModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": 1,
      "harga_awal": "5000",
      "nego": "4000",
      "status": "Diterima seller"
    }
  ]
}
*/

  String? result;
  List<RiwayatNegoTransaksiModelData?>? data;

  RiwayatNegoTransaksiModel({
    this.result,
    this.data,
  });
  RiwayatNegoTransaksiModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RiwayatNegoTransaksiModelData>[];
      v.forEach((v) {
        arr0.add(RiwayatNegoTransaksiModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
