///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetailTransaksiKeuanganModelDataTimeline {
/*
{
  "label": "Pesanan Baru",
  "time": "2025-02-21",
  "desc": "a"
} 
*/

  String? label;
  String? time;
  String? desc;

  DetailTransaksiKeuanganModelDataTimeline({
    this.label,
    this.time,
    this.desc,
  });
  DetailTransaksiKeuanganModelDataTimeline.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    time = json['time']?.toString();
    desc = json['desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['time'] = time;
    data['desc'] = desc;
    return data;
  }
}

class DetailTransaksiKeuanganModelDataDetail {
/*
{
  "ID": "60",
  "nama": "THREEBOND 1211",
  "harga": "422750",
  "kode_produk": "",
  "size": "",
  "qty": "4",
  "deskripsi": "Jenis: Silikon Aplikasi: Bonding, Gasketing, Sealing Industri: Otomotif, Manufaktur Umum, Kelautan, Motor Sport, Perakitan Produk ThreeBond TB1211 adalah gasket cair silikon RTV komponen tunggal putih, bebas mengalir, bebas pelarut dan non-asam.",
  "SellerID": "106",
  "foto": "https://mspeed.erdata.id/produk/THREEBOND1211.png",
  "IDKategori": "1",
  "harga_akhir": "1691000",
  "dikomplain": "NO",
  "komplain": "",
  "IDOrder": "10"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? foto;
  String? IDKategori;
  String? hargaAkhir;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DetailTransaksiKeuanganModelDataDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.foto,
    this.IDKategori,
    this.hargaAkhir,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DetailTransaksiKeuanganModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['harga_akhir'] = hargaAkhir;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DetailTransaksiKeuanganModelDataParentOrderModel {
/*
{
  "ID": "2",
  "Created": "2023-07-18 13:22:41",
  "Updated": "2023-07-18 13:22:41",
  "nomor_order": "0002/SPS/E-Katalog/23",
  "subtotal": "26039500",
  "pajak": "2864345",
  "ongkir": "0",
  "total": "28903845",
  "BuyerID": "101",
  "SellerID": "106",
  "nama": "Penerima JP2 Niko",
  "alamat": "Jl. Surabaya - Paiton Km 140, Probolinggo Jawa Timur",
  "telp": "089649867832",
  "status": "TELAH_DIBAYAR",
  "PengajuanID": "45",
  "keterangan": "Catatan 99",
  "penerimaID": "108",
  "penerimaStr": "null",
  "keuanganID": "null",
  "keuanganStr": "null",
  "estPengiriman": "2023-07-19",
  "estPengiriman2": "2024-08-20",
  "nomor_invoice": "0002/INV/E-Katalog/23",
  "nomor_suratjalan": "0002/SJL/E-Katalog/23",
  "nomor_kwitansi": "0002/KWT/E-Katalog/23",
  "read_status": "1",
  "tgl_ttd_kwitansi": "2023-07-24 08:16:54",
  "tgl_ttd_surat_pesanan": "2023-07-24 08:16:54",
  "tgl_ttd_surat_jalan": "2023-07-19 15:03:17",
  "tgl_ttd_invoice": "2023-07-24 08:16:54",
  "Rekening": "0605553721",
  "an_rek": "CV Singoyudho Nusantara",
  "bank": "BNI",
  "SellerNama": "Singoyudho Nusantara",
  "jum": "9"
} 
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? Rekening;
  String? anRek;
  String? bank;
  String? SellerNama;
  String? jum;

  DetailTransaksiKeuanganModelDataParentOrderModel({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.Rekening,
    this.anRek,
    this.bank,
    this.SellerNama,
    this.jum,
  });
  DetailTransaksiKeuanganModelDataParentOrderModel.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    Created = json['Created']?.toString() ?? json['created_at']?.toString();
    Updated = json['Updated']?.toString() ?? json['updated_at']?.toString();
    nomorOrder = json['nomor_order']?.toString() ?? json['order_number']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString() ?? json['shipping']?['cost']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString() ?? json['actors_snapshot']?['buyer']?['id']?.toString();
    SellerID = json['SellerID']?.toString() ?? json['seller_snapshot']?['id']?.toString();
    nama = json['nama']?.toString() ?? json['actors_snapshot']?['buyer']?['name']?.toString();
    alamat = json['alamat']?.toString() ?? json['seller_snapshot']?['address']?.toString();
    telp = json['telp']?.toString() ?? json['seller_snapshot']?['phone']?.toString();
    status = json['status']?.toString() ?? json['payment_status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    penerimaID = json['penerimaID']?.toString() ?? json['actors_snapshot']?['recipient']?['id']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString() ?? json['actors_snapshot']?['finance']?['id']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString() ?? json['shipping']?['estimated_start']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString() ?? json['shipping']?['estimated_end']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString() ?? json['receipt_number']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    Rekening = json['Rekening']?.toString();
    anRek = json['an_rek']?.toString();
    bank = json['bank']?.toString();
    SellerNama = json['SellerNama']?.toString() ?? json['seller_snapshot']?['name']?.toString();
    jum = json['jum']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['Rekening'] = Rekening;
    data['an_rek'] = anRek;
    data['bank'] = bank;
    data['SellerNama'] = SellerNama;
    data['jum'] = jum;
    return data;
  }
}

class DetailTransaksiKeuanganModelData {
/*
{
  "ParentOrderModel": {
    "ID": "2",
    "Created": "2023-07-18 13:22:41",
    "Updated": "2023-07-18 13:22:41",
    "nomor_order": "0002/SPS/E-Katalog/23",
    "subtotal": "26039500",
    "pajak": "2864345",
    "ongkir": "0",
    "total": "28903845",
    "BuyerID": "101",
    "SellerID": "106",
    "nama": "Penerima JP2 Niko",
    "alamat": "Jl. Surabaya - Paiton Km 140, Probolinggo Jawa Timur",
    "telp": "089649867832",
    "status": "TELAH_DIBAYAR",
    "PengajuanID": "45",
    "keterangan": "Catatan 99",
    "penerimaID": "108",
    "penerimaStr": "null",
    "keuanganID": "null",
    "keuanganStr": "null",
    "estPengiriman": "2023-07-19",
    "estPengiriman2": "2024-08-20",
    "nomor_invoice": "0002/INV/E-Katalog/23",
    "nomor_suratjalan": "0002/SJL/E-Katalog/23",
    "nomor_kwitansi": "0002/KWT/E-Katalog/23",
    "read_status": "1",
    "tgl_ttd_kwitansi": "2023-07-24 08:16:54",
    "tgl_ttd_surat_pesanan": "2023-07-24 08:16:54",
    "tgl_ttd_surat_jalan": "2023-07-19 15:03:17",
    "tgl_ttd_invoice": "2023-07-24 08:16:54",
    "Rekening": "0605553721",
    "an_rek": "CV Singoyudho Nusantara",
    "bank": "BNI",
    "SellerNama": "Singoyudho Nusantara",
    "jum": "9"
  },
  "detail": [
    {
      "ID": "60",
      "nama": "THREEBOND 1211",
      "harga": "422750",
      "kode_produk": "",
      "size": "",
      "qty": "4",
      "deskripsi": "Jenis: Silikon Aplikasi: Bonding, Gasketing, Sealing Industri: Otomotif, Manufaktur Umum, Kelautan, Motor Sport, Perakitan Produk ThreeBond TB1211 adalah gasket cair silikon RTV komponen tunggal putih, bebas mengalir, bebas pelarut dan non-asam.",
      "SellerID": "106",
      "foto": "https://mspeed.erdata.id/produk/THREEBOND1211.png",
      "IDKategori": "1",
      "harga_akhir": "1691000",
      "dikomplain": "NO",
      "komplain": "",
      "IDOrder": "10"
    }
  ],
  "timeline": [
    {
      "label": "Pesanan Baru",
      "time": "2025-02-21",
      "desc": "a"
    }
  ]
} 
*/

  DetailTransaksiKeuanganModelDataParentOrderModel? ParentOrderModel;
  List<DetailTransaksiKeuanganModelDataDetail?>? detail;
  List<DetailTransaksiKeuanganModelDataTimeline?>? timeline;

  DetailTransaksiKeuanganModelData({
    this.ParentOrderModel,
    this.detail,
    this.timeline,
  });
  DetailTransaksiKeuanganModelData.fromJson(Map<String, dynamic> json) {
    ParentOrderModel = (json['ParentOrderModel'] != null) ? DetailTransaksiKeuanganModelDataParentOrderModel.fromJson(json['ParentOrderModel']) : null;
  if (json['detail'] != null) {
  final v = json['detail'];
  final arr0 = <DetailTransaksiKeuanganModelDataDetail>[];
  v.forEach((v) {
  arr0.add(DetailTransaksiKeuanganModelDataDetail.fromJson(v));
  });
    detail = arr0;
    }
  if (json['timeline'] != null) {
  final v = json['timeline'];
  final arr0 = <DetailTransaksiKeuanganModelDataTimeline>[];
  v.forEach((v) {
  arr0.add(DetailTransaksiKeuanganModelDataTimeline.fromJson(v));
  });
    timeline = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ParentOrderModel != null) {
      data['ParentOrderModel'] = ParentOrderModel!.toJson();
    }
    if (detail != null) {
      final v = detail;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['detail'] = arr0;
    }
    if (timeline != null) {
      final v = timeline;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['timeline'] = arr0;
    }
    return data;
  }
}

class DetailTransaksiKeuanganModel {
/*
{
  "result": "success",
  "data": {
    "ParentOrderModel": {
      "ID": "2",
      "Created": "2023-07-18 13:22:41",
      "Updated": "2023-07-18 13:22:41",
      "nomor_order": "0002/SPS/E-Katalog/23",
      "subtotal": "26039500",
      "pajak": "2864345",
      "ongkir": "0",
      "total": "28903845",
      "BuyerID": "101",
      "SellerID": "106",
      "nama": "Penerima JP2 Niko",
      "alamat": "Jl. Surabaya - Paiton Km 140, Probolinggo Jawa Timur",
      "telp": "089649867832",
      "status": "TELAH_DIBAYAR",
      "PengajuanID": "45",
      "keterangan": "Catatan 99",
      "penerimaID": "108",
      "penerimaStr": "null",
      "keuanganID": "null",
      "keuanganStr": "null",
      "estPengiriman": "2023-07-19",
      "estPengiriman2": "2024-08-20",
      "nomor_invoice": "0002/INV/E-Katalog/23",
      "nomor_suratjalan": "0002/SJL/E-Katalog/23",
      "nomor_kwitansi": "0002/KWT/E-Katalog/23",
      "read_status": "1",
      "tgl_ttd_kwitansi": "2023-07-24 08:16:54",
      "tgl_ttd_surat_pesanan": "2023-07-24 08:16:54",
      "tgl_ttd_surat_jalan": "2023-07-19 15:03:17",
      "tgl_ttd_invoice": "2023-07-24 08:16:54",
      "Rekening": "0605553721",
      "an_rek": "CV Singoyudho Nusantara",
      "bank": "BNI",
      "SellerNama": "Singoyudho Nusantara",
      "jum": "9"
    },
    "detail": [
      {
        "ID": "60",
        "nama": "THREEBOND 1211",
        "harga": "422750",
        "kode_produk": "",
        "size": "",
        "qty": "4",
        "deskripsi": "Jenis: Silikon Aplikasi: Bonding, Gasketing, Sealing Industri: Otomotif, Manufaktur Umum, Kelautan, Motor Sport, Perakitan Produk ThreeBond TB1211 adalah gasket cair silikon RTV komponen tunggal putih, bebas mengalir, bebas pelarut dan non-asam.",
        "SellerID": "106",
        "foto": "https://mspeed.erdata.id/produk/THREEBOND1211.png",
        "IDKategori": "1",
        "harga_akhir": "1691000",
        "dikomplain": "NO",
        "komplain": "",
        "IDOrder": "10"
      }
    ],
    "timeline": [
      {
        "label": "Pesanan Baru",
        "time": "2025-02-21",
        "desc": "a"
      }
    ]
  }
} 
*/

  String? result;
  DetailTransaksiKeuanganModelData? data;

  DetailTransaksiKeuanganModel({
    this.result,
    this.data,
  });
  DetailTransaksiKeuanganModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? DetailTransaksiKeuanganModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
