///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DownloadModel {
/*
{
  "result": "success",
  "data": "https://mspeed.erdata.id/buyer/cetakkwitansi/99"
}
*/

  String? result;
  String? data;

  DownloadModel({
    this.result,
    this.data,
  });
  DownloadModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data;
    return data;
  }
}
