///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LihatLampiranModelData {
/*
{
  "faktur": "https://mspeed.erdata.id/lampiran/faktur_2_Faktur418.pdf",
  "enofa": "https://mspeed.erdata.id/lampiran/enofa_2_S-915_PPN.NSFP_WPJ.24_KP.1003_2023.pdf"
}
*/

  String? faktur;
  String? enofa;

  LihatLampiranModelData({
    this.faktur,
    this.enofa,
  });
  LihatLampiranModelData.fromJson(Map<String, dynamic> json) {
    faktur = json['faktur']?.toString();
    enofa = json['enofa']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['faktur'] = faktur;
    data['enofa'] = enofa;
    return data;
  }
}

class LihatLampiranModel {
/*
{
  "result": "success",
  "data": {
    "faktur": "https://mspeed.erdata.id/lampiran/faktur_2_Faktur418.pdf",
    "enofa": "https://mspeed.erdata.id/lampiran/enofa_2_S-915_PPN.NSFP_WPJ.24_KP.1003_2023.pdf"
  }
}
*/

  String? result;
  LihatLampiranModelData? data;

  LihatLampiranModel({
    this.result,
    this.data,
  });
  LihatLampiranModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? LihatLampiranModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
