///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetailPesananPenerimaModelDataTimeline {
  /*
{
  "label": "Pesanan Baru",
  "time": "2025-02-21",
  "desc": "a"
} 
*/

  String? label;
  String? time;
  String? desc;

  DetailPesananPenerimaModelDataTimeline({this.label, this.time, this.desc});
  DetailPesananPenerimaModelDataTimeline.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    time = json['time']?.toString();
    desc = json['desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['time'] = time;
    data['desc'] = desc;
    return data;
  }
}

class DetailPesananPenerimaModelDataDetail {
  /*
{
  "ID": "1184",
  "nama": "Boneka Woody",
  "harga": "100000",
  "kode_produk": "001",
  "size": "",
  "qty": "6",
  "deskripsi": "Boneka Woody Lucu Sekali",
  "SellerID": "196",
  "hapus": "0",
  "foto": "woody_toy_story_4-wallpaper-1280x1280.jpg",
  "IDKategori": "1",
  "harga_akhir": "600000",
  "diterima": "NO",
  "dikomplain": "NO",
  "komplain": "",
  "IDOrder": "724"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? hargaAkhir;
  String? diterima;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DetailPesananPenerimaModelDataDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.hargaAkhir,
    this.diterima,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DetailPesananPenerimaModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    diterima = json['diterima']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['harga_akhir'] = hargaAkhir;
    data['diterima'] = diterima;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DetailPesananPenerimaModelDataParentOrderModel {
  /*
{
  "ID": "83",
  "Created": "2024-07-31 10:45:53",
  "Updated": "2024-07-31 10:45:53",
  "nomor_order": "0076/SPS/E-Katalog/24",
  "subtotal": "1533450",
  "pajak": "550",
  "ongkir": "10000",
  "total": "1534000",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Atria Buyer",
  "alamat": "",
  "telp": "",
  "status": "PESANAN_DITERIMA",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "148",
  "penerimaStr": null,
  "keuanganID": null,
  "keuanganStr": null,
  "estPengiriman": "2023-07-28",
  "estPengiriman2": "2023-07-30",
  "nomor_invoice": "0076/INV/E-Katalog/24",
  "nomor_suratjalan": "0076/SJL/E-Katalog/24",
  "nomor_kwitansi": "0076/KWT/E-Katalog/24",
  "read_status": "2",
  "tgl_ttd_kwitansi": null,
  "tgl_ttd_surat_pesanan": null,
  "tgl_ttd_surat_jalan": null,
  "tgl_ttd_invoice": null
}
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;

  DetailPesananPenerimaModelDataParentOrderModel({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
  });
  DetailPesananPenerimaModelDataParentOrderModel.fromJson(
    Map<String, dynamic> json,
  ) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    Created = json['Created']?.toString() ?? json['created_at']?.toString();
    Updated = json['Updated']?.toString() ?? json['updated_at']?.toString();
    nomorOrder = json['nomor_order']?.toString() ?? json['order_number']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString() ?? json['shipping']?['cost']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString() ?? json['actors_snapshot']?['buyer']?['id']?.toString();
    SellerID = json['SellerID']?.toString() ?? json['seller_snapshot']?['id']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString() ?? json['seller_snapshot']?['address']?.toString();
    telp = json['telp']?.toString() ?? json['seller_snapshot']?['phone']?.toString();
    status = json['status']?.toString() ?? json['payment_status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString() ?? json['actors_snapshot']?['recipient']?['id']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString() ?? json['actors_snapshot']?['finance']?['id']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString() ?? json['shipping']?['estimated_start']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString() ?? json['shipping']?['estimated_end']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString() ?? json['receipt_number']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    return data;
  }
}

class DetailPesananPenerimaModelData {
  /*
{
  "ParentOrderModel": {
    "ID": "83",
    "Created": "2024-07-31 10:45:53",
    "Updated": "2024-07-31 10:45:53",
    "nomor_order": "0076/SPS/E-Katalog/24",
    "subtotal": "1533450",
    "pajak": "550",
    "ongkir": "10000",
    "total": "1534000",
    "BuyerID": "148",
    "SellerID": "196",
    "nama": "Atria Buyer",
    "alamat": "",
    "telp": "",
    "status": "PESANAN_DITERIMA",
    "PengajuanID": "49",
    "keterangan": "",
    "bukti": "",
    "penerimaID": "148",
    "penerimaStr": null,
    "keuanganID": null,
    "keuanganStr": null,
    "estPengiriman": "2023-07-28",
    "estPengiriman2": "2023-07-30",
    "nomor_invoice": "0076/INV/E-Katalog/24",
    "nomor_suratjalan": "0076/SJL/E-Katalog/24",
    "nomor_kwitansi": "0076/KWT/E-Katalog/24",
    "read_status": "2",
    "tgl_ttd_kwitansi": null,
    "tgl_ttd_surat_pesanan": null,
    "tgl_ttd_surat_jalan": null,
    "tgl_ttd_invoice": null
  },
  "detail": [
    {
      "ID": "1184",
      "nama": "Boneka Woody",
      "harga": "100000",
      "kode_produk": "001",
      "size": "",
      "qty": "6",
      "deskripsi": "Boneka Woody Lucu Sekali",
      "SellerID": "196",
      "hapus": "0",
      "foto": "woody_toy_story_4-wallpaper-1280x1280.jpg",
      "IDKategori": "1",
      "harga_akhir": "600000",
      "diterima": "NO",
      "dikomplain": "NO",
      "komplain": "",
      "IDOrder": "724"
    }
  ]
}
*/

  DetailPesananPenerimaModelDataParentOrderModel? ParentOrderModel;
  List<DetailPesananPenerimaModelDataDetail?>? detail;
  List<DetailPesananPenerimaModelDataTimeline?>? timeline;

  DetailPesananPenerimaModelData({
    this.ParentOrderModel,
    this.detail,
    this.timeline,
  });
  DetailPesananPenerimaModelData.fromJson(Map<String, dynamic> json) {
    ParentOrderModel =
        (json['ParentOrderModel'] != null)
            ? DetailPesananPenerimaModelDataParentOrderModel.fromJson(
              json['ParentOrderModel'],
            )
            : null;
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <DetailPesananPenerimaModelDataDetail>[];
      v.forEach((v) {
        arr0.add(DetailPesananPenerimaModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
    if (json['timeline'] != null) {
      final v = json['timeline'];
      final arr0 = <DetailPesananPenerimaModelDataTimeline>[];
      v.forEach((v) {
        arr0.add(DetailPesananPenerimaModelDataTimeline.fromJson(v));
      });
      timeline = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ParentOrderModel != null) {
      data['ParentOrderModel'] = ParentOrderModel!.toJson();
    }
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    if (timeline != null) {
      final v = timeline;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['timeline'] = arr0;
    }
    return data;
  }
}

class DetailPesananPenerimaModel {
  /*
{
  "result": "success",
  "data": {
    "ParentOrderModel": {
      "ID": "83",
      "Created": "2024-07-31 10:45:53",
      "Updated": "2024-07-31 10:45:53",
      "nomor_order": "0076/SPS/E-Katalog/24",
      "subtotal": "1533450",
      "pajak": "550",
      "ongkir": "10000",
      "total": "1534000",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Atria Buyer",
      "alamat": "",
      "telp": "",
      "status": "PESANAN_DITERIMA",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "148",
      "penerimaStr": null,
      "keuanganID": null,
      "keuanganStr": null,
      "estPengiriman": "2023-07-28",
      "estPengiriman2": "2023-07-30",
      "nomor_invoice": "0076/INV/E-Katalog/24",
      "nomor_suratjalan": "0076/SJL/E-Katalog/24",
      "nomor_kwitansi": "0076/KWT/E-Katalog/24",
      "read_status": "2",
      "tgl_ttd_kwitansi": null,
      "tgl_ttd_surat_pesanan": null,
      "tgl_ttd_surat_jalan": null,
      "tgl_ttd_invoice": null
    },
    "detail": [
      {
        "ID": "1184",
        "nama": "Boneka Woody",
        "harga": "100000",
        "kode_produk": "001",
        "size": "",
        "qty": "6",
        "deskripsi": "Boneka Woody Lucu Sekali",
        "SellerID": "196",
        "hapus": "0",
        "foto": "woody_toy_story_4-wallpaper-1280x1280.jpg",
        "IDKategori": "1",
        "harga_akhir": "600000",
        "diterima": "NO",
        "dikomplain": "NO",
        "komplain": "",
        "IDOrder": "724"
      }
    ]
  }
}
*/

  String? result;
  DetailPesananPenerimaModelData? data;

  DetailPesananPenerimaModel({this.result, this.data});
  DetailPesananPenerimaModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data =
        (json['data'] != null)
            ? DetailPesananPenerimaModelData.fromJson(json['data'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
    return data;
  }
}
