///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PesananPenerimaModelData {
/*
{
  "ID": "91",
  "Created": "2024-07-31 12:11:19",
  "Updated": "2024-07-31 12:11:19",
  "nomor_order": "0084/SPS/E-Katalog/24",
  "subtotal": "200000",
  "pajak": "0",
  "ongkir": "0",
  "total": "200000",
  "BuyerID": "148",
  "SellerID": "203",
  "nama": "Operasi MKP KP",
  "alamat": "Juanda Business Centre Blok A No. 4-6",
  "telp": "",
  "status": "TELAH_DIBAYAR",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "img_61dea2801cc5e1-10131711-36423950.jpg",
  "penerimaID": "124",
  "penerimaStr": null,
  "keuanganID": null,
  "keuanganStr": null,
  "estPengiriman": "2024-07-31",
  "estPengiriman2": "2024-08-01",
  "nomor_invoice": "0084/INV/E-Katalog/24",
  "nomor_suratjalan": "0084/SJL/E-Katalog/24",
  "nomor_kwitansi": "0084/KWT/E-Katalog/24",
  "read_status": "1",
  "tgl_ttd_kwitansi": "2024-07-31 13:09:36",
  "tgl_ttd_surat_pesanan": null,
  "tgl_ttd_surat_jalan": null,
  "tgl_ttd_invoice": null,
  "SellerNama": "PT Kreasi Mulia",
  "jum": "1"
}
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? SellerNama;
  String? jum;

  PesananPenerimaModelData({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.SellerNama,
    this.jum,
  });
  PesananPenerimaModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    SellerNama = json['SellerNama']?.toString();
    jum = json['jum']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['SellerNama'] = SellerNama;
    data['jum'] = jum;
    return data;
  }
}

class PesananPenerimaModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "91",
      "Created": "2024-07-31 12:11:19",
      "Updated": "2024-07-31 12:11:19",
      "nomor_order": "0084/SPS/E-Katalog/24",
      "subtotal": "200000",
      "pajak": "0",
      "ongkir": "0",
      "total": "200000",
      "BuyerID": "148",
      "SellerID": "203",
      "nama": "Operasi MKP KP",
      "alamat": "Juanda Business Centre Blok A No. 4-6",
      "telp": "",
      "status": "TELAH_DIBAYAR",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "img_61dea2801cc5e1-10131711-36423950.jpg",
      "penerimaID": "124",
      "penerimaStr": null,
      "keuanganID": null,
      "keuanganStr": null,
      "estPengiriman": "2024-07-31",
      "estPengiriman2": "2024-08-01",
      "nomor_invoice": "0084/INV/E-Katalog/24",
      "nomor_suratjalan": "0084/SJL/E-Katalog/24",
      "nomor_kwitansi": "0084/KWT/E-Katalog/24",
      "read_status": "1",
      "tgl_ttd_kwitansi": "2024-07-31 13:09:36",
      "tgl_ttd_surat_pesanan": null,
      "tgl_ttd_surat_jalan": null,
      "tgl_ttd_invoice": null,
      "SellerNama": "PT Kreasi Mulia",
      "jum": "1"
    }
  ]
}
*/

  String? result;
  List<PesananPenerimaModelData?>? data;

  PesananPenerimaModel({
    this.result,
    this.data,
  });
  PesananPenerimaModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PesananPenerimaModelData>[];
      v.forEach((v) {
        arr0.add(PesananPenerimaModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
