///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BuyerProductModelData {
/*
{
  "ID": "1200",
  "nama": "Bat Base",
  "harga": "10000",
  "kode_produk": "BAT-123",
  "size": "",
  "qty": "95",
  "deskripsi": "ASB",
  "SellerID": "196",
  "SellerNama": "Atria Seller",
  "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
  "IDKategori": "4",
  "NamaKategori": "ATK",
  "terjual": "3"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? SellerNama;
  String? foto;
  String? IDKategori;
  String? NamaKategori;
  String? terjual;

  BuyerProductModelData({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.SellerNama,
    this.foto,
    this.IDKategori,
    this.NamaKategori,
    this.terjual,
  });
  BuyerProductModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    SellerNama = json['SellerNama']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    NamaKategori = json['NamaKategori']?.toString();
    terjual = json['terjual']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['SellerNama'] = SellerNama;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['NamaKategori'] = NamaKategori;
    data['terjual'] = terjual;
    return data;
  }
}

class BuyerProductModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1200",
      "nama": "Bat Base",
      "harga": "10000",
      "kode_produk": "BAT-123",
      "size": "",
      "qty": "95",
      "deskripsi": "ASB",
      "SellerID": "196",
      "SellerNama": "Atria Seller",
      "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
      "IDKategori": "4",
      "NamaKategori": "ATK",
      "terjual": "3"
    }
  ]
} 
*/

  String? result;
  List<BuyerProductModelData?>? data;

  BuyerProductModel({
    this.result,
    this.data,
  });
  BuyerProductModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <BuyerProductModelData>[];
  v.forEach((v) {
  arr0.add(BuyerProductModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
