///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KategoriLokasiModelData {
/*
{
  "ID": "2",
  "kota": "Kabupaten Rembang"
} 
*/

  String? ID;
  String? kota;

  KategoriLokasiModelData({
    this.ID,
    this.kota,
  });
  KategoriLokasiModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    kota = json['kota']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['kota'] = kota;
    return data;
  }
}

class KategoriLokasiModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "2",
      "kota": "Kabupaten Rembang"
    }
  ]
} 
*/

  String? result;
  List<KategoriLokasiModelData?>? data;

  KategoriLokasiModel({
    this.result,
    this.data,
  });
  KategoriLokasiModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <KategoriLokasiModelData>[];
      v.forEach((v) {
        arr0.add(KategoriLokasiModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
