///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutOptionTaxModelData {
/*
{
  "id": 1,
  "name": "VAT",
  "percentage": 10
} 
*/

  int? id;
  String? name;
  int? percentage;

  CheckoutOptionTaxModelData({
    this.id,
    this.name,
    this.percentage,
  });
  CheckoutOptionTaxModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    percentage = json['percentage']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['percentage'] = percentage;
    return data;
  }
}

class CheckoutOptionTaxModel {
/*
{
  "success": true,
  "message": "",
  "data": [
    {
      "id": 1,
      "name": "VAT",
      "percentage": 10
    }
  ]
} 
*/

  bool? success;
  String? message;
  List<CheckoutOptionTaxModelData?>? data;

  CheckoutOptionTaxModel({
    this.success,
    this.message,
    this.data,
  });
  CheckoutOptionTaxModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CheckoutOptionTaxModelData>[];
      v.forEach((v) {
        arr0.add(CheckoutOptionTaxModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
