///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutOptionPaymentModelData {
/*
{
  "id": 1,
  "name": "COD"
} 
*/

  int? id;
  String? name;

  CheckoutOptionPaymentModelData({
    this.id,
    this.name,
  });
  CheckoutOptionPaymentModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CheckoutOptionPaymentModel {
/*
{
  "success": true,
  "message": "",
  "data": [
    {
      "id": 1,
      "name": "COD"
    }
  ]
} 
*/

  bool? success;
  String? message;
  List<CheckoutOptionPaymentModelData?>? data;

  CheckoutOptionPaymentModel({
    this.success,
    this.message,
    this.data,
  });
  CheckoutOptionPaymentModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CheckoutOptionPaymentModelData>[];
      v.forEach((v) {
        arr0.add(CheckoutOptionPaymentModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
