///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutModelDataAlamat {
/*
{
  "ID": "124",
  "email": "danirputra@mail.com",
  "password": "$2y$10$LQXmd8X0y6skJNqUV3/KaeJ71AXRDRZUoBL8GxyIT2cu7LGz0RQcy",
  "jenis": "SUB_BUYER",
  "aktif": "0",
  "hapus": "0",
  "kelengkapan": "0",
  "nama_perusahaan": "",
  "alamat": "Jalan Surabaya No 4567",
  "tagging": "",
  "kegiatan_usaha": "",
  "pemilik_toko": "",
  "firstname": "Operasi",
  "lastname": "MKP KP",
  "HakAksesID": "2",
  "status_pilihalamat": "1",
  "telp": "",
  "kabkota": "Sidoarjo",
  "subdit_id": "null"
}
*/

  String? ID;
  String? email;
  String? password;
  String? jenis;
  String? aktif;
  String? hapus;
  String? kelengkapan;
  String? namaPerusahaan;
  String? alamat;
  String? tagging;
  String? kegiatanUsaha;
  String? pemilikToko;
  String? firstname;
  String? lastname;
  String? HakAksesID;
  String? statusPilihalamat;
  String? telp;
  String? kabkota;
  String? subditId;

  CheckoutModelDataAlamat({
    this.ID,
    this.email,
    this.password,
    this.jenis,
    this.aktif,
    this.hapus,
    this.kelengkapan,
    this.namaPerusahaan,
    this.alamat,
    this.tagging,
    this.kegiatanUsaha,
    this.pemilikToko,
    this.firstname,
    this.lastname,
    this.HakAksesID,
    this.statusPilihalamat,
    this.telp,
    this.kabkota,
    this.subditId,
  });
  CheckoutModelDataAlamat.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    jenis = json['jenis']?.toString();
    aktif = json['aktif']?.toString();
    hapus = json['hapus']?.toString();
    kelengkapan = json['kelengkapan']?.toString();
    namaPerusahaan = json['nama_perusahaan']?.toString();
    alamat = json['alamat']?.toString();
    tagging = json['tagging']?.toString();
    kegiatanUsaha = json['kegiatan_usaha']?.toString();
    pemilikToko = json['pemilik_toko']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    HakAksesID = json['HakAksesID']?.toString();
    statusPilihalamat = json['status_pilihalamat']?.toString();
    telp = json['telp']?.toString();
    kabkota = json['kabkota']?.toString();
    subditId = json['subdit_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['email'] = email;
    data['password'] = password;
    data['jenis'] = jenis;
    data['aktif'] = aktif;
    data['hapus'] = hapus;
    data['kelengkapan'] = kelengkapan;
    data['nama_perusahaan'] = namaPerusahaan;
    data['alamat'] = alamat;
    data['tagging'] = tagging;
    data['kegiatan_usaha'] = kegiatanUsaha;
    data['pemilik_toko'] = pemilikToko;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['HakAksesID'] = HakAksesID;
    data['status_pilihalamat'] = statusPilihalamat;
    data['telp'] = telp;
    data['kabkota'] = kabkota;
    data['subdit_id'] = subditId;
    return data;
  }
}

class CheckoutModelDataTemporderProduk {
/*
{
  "ID": "1204",
  "nama": "BOR LISTRIK THERMAL",
  "harga": "2850000",
  "kode_produk": "BRG-270824",
  "size": "",
  "qty": "1",
  "IDProduk": "1204",
  "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  "SellerID": "196",
  "hapus": "0",
  "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
  "IDKategori": "3",
  "harga_awal": "2650000",
  "harga_akhir": 2650000,
  "CartID": "975",
  "status_nego": "1",
  "nego": "2500000",
  "nego2": "2700000",
  "nego3": "2650000",
  "namaseller": "Atria Seller",
  "harga_sebelum_nego": "2850000",
  "fixprice": "2650000",
  "fixstatus": "Nego Disetujui"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? IDProduk;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? hargaAwal;
  int? hargaAkhir;
  String? CartID;
  String? statusNego;
  String? nego;
  String? nego2;
  String? nego3;
  String? namaseller;
  String? hargaSebelumNego;
  String? fixprice;
  String? fixstatus;

  CheckoutModelDataTemporderProduk({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.IDProduk,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.hargaAwal,
    this.hargaAkhir,
    this.CartID,
    this.statusNego,
    this.nego,
    this.nego2,
    this.nego3,
    this.namaseller,
    this.hargaSebelumNego,
    this.fixprice,
    this.fixstatus,
  });
  CheckoutModelDataTemporderProduk.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    IDProduk = json['IDProduk']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    hargaAwal = json['harga_awal']?.toString();
    hargaAkhir = json['harga_akhir']?.toInt();
    CartID = json['CartID']?.toString();
    statusNego = json['status_nego']?.toString();
    nego = json['nego']?.toString();
    nego2 = json['nego2']?.toString();
    nego3 = json['nego3']?.toString();
    namaseller = json['namaseller']?.toString();
    hargaSebelumNego = json['harga_sebelum_nego']?.toString();
    fixprice = json['fixprice']?.toString();
    fixstatus = json['fixstatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['IDProduk'] = IDProduk;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['harga_awal'] = hargaAwal;
    data['harga_akhir'] = hargaAkhir;
    data['CartID'] = CartID;
    data['status_nego'] = statusNego;
    data['nego'] = nego;
    data['nego2'] = nego2;
    data['nego3'] = nego3;
    data['namaseller'] = namaseller;
    data['harga_sebelum_nego'] = hargaSebelumNego;
    data['fixprice'] = fixprice;
    data['fixstatus'] = fixstatus;
    return data;
  }
}

class CheckoutModelDataTemporder {
/*
{
  "ID": "316",
  "status": "0",
  "BuyerID": "148",
  "pajak": "77550",
  "ongkir": "9999",
  "title": "Checkout",
  "produk": [
    {
      "ID": "1204",
      "nama": "BOR LISTRIK THERMAL",
      "harga": "2850000",
      "kode_produk": "BRG-270824",
      "size": "",
      "qty": "1",
      "IDProduk": "1204",
      "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SellerID": "196",
      "hapus": "0",
      "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
      "IDKategori": "3",
      "harga_awal": "2650000",
      "harga_akhir": 2650000,
      "CartID": "975",
      "status_nego": "1",
      "nego": "2500000",
      "nego2": "2700000",
      "nego3": "2650000",
      "namaseller": "Atria Seller",
      "harga_sebelum_nego": "2850000",
      "fixprice": "2650000",
      "fixstatus": "Nego Disetujui"
    }
  ]
}
*/

  String? ID;
  String? status;
  String? BuyerID;
  String? pajak;
  String? ongkir;
  String? title;
  List<CheckoutModelDataTemporderProduk?>? produk;

  CheckoutModelDataTemporder({
    this.ID,
    this.status,
    this.BuyerID,
    this.pajak,
    this.ongkir,
    this.title,
    this.produk,
  });
  CheckoutModelDataTemporder.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    status = json['status']?.toString();
    BuyerID = json['BuyerID']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    title = json['title']?.toString();
    if (json['produk'] != null) {
      final v = json['produk'];
      final arr0 = <CheckoutModelDataTemporderProduk>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataTemporderProduk.fromJson(v));
      });
      produk = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['status'] = status;
    data['BuyerID'] = BuyerID;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['title'] = title;
    if (produk != null) {
      final v = produk;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['produk'] = arr0;
    }
    return data;
  }
}

class CheckoutModelDataProduk {
/*
{
  "ID": "1204",
  "nama": "BOR LISTRIK THERMAL",
  "harga": "2850000",
  "kode_produk": "BRG-270824",
  "size": "",
  "qty": "1",
  "IDProduk": "1204",
  "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  "SellerID": "196",
  "hapus": "0",
  "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
  "IDKategori": "3",
  "harga_awal": "2650000",
  "harga_akhir": 2650000,
  "CartID": "975",
  "status_nego": "1",
  "nego": "2500000",
  "nego2": "2700000",
  "nego3": "2650000",
  "namaseller": "Atria Seller",
  "harga_sebelum_nego": "2850000",
  "fixprice": "2650000",
  "fixstatus": "Nego Disetujui"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? IDProduk;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? hargaAwal;
  int? hargaAkhir;
  String? CartID;
  String? statusNego;
  String? nego;
  String? nego2;
  String? nego3;
  String? namaseller;
  String? hargaSebelumNego;
  String? fixprice;
  String? fixstatus;

  CheckoutModelDataProduk({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.IDProduk,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.hargaAwal,
    this.hargaAkhir,
    this.CartID,
    this.statusNego,
    this.nego,
    this.nego2,
    this.nego3,
    this.namaseller,
    this.hargaSebelumNego,
    this.fixprice,
    this.fixstatus,
  });
  CheckoutModelDataProduk.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    IDProduk = json['IDProduk']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    hargaAwal = json['harga_awal']?.toString();
    hargaAkhir = json['harga_akhir']?.toInt();
    CartID = json['CartID']?.toString();
    statusNego = json['status_nego']?.toString();
    nego = json['nego']?.toString();
    nego2 = json['nego2']?.toString();
    nego3 = json['nego3']?.toString();
    namaseller = json['namaseller']?.toString();
    hargaSebelumNego = json['harga_sebelum_nego']?.toString();
    fixprice = json['fixprice']?.toString();
    fixstatus = json['fixstatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['IDProduk'] = IDProduk;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['harga_awal'] = hargaAwal;
    data['harga_akhir'] = hargaAkhir;
    data['CartID'] = CartID;
    data['status_nego'] = statusNego;
    data['nego'] = nego;
    data['nego2'] = nego2;
    data['nego3'] = nego3;
    data['namaseller'] = namaseller;
    data['harga_sebelum_nego'] = hargaSebelumNego;
    data['fixprice'] = fixprice;
    data['fixstatus'] = fixstatus;
    return data;
  }
}

class CheckoutModelData {
/*
{
  "ID": "316",
  "status": "0",
  "BuyerID": "148",
  "pajak": "77550",
  "ongkir": "9999",
  "title": "Checkout",
  "produk": [
    {
      "ID": "1204",
      "nama": "BOR LISTRIK THERMAL",
      "harga": "2850000",
      "kode_produk": "BRG-270824",
      "size": "",
      "qty": "1",
      "IDProduk": "1204",
      "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SellerID": "196",
      "hapus": "0",
      "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
      "IDKategori": "3",
      "harga_awal": "2650000",
      "harga_akhir": 2650000,
      "CartID": "975",
      "status_nego": "1",
      "nego": "2500000",
      "nego2": "2700000",
      "nego3": "2650000",
      "namaseller": "Atria Seller",
      "harga_sebelum_nego": "2850000",
      "fixprice": "2650000",
      "fixstatus": "Nego Disetujui"
    }
  ],
  "temporder": {
    "ID": "316",
    "status": "0",
    "BuyerID": "148",
    "pajak": "77550",
    "ongkir": "9999",
    "title": "Checkout",
    "produk": [
      {
        "ID": "1204",
        "nama": "BOR LISTRIK THERMAL",
        "harga": "2850000",
        "kode_produk": "BRG-270824",
        "size": "",
        "qty": "1",
        "IDProduk": "1204",
        "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "SellerID": "196",
        "hapus": "0",
        "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
        "IDKategori": "3",
        "harga_awal": "2650000",
        "harga_akhir": 2650000,
        "CartID": "975",
        "status_nego": "1",
        "nego": "2500000",
        "nego2": "2700000",
        "nego3": "2650000",
        "namaseller": "Atria Seller",
        "harga_sebelum_nego": "2850000",
        "fixprice": "2650000",
        "fixstatus": "Nego Disetujui"
      }
    ]
  },
  "Alamat": {
    "ID": "124",
    "email": "danirputra@mail.com",
    "password": "$2y$10$LQXmd8X0y6skJNqUV3/KaeJ71AXRDRZUoBL8GxyIT2cu7LGz0RQcy",
    "jenis": "SUB_BUYER",
    "aktif": "0",
    "hapus": "0",
    "kelengkapan": "0",
    "nama_perusahaan": "",
    "alamat": "Jalan Surabaya No 4567",
    "tagging": "",
    "kegiatan_usaha": "",
    "pemilik_toko": "",
    "firstname": "Operasi",
    "lastname": "MKP KP",
    "HakAksesID": "2",
    "status_pilihalamat": "1",
    "telp": "",
    "kabkota": "Sidoarjo",
    "subdit_id": "null"
  }
}
*/

  String? ID;
  String? status;
  String? BuyerID;
  String? pajak;
  String? ongkir;
  String? title;
  List<CheckoutModelDataProduk?>? produk;
  CheckoutModelDataTemporder? temporder;
  CheckoutModelDataAlamat? Alamat;

  CheckoutModelData({
    this.ID,
    this.status,
    this.BuyerID,
    this.pajak,
    this.ongkir,
    this.title,
    this.produk,
    this.temporder,
    this.Alamat,
  });
  CheckoutModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    status = json['status']?.toString();
    BuyerID = json['BuyerID']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    title = json['title']?.toString();
    if (json['produk'] != null) {
      final v = json['produk'];
      final arr0 = <CheckoutModelDataProduk>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataProduk.fromJson(v));
      });
      produk = arr0;
    }
    temporder = (json['temporder'] != null) ? CheckoutModelDataTemporder.fromJson(json['temporder']) : null;
    Alamat = (json['Alamat'] != null) ? CheckoutModelDataAlamat.fromJson(json['Alamat']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['status'] = status;
    data['BuyerID'] = BuyerID;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['title'] = title;
    if (produk != null) {
      final v = produk;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['produk'] = arr0;
    }
    if (temporder != null) {
      data['temporder'] = temporder!.toJson();
    }
    if (Alamat != null) {
      data['Alamat'] = Alamat!.toJson();
    }
    return data;
  }
}

class CheckoutModel {
/*
{
  "result": "success",
  "data": {
    "ID": "316",
    "status": "0",
    "BuyerID": "148",
    "pajak": "77550",
    "ongkir": "9999",
    "title": "Checkout",
    "produk": [
      {
        "ID": "1204",
        "nama": "BOR LISTRIK THERMAL",
        "harga": "2850000",
        "kode_produk": "BRG-270824",
        "size": "",
        "qty": "1",
        "IDProduk": "1204",
        "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "SellerID": "196",
        "hapus": "0",
        "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
        "IDKategori": "3",
        "harga_awal": "2650000",
        "harga_akhir": 2650000,
        "CartID": "975",
        "status_nego": "1",
        "nego": "2500000",
        "nego2": "2700000",
        "nego3": "2650000",
        "namaseller": "Atria Seller",
        "harga_sebelum_nego": "2850000",
        "fixprice": "2650000",
        "fixstatus": "Nego Disetujui"
      }
    ],
    "temporder": {
      "ID": "316",
      "status": "0",
      "BuyerID": "148",
      "pajak": "77550",
      "ongkir": "9999",
      "title": "Checkout",
      "produk": [
        {
          "ID": "1204",
          "nama": "BOR LISTRIK THERMAL",
          "harga": "2850000",
          "kode_produk": "BRG-270824",
          "size": "",
          "qty": "1",
          "IDProduk": "1204",
          "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
          "SellerID": "196",
          "hapus": "0",
          "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
          "IDKategori": "3",
          "harga_awal": "2650000",
          "harga_akhir": 2650000,
          "CartID": "975",
          "status_nego": "1",
          "nego": "2500000",
          "nego2": "2700000",
          "nego3": "2650000",
          "namaseller": "Atria Seller",
          "harga_sebelum_nego": "2850000",
          "fixprice": "2650000",
          "fixstatus": "Nego Disetujui"
        }
      ]
    },
    "Alamat": {
      "ID": "124",
      "email": "danirputra@mail.com",
      "password": "$2y$10$LQXmd8X0y6skJNqUV3/KaeJ71AXRDRZUoBL8GxyIT2cu7LGz0RQcy",
      "jenis": "SUB_BUYER",
      "aktif": "0",
      "hapus": "0",
      "kelengkapan": "0",
      "nama_perusahaan": "",
      "alamat": "Jalan Surabaya No 4567",
      "tagging": "",
      "kegiatan_usaha": "",
      "pemilik_toko": "",
      "firstname": "Operasi",
      "lastname": "MKP KP",
      "HakAksesID": "2",
      "status_pilihalamat": "1",
      "telp": "",
      "kabkota": "Sidoarjo",
      "subdit_id": "null"
    }
  }
}
*/

  String? result;
  CheckoutModelData? data;

  CheckoutModel({
    this.result,
    this.data,
  });
  CheckoutModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? CheckoutModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
