///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutOptionShippingModelShippingListTypeList {
/*
{
  "courier_service_code": "oke",
  "courier_name": "JNE",
  "courier_code": "jne",
  "duration": "2 - 3 hari",
  "price": 8000,
  "price_desc": "Rp 8.000"
}
*/

  String? courierServiceCode;
  String? courierName;
  String? courierCode;
  String? duration;
  int? price;
  String? priceDesc;

  CheckoutOptionShippingModelShippingListTypeList({
    this.courierServiceCode,
    this.courierName,
    this.courierCode,
    this.duration,
    this.price,
    this.priceDesc,
  });
  CheckoutOptionShippingModelShippingListTypeList.fromJson(Map<String, dynamic> json) {
    courierServiceCode = json['courier_service_code']?.toString();
    courierName = json['courier_name']?.toString();
    courierCode = json['courier_code']?.toString();
    duration = json['duration']?.toString();
    price = json['price']?.toInt();
    priceDesc = json['price_desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['courier_service_code'] = courierServiceCode;
    data['courier_name'] = courierName;
    data['courier_code'] = courierCode;
    data['duration'] = duration;
    data['price'] = price;
    data['price_desc'] = priceDesc;
    return data;
  }
}

class CheckoutOptionShippingModelShippingList {
/*
{
  "type_name": "oke",
  "type_list": [
    {
      "courier_service_code": "oke",
      "courier_name": "JNE",
      "courier_code": "jne",
      "duration": "2 - 3 hari",
      "price": 8000,
      "price_desc": "Rp 8.000"
    }
  ]
}
*/

  String? typeName;
  List<CheckoutOptionShippingModelShippingListTypeList?>? typeList;

  CheckoutOptionShippingModelShippingList({
    this.typeName,
    this.typeList,
  });
  CheckoutOptionShippingModelShippingList.fromJson(Map<String, dynamic> json) {
    typeName = json['type_name']?.toString();
    if (json['type_list'] != null) {
      final v = json['type_list'];
      final arr0 = <CheckoutOptionShippingModelShippingListTypeList>[];
      v.forEach((v) {
        arr0.add(CheckoutOptionShippingModelShippingListTypeList.fromJson(v));
      });
      typeList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type_name'] = typeName;
    if (typeList != null) {
      final v = typeList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['type_list'] = arr0;
    }
    return data;
  }
}

class CheckoutOptionShippingModel {
/*
{
  "shipping_list": [
    {
      "type_name": "oke",
      "type_list": [
        {
          "courier_service_code": "oke",
          "courier_name": "JNE",
          "courier_code": "jne",
          "duration": "2 - 3 hari",
          "price": 8000,
          "price_desc": "Rp 8.000"
        }
      ]
    }
  ]
}
*/

  List<CheckoutOptionShippingModelShippingList?>? shippingList;

  CheckoutOptionShippingModel({
    this.shippingList,
  });
  CheckoutOptionShippingModel.fromJson(Map<String, dynamic> json) {
    if (json['shipping_list'] != null) {
      final v = json['shipping_list'];
      final arr0 = <CheckoutOptionShippingModelShippingList>[];
      v.forEach((v) {
        arr0.add(CheckoutOptionShippingModelShippingList.fromJson(v));
      });
      shippingList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (shippingList != null) {
      final v = shippingList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['shipping_list'] = arr0;
    }
    return data;
  }
}
