///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DoCheckoutModelMessages {
/*
{
  "success": "Checkout berhasil dilakukan"
}
*/

  String? success;

  DoCheckoutModelMessages({
    this.success,
  });
  DoCheckoutModelMessages.fromJson(Map<String, dynamic> json) {
    success = json['success']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class DoCheckoutModel {
/*
{
  "status": "success",
  "error": "null",
  "parent_id": 156,
  "messages": {
    "success": "Checkout berhasil dilakukan"
  }
}
*/

  String? status;
  String? error;
  int? parentId;
  DoCheckoutModelMessages? messages;

  DoCheckoutModel({
    this.status,
    this.error,
    this.parentId,
    this.messages,
  });
  DoCheckoutModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    error = json['error']?.toString();
    parentId = json['parent_id']?.toInt();
    messages = (json['messages'] != null) ? DoCheckoutModelMessages.fromJson(json['messages']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['error'] = error;
    data['parent_id'] = parentId;
    if (messages != null) {
      data['messages'] = messages!.toJson();
    }
    return data;
  }
}
