///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeSellerModelDataTablePalingLaris {
/*
{
  "nama": "Barang Atria",
  "qty": "5",
  "harga": "25000"
} 
*/

  String? nama;
  String? qty;
  String? harga;

  HomeSellerModelDataTablePalingLaris({
    this.nama,
    this.qty,
    this.harga,
  });
  HomeSellerModelDataTablePalingLaris.fromJson(Map<String, dynamic> json) {
    nama = json['nama']?.toString();
    qty = json['qty']?.toString();
    harga = json['harga']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nama'] = nama;
    data['qty'] = qty;
    data['harga'] = harga;
    return data;
  }
}

class HomeSellerModelDataTablePesananTerbaru {
/*
{
  "ID": "89",
  "Created": "2024-07-31 11:36:06",
  "Updated": "2024-07-31 11:36:06",
  "nomor_order": "0082/SPS/E-Katalog/24",
  "subtotal": "-550",
  "pajak": "550",
  "ongkir": "10000",
  "total": "0",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Atria Buyer",
  "alamat": "",
  "telp": "",
  "status": "PESANAN_BARU",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "148",
  "penerimaStr": "",
  "keuanganID": "",
  "keuanganStr": "",
  "estPengiriman": "0000-00-00",
  "estPengiriman2": "0000-00-00",
  "nomor_invoice": "0082/INV/E-Katalog/24",
  "nomor_suratjalan": "0082/SJL/E-Katalog/24",
  "nomor_kwitansi": "0082/KWT/E-Katalog/24",
  "read_status": "2",
  "tgl_ttd_kwitansi": "",
  "tgl_ttd_surat_pesanan": "",
  "tgl_ttd_surat_jalan": "",
  "tgl_ttd_invoice": "",
  "jum": "0"
} 
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? jum;

  HomeSellerModelDataTablePesananTerbaru({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.jum,
  });
  HomeSellerModelDataTablePesananTerbaru.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    jum = json['jum']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['jum'] = jum;
    return data;
  }
}

class HomeSellerModelData {
/*
{
  "produk": "3",
  "total_permintaan_pesanan": "5418950",
  "total_pendapatan": "26100",
  "total_belum_lunas": "5392850",
  "pesanan_baru": "8",
  "pesanan_diterima": "1",
  "pesanan_dikirim": "0",
  "barang_diterima": 0,
  "proses_pembayaran": 1,
  "pesanan_dibayar": "2",
  "table_pesanan_terbaru": [
    {
      "ID": "89",
      "Created": "2024-07-31 11:36:06",
      "Updated": "2024-07-31 11:36:06",
      "nomor_order": "0082/SPS/E-Katalog/24",
      "subtotal": "-550",
      "pajak": "550",
      "ongkir": "10000",
      "total": "0",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Atria Buyer",
      "alamat": "",
      "telp": "",
      "status": "PESANAN_BARU",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "148",
      "penerimaStr": "",
      "keuanganID": "",
      "keuanganStr": "",
      "estPengiriman": "0000-00-00",
      "estPengiriman2": "0000-00-00",
      "nomor_invoice": "0082/INV/E-Katalog/24",
      "nomor_suratjalan": "0082/SJL/E-Katalog/24",
      "nomor_kwitansi": "0082/KWT/E-Katalog/24",
      "read_status": "2",
      "tgl_ttd_kwitansi": "",
      "tgl_ttd_surat_pesanan": "",
      "tgl_ttd_surat_jalan": "",
      "tgl_ttd_invoice": "",
      "jum": "0"
    }
  ],
  "chart_penjualan": [
    0
  ],
  "table_paling_laris": [
    {
      "nama": "Barang Atria",
      "qty": "5",
      "harga": "25000"
    }
  ]
} 
*/

  String? produk;
  String? totalPermintaanPesanan;
  String? totalPendapatan;
  String? totalBelumLunas;
  String? pesananBaru;
  String? pesananDiterima;
  String? pesananDikirim;
  int? barangDiterima;
  int? prosesPembayaran;
  String? pesananDibayar;
  List<HomeSellerModelDataTablePesananTerbaru?>? tablePesananTerbaru;
  List<int?>? chartPenjualan;
  List<HomeSellerModelDataTablePalingLaris?>? tablePalingLaris;

  HomeSellerModelData({
    this.produk,
    this.totalPermintaanPesanan,
    this.totalPendapatan,
    this.totalBelumLunas,
    this.pesananBaru,
    this.pesananDiterima,
    this.pesananDikirim,
    this.barangDiterima,
    this.prosesPembayaran,
    this.pesananDibayar,
    this.tablePesananTerbaru,
    this.chartPenjualan,
    this.tablePalingLaris,
  });
  HomeSellerModelData.fromJson(Map<String, dynamic> json) {
    produk = json['produk']?.toString();
    totalPermintaanPesanan = json['total_permintaan_pesanan']?.toString();
    totalPendapatan = json['total_pendapatan']?.toString();
    totalBelumLunas = json['total_belum_lunas']?.toString();
    pesananBaru = json['pesanan_baru']?.toString();
    pesananDiterima = json['pesanan_diterima']?.toString();
    pesananDikirim = json['pesanan_dikirim']?.toString();
    barangDiterima = json['barang_diterima']?.toInt();
    prosesPembayaran = json['proses_pembayaran']?.toInt();
    pesananDibayar = json['pesanan_dibayar']?.toString();
    if (json['table_pesanan_terbaru'] != null) {
      final v = json['table_pesanan_terbaru'];
      final arr0 = <HomeSellerModelDataTablePesananTerbaru>[];
      v.forEach((v) {
        arr0.add(HomeSellerModelDataTablePesananTerbaru.fromJson(v));
      });
      tablePesananTerbaru = arr0;
    }
    if (json['chart_penjualan'] != null) {
      final v = json['chart_penjualan'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      chartPenjualan = arr0;
    }
    if (json['table_paling_laris'] != null) {
      final v = json['table_paling_laris'];
      final arr0 = <HomeSellerModelDataTablePalingLaris>[];
      v.forEach((v) {
        arr0.add(HomeSellerModelDataTablePalingLaris.fromJson(v));
      });
      tablePalingLaris = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['produk'] = produk;
    data['total_permintaan_pesanan'] = totalPermintaanPesanan;
    data['total_pendapatan'] = totalPendapatan;
    data['total_belum_lunas'] = totalBelumLunas;
    data['pesanan_baru'] = pesananBaru;
    data['pesanan_diterima'] = pesananDiterima;
    data['pesanan_dikirim'] = pesananDikirim;
    data['barang_diterima'] = barangDiterima;
    data['proses_pembayaran'] = prosesPembayaran;
    data['pesanan_dibayar'] = pesananDibayar;
    if (tablePesananTerbaru != null) {
      final v = tablePesananTerbaru;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['table_pesanan_terbaru'] = arr0;
    }
    if (chartPenjualan != null) {
      final v = chartPenjualan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['chart_penjualan'] = arr0;
    }
    if (tablePalingLaris != null) {
      final v = tablePalingLaris;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['table_paling_laris'] = arr0;
    }
    return data;
  }
}

class HomeSellerModel {
/*
{
  "result": "success",
  "data": {
    "produk": "3",
    "total_permintaan_pesanan": "5418950",
    "total_pendapatan": "26100",
    "total_belum_lunas": "5392850",
    "pesanan_baru": "8",
    "pesanan_diterima": "1",
    "pesanan_dikirim": "0",
    "barang_diterima": 0,
    "proses_pembayaran": 1,
    "pesanan_dibayar": "2",
    "table_pesanan_terbaru": [
      {
        "ID": "89",
        "Created": "2024-07-31 11:36:06",
        "Updated": "2024-07-31 11:36:06",
        "nomor_order": "0082/SPS/E-Katalog/24",
        "subtotal": "-550",
        "pajak": "550",
        "ongkir": "10000",
        "total": "0",
        "BuyerID": "148",
        "SellerID": "196",
        "nama": "Atria Buyer",
        "alamat": "",
        "telp": "",
        "status": "PESANAN_BARU",
        "PengajuanID": "49",
        "keterangan": "",
        "bukti": "",
        "penerimaID": "148",
        "penerimaStr": "",
        "keuanganID": "",
        "keuanganStr": "",
        "estPengiriman": "0000-00-00",
        "estPengiriman2": "0000-00-00",
        "nomor_invoice": "0082/INV/E-Katalog/24",
        "nomor_suratjalan": "0082/SJL/E-Katalog/24",
        "nomor_kwitansi": "0082/KWT/E-Katalog/24",
        "read_status": "2",
        "tgl_ttd_kwitansi": "",
        "tgl_ttd_surat_pesanan": "",
        "tgl_ttd_surat_jalan": "",
        "tgl_ttd_invoice": "",
        "jum": "0"
      }
    ],
    "chart_penjualan": [
      0
    ],
    "table_paling_laris": [
      {
        "nama": "Barang Atria",
        "qty": "5",
        "harga": "25000"
      }
    ]
  }
} 
*/

  String? result;
  HomeSellerModelData? data;

  HomeSellerModel({
    this.result,
    this.data,
  });
  HomeSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null)
        ? HomeSellerModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
