///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlamatAdminModelData {
/*
{
  "id": "3",
  "prov_id": "15",
  "kota_id": "240",
  "nama": "Jalan Probolinggo No 12",
  "prov": "Jawa Timur",
  "kota": "Kabupaten Probolinggo"
}
*/

  String? id;
  String? provId;
  String? kotaId;
  String? nama;
  String? prov;
  String? kota;

  AlamatAdminModelData({
    this.id,
    this.provId,
    this.kotaId,
    this.nama,
    this.prov,
    this.kota,
  });
  AlamatAdminModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    provId = json['prov_id']?.toString();
    kotaId = json['kota_id']?.toString();
    nama = json['nama']?.toString();
    prov = json['prov']?.toString();
    kota = json['kota']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['prov_id'] = provId;
    data['kota_id'] = kotaId;
    data['nama'] = nama;
    data['prov'] = prov;
    data['kota'] = kota;
    return data;
  }
}

class AlamatAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": "3",
      "prov_id": "15",
      "kota_id": "240",
      "nama": "Jalan Probolinggo No 12",
      "prov": "Jawa Timur",
      "kota": "Kabupaten Probolinggo"
    }
  ]
}
*/

  String? result;
  List<AlamatAdminModelData?>? data;

  AlamatAdminModel({
    this.result,
    this.data,
  });
  AlamatAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AlamatAdminModelData>[];
      v.forEach((v) {
        arr0.add(AlamatAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
