///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlamatAdminModelData {
/*
{
  "id": "3",
  "prov_id": "15",
  "kota_id": "240",
  "nama": "Jalan Probolinggo No 12",
  "prov": "Jawa Timur",
  "kota": "Kabupaten Probolinggo"
}
*/

  String? id;
  String? provId;
  String? kotaId;
  String? nama;
  String? prov;
  String? kota;
  String? phone;
  String? status;
  String? recipientName;

  AlamatAdminModelData({
    this.id,
    this.provId,
    this.kotaId,
    this.nama,
    this.prov,
    this.kota,
    this.phone,
    this.status,
    this.recipientName,
  });
  AlamatAdminModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    if (json['location'] != null) {
      provId = json['location']['province_id']?.toString();
      kotaId = json['location']['city_id']?.toString();
      prov = json['location']['province_name']?.toString();
      kota = json['location']['city_name']?.toString();
    } else {
      provId = json['prov_id']?.toString();
      kotaId = json['kota_id']?.toString();
      prov = json['prov']?.toString();
      kota = json['kota']?.toString();
    }
    nama = json['detail']?.toString() ?? json['nama']?.toString();
    phone = json['phone']?.toString();
    status = json['status']?.toString();
    recipientName = json['recipient_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['prov_id'] = provId;
    data['kota_id'] = kotaId;
    data['nama'] = nama;
    data['prov'] = prov;
    data['kota'] = kota;
    data['phone'] = phone;
    data['status'] = status;
    data['recipient_name'] = recipientName;
    return data;
  }
}

class AlamatAdminModel {
  String? result;
  List<AlamatAdminModelData?>? data;
  dynamic meta;
  dynamic links;

  AlamatAdminModel({
    this.result,
    this.data,
    this.meta,
    this.links,
  });

  AlamatAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AlamatAdminModelData>[];
      v.forEach((v) {
        arr0.add(AlamatAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = json['meta'];
    links = json['links'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['meta'] = meta;
    data['links'] = links;
    return data;
  }
}
