///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KategoriAdminModelData {
/*
{
  "ID": "1",
  "nama": "Consumable"
} 
*/

  String? ID;
  String? nama;

  KategoriAdminModelData({
    this.ID,
    this.nama,
  });
  KategoriAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    return data;
  }
}

class KategoriAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1",
      "nama": "Consumable"
    }
  ]
} 
*/

  String? result;
  List<KategoriAdminModelData?>? data;

  KategoriAdminModel({
    this.result,
    this.data,
  });
  KategoriAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <KategoriAdminModelData>[];
      v.forEach((v) {
        arr0.add(KategoriAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
