///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KotaAdminModelData {
/*
{
  "ID": "257",
  "prov_id": "15",
  "nama": "Kota Kediri"
}
*/

  String? ID;
  String? provId;
  String? nama;

  KotaAdminModelData({
    this.ID,
    this.provId,
    this.nama,
  });
  KotaAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    provId = json['prov_id']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['prov_id'] = provId;
    data['nama'] = nama;
    return data;
  }
}

class KotaAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "257",
      "prov_id": "15",
      "nama": "Kota Kediri"
    }
  ]
}
*/

  String? result;
  List<KotaAdminModelData?>? data;

  KotaAdminModel({
    this.result,
    this.data,
  });
  KotaAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <KotaAdminModelData>[];
      v.forEach((v) {
        arr0.add(KotaAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
