///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PajakAdminModelData {
/*
{
  "id": "2",
  "nama": "Pajak Pengiriman",
  "persentase": "1.1"
}
*/

  String? id;
  String? nama;
  String? persentase;

  PajakAdminModelData({
    this.id,
    this.nama,
    this.persentase,
  });
  PajakAdminModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    nama = json['nama']?.toString();
    persentase = json['persentase']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama'] = nama;
    data['persentase'] = persentase;
    return data;
  }
}

class PajakAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": "2",
      "nama": "Pajak Pengiriman",
      "persentase": "1.1"
    }
  ]
}
*/

  String? result;
  List<PajakAdminModelData?>? data;

  PajakAdminModel({
    this.result,
    this.data,
  });
  PajakAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PajakAdminModelData>[];
      v.forEach((v) {
        arr0.add(PajakAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
