///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProvinsiAdminModelData {
/*
{
  "ID": "1",
  "nama": "Aceh"
}
*/

  String? ID;
  String? nama;

  ProvinsiAdminModelData({
    this.ID,
    this.nama,
  });
  ProvinsiAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['id']?.toString();
    nama = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = ID;
    data['name'] = nama;
    return data;
  }
}

class ProvinsiAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1",
      "nama": "Aceh"
    }
  ]
}
*/

  String? result;
  List<ProvinsiAdminModelData?>? data;

  ProvinsiAdminModel({
    this.result,
    this.data,
  });
  ProvinsiAdminModel.fromJson(Map<String, dynamic> json) {
    result = "success"; // Hardcoded for backward compatibility in Flutter side
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProvinsiAdminModelData>[];
      v.forEach((v) {
        arr0.add(ProvinsiAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
