///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
class DetailPesananSellerModelDataTimeline {
  /*
{
  "label": "Pesanan Baru",
  "time": "2025-02-21",
  "desc": "a"
} 
*/

  String? label;
  String? time;
  String? desc;

  DetailPesananSellerModelDataTimeline({this.label, this.time, this.desc});
  DetailPesananSellerModelDataTimeline.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    time = json['time']?.toString();
    desc = json['desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['time'] = time;
    data['desc'] = desc;
    return data;
  }
}

class DetailPesananSellerModelDataDetail {
  /*
{
  "ID": "1185",
  "nama": "Skincare Pria",
  "harga": "467000",
  "kode_produk": "002",
  "size": "",
  "qty": "1",
  "deskripsi": "Membuat kulit cerah",
  "SellerID": "196",
  "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
  "IDKategori": "1",
  "harga_akhir": "410000",
  "dikomplain": "YES",
  "komplain": "kirim lagi aja",
  "IDOrder": "751"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? foto;
  String? IDKategori;
  String? hargaAkhir;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DetailPesananSellerModelDataDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.foto,
    this.IDKategori,
    this.hargaAkhir,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DetailPesananSellerModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['harga_akhir'] = hargaAkhir;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DetailPesananSellerModelDataParentOrderModel {
  /*
{
  "ID": "110",
  "Created": "2024-08-21 10:22:18",
  "Updated": "2024-08-21 10:22:18",
  "nomor_order": "0103/SPS/E-Katalog/24",
  "subtotal": "567000",
  "pajak": "55550",
  "ongkir": "20000",
  "total": "642550",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Operasi MKP KP",
  "alamat": "Jalan Probolinggo No 12",
  "telp": "",
  "status": "TELAH_DIBAYAR",
  "PengajuanID": "49",
  "keterangan": "",
  "penerimaID": "124",
  "penerimaStr": "",
  "keuanganID": "",
  "keuanganStr": "",
  "estPengiriman": "2024-08-21",
  "estPengiriman2": "2024-08-21",
  "nomor_invoice": "0103/INV/E-Katalog/24",
  "nomor_suratjalan": "0103/SJL/E-Katalog/24",
  "nomor_kwitansi": "0103/KWT/E-Katalog/24",
  "read_status": "1",
  "tgl_ttd_kwitansi": "2024-08-21 11:47:07",
  "tgl_ttd_surat_pesanan": "",
  "tgl_ttd_surat_jalan": "",
  "tgl_ttd_invoice": "",
  "Rekening": "",
  "an_rek": "",
  "bank": "",
  "SellerNama": "Atria Seller",
  "jum": "2",
  "ttd_pesanan_buyer": "https://mspeed.erdata.id/ttdsuratpesanan/signature_buyer_0103_SPS_E-Katalog_24.png",
  "ttd_pesanan_seller": "https://mspeed.erdata.id/ttdsuratpesanan/signature_seller_0103_SPS_E-Katalog_24.png",
  "ttd_suratjalan_seller": "https://mspeed.erdata.id/ttdsuratjalan/signature_seller_0103_SPS_E-Katalog_24.png",
  "ttd_suratjalan_penerima": "https://mspeed.erdata.id/ttdsuratjalan/signature_buyer_0103_SPS_E-Katalog_24.png",
  "lampiran": 2
} 
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? Rekening;
  String? anRek;
  String? bank;
  String? SellerNama;
  String? jum;
  String? ttdPesananBuyer;
  String? ttdPesananSeller;
  String? ttdSuratjalanSeller;
  String? ttdSuratjalanPenerima;
  int? lampiran;

  DetailPesananSellerModelDataParentOrderModel({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.Rekening,
    this.anRek,
    this.bank,
    this.SellerNama,
    this.jum,
    this.ttdPesananBuyer,
    this.ttdPesananSeller,
    this.ttdSuratjalanSeller,
    this.ttdSuratjalanPenerima,
    this.lampiran,
  });
  DetailPesananSellerModelDataParentOrderModel.fromJson(
    Map<String, dynamic> json,
  ) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    Rekening = json['Rekening']?.toString();
    anRek = json['an_rek']?.toString();
    bank = json['bank']?.toString();
    SellerNama = json['SellerNama']?.toString();
    jum = json['jum']?.toString();
    ttdPesananBuyer = json['ttd_pesanan_buyer']?.toString();
    ttdPesananSeller = json['ttd_pesanan_seller']?.toString();
    ttdSuratjalanSeller = json['ttd_suratjalan_seller']?.toString();
    ttdSuratjalanPenerima = json['ttd_suratjalan_penerima']?.toString();
    lampiran = json['lampiran']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['Rekening'] = Rekening;
    data['an_rek'] = anRek;
    data['bank'] = bank;
    data['SellerNama'] = SellerNama;
    data['jum'] = jum;
    data['ttd_pesanan_buyer'] = ttdPesananBuyer;
    data['ttd_pesanan_seller'] = ttdPesananSeller;
    data['ttd_suratjalan_seller'] = ttdSuratjalanSeller;
    data['ttd_suratjalan_penerima'] = ttdSuratjalanPenerima;
    data['lampiran'] = lampiran;
    return data;
  }
}

class DetailPesananSellerModelData {
  /*
{
  "ParentOrderModel": {
    "ID": "110",
    "Created": "2024-08-21 10:22:18",
    "Updated": "2024-08-21 10:22:18",
    "nomor_order": "0103/SPS/E-Katalog/24",
    "subtotal": "567000",
    "pajak": "55550",
    "ongkir": "20000",
    "total": "642550",
    "BuyerID": "148",
    "SellerID": "196",
    "nama": "Operasi MKP KP",
    "alamat": "Jalan Probolinggo No 12",
    "telp": "",
    "status": "TELAH_DIBAYAR",
    "PengajuanID": "49",
    "keterangan": "",
    "penerimaID": "124",
    "penerimaStr": "",
    "keuanganID": "",
    "keuanganStr": "",
    "estPengiriman": "2024-08-21",
    "estPengiriman2": "2024-08-21",
    "nomor_invoice": "0103/INV/E-Katalog/24",
    "nomor_suratjalan": "0103/SJL/E-Katalog/24",
    "nomor_kwitansi": "0103/KWT/E-Katalog/24",
    "read_status": "1",
    "tgl_ttd_kwitansi": "2024-08-21 11:47:07",
    "tgl_ttd_surat_pesanan": "",
    "tgl_ttd_surat_jalan": "",
    "tgl_ttd_invoice": "",
    "Rekening": "",
    "an_rek": "",
    "bank": "",
    "SellerNama": "Atria Seller",
    "jum": "2",
    "ttd_pesanan_buyer": "https://mspeed.erdata.id/ttdsuratpesanan/signature_buyer_0103_SPS_E-Katalog_24.png",
    "ttd_pesanan_seller": "https://mspeed.erdata.id/ttdsuratpesanan/signature_seller_0103_SPS_E-Katalog_24.png",
    "ttd_suratjalan_seller": "https://mspeed.erdata.id/ttdsuratjalan/signature_seller_0103_SPS_E-Katalog_24.png",
    "ttd_suratjalan_penerima": "https://mspeed.erdata.id/ttdsuratjalan/signature_buyer_0103_SPS_E-Katalog_24.png",
    "lampiran": 2
  },
  "detail": [
    {
      "ID": "1185",
      "nama": "Skincare Pria",
      "harga": "467000",
      "kode_produk": "002",
      "size": "",
      "qty": "1",
      "deskripsi": "Membuat kulit cerah",
      "SellerID": "196",
      "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
      "IDKategori": "1",
      "harga_akhir": "410000",
      "dikomplain": "YES",
      "komplain": "kirim lagi aja",
      "IDOrder": "751"
    }
  ]
} 
*/

  DetailPesananSellerModelDataParentOrderModel? ParentOrderModel;
  List<DetailPesananSellerModelDataDetail?>? detail;
  List<DetailPesananSellerModelDataTimeline?>? timeline;

  DetailPesananSellerModelData({
    this.ParentOrderModel,
    this.detail,
    this.timeline,
  });
  DetailPesananSellerModelData.fromJson(Map<String, dynamic> json) {
    ParentOrderModel =
        (json['ParentOrderModel'] != null)
            ? DetailPesananSellerModelDataParentOrderModel.fromJson(
              json['ParentOrderModel'],
            )
            : null;
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <DetailPesananSellerModelDataDetail>[];
      v.forEach((v) {
        arr0.add(DetailPesananSellerModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
    if (json['timeline'] != null) {
      final v = json['timeline'];
      final arr0 = <DetailPesananSellerModelDataTimeline>[];
      v.forEach((v) {
        arr0.add(DetailPesananSellerModelDataTimeline.fromJson(v));
      });
      timeline = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ParentOrderModel != null) {
      data['ParentOrderModel'] = ParentOrderModel!.toJson();
    }
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    if (timeline != null) {
      final v = timeline;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['timeline'] = arr0;
    }
    return data;
  }
}

class DetailPesananSellerModel {
  /*
{
  "result": "success",
  "data": {
    "ParentOrderModel": {
      "ID": "110",
      "Created": "2024-08-21 10:22:18",
      "Updated": "2024-08-21 10:22:18",
      "nomor_order": "0103/SPS/E-Katalog/24",
      "subtotal": "567000",
      "pajak": "55550",
      "ongkir": "20000",
      "total": "642550",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Operasi MKP KP",
      "alamat": "Jalan Probolinggo No 12",
      "telp": "",
      "status": "TELAH_DIBAYAR",
      "PengajuanID": "49",
      "keterangan": "",
      "penerimaID": "124",
      "penerimaStr": "",
      "keuanganID": "",
      "keuanganStr": "",
      "estPengiriman": "2024-08-21",
      "estPengiriman2": "2024-08-21",
      "nomor_invoice": "0103/INV/E-Katalog/24",
      "nomor_suratjalan": "0103/SJL/E-Katalog/24",
      "nomor_kwitansi": "0103/KWT/E-Katalog/24",
      "read_status": "1",
      "tgl_ttd_kwitansi": "2024-08-21 11:47:07",
      "tgl_ttd_surat_pesanan": "",
      "tgl_ttd_surat_jalan": "",
      "tgl_ttd_invoice": "",
      "Rekening": "",
      "an_rek": "",
      "bank": "",
      "SellerNama": "Atria Seller",
      "jum": "2",
      "ttd_pesanan_buyer": "https://mspeed.erdata.id/ttdsuratpesanan/signature_buyer_0103_SPS_E-Katalog_24.png",
      "ttd_pesanan_seller": "https://mspeed.erdata.id/ttdsuratpesanan/signature_seller_0103_SPS_E-Katalog_24.png",
      "ttd_suratjalan_seller": "https://mspeed.erdata.id/ttdsuratjalan/signature_seller_0103_SPS_E-Katalog_24.png",
      "ttd_suratjalan_penerima": "https://mspeed.erdata.id/ttdsuratjalan/signature_buyer_0103_SPS_E-Katalog_24.png",
      "lampiran": 2
    },
    "detail": [
      {
        "ID": "1185",
        "nama": "Skincare Pria",
        "harga": "467000",
        "kode_produk": "002",
        "size": "",
        "qty": "1",
        "deskripsi": "Membuat kulit cerah",
        "SellerID": "196",
        "foto": "https://mspeed.erdata.id/produk/KAHF-FOTO-3-1344x800.png",
        "IDKategori": "1",
        "harga_akhir": "410000",
        "dikomplain": "YES",
        "komplain": "kirim lagi aja",
        "IDOrder": "751"
      }
    ]
  }
} 
*/

  String? result;
  DetailPesananSellerModelData? data;

  DetailPesananSellerModel({this.result, this.data});
  DetailPesananSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data =
        (json['data'] != null)
            ? DetailPesananSellerModelData.fromJson(json['data'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
    return data;
  }
}
