///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PesananSellerModelData {
/*
{
  "ID": "92",
  "Created": "2024-08-12 11:05:38",
  "Updated": "2024-08-12 11:05:38",
  "nomor_order": "0085/SPS/E-Katalog/24",
  "subtotal": "3374500",
  "pajak": "27500",
  "ongkir": "0",
  "total": "3402000",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Atria Buyer",
  "alamat": "Jalan Surabay No 1",
  "telp": "",
  "status": "PESANAN_BARU",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "148",
  "penerimaStr": null,
  "keuanganID": null,
  "keuanganStr": null,
  "estPengiriman": "0000-00-00",
  "estPengiriman2": "0000-00-00",
  "nomor_invoice": "0085/INV/E-Katalog/24",
  "nomor_suratjalan": "0085/SJL/E-Katalog/24",
  "nomor_kwitansi": "0085/KWT/E-Katalog/24",
  "read_status": "2",
  "tgl_ttd_kwitansi": null,
  "tgl_ttd_surat_pesanan": null,
  "tgl_ttd_surat_jalan": null,
  "tgl_ttd_invoice": null,
  "jum": "2",
  "jumkomplain": "0"
}
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? jum;
  String? jumkomplain;

  PesananSellerModelData({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.jum,
    this.jumkomplain,
  });
  PesananSellerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    jum = json['jum']?.toString();
    jumkomplain = json['jumkomplain']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['jum'] = jum;
    data['jumkomplain'] = jumkomplain;
    return data;
  }
}

class PesananSellerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "92",
      "Created": "2024-08-12 11:05:38",
      "Updated": "2024-08-12 11:05:38",
      "nomor_order": "0085/SPS/E-Katalog/24",
      "subtotal": "3374500",
      "pajak": "27500",
      "ongkir": "0",
      "total": "3402000",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Atria Buyer",
      "alamat": "Jalan Surabay No 1",
      "telp": "",
      "status": "PESANAN_BARU",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "148",
      "penerimaStr": null,
      "keuanganID": null,
      "keuanganStr": null,
      "estPengiriman": "0000-00-00",
      "estPengiriman2": "0000-00-00",
      "nomor_invoice": "0085/INV/E-Katalog/24",
      "nomor_suratjalan": "0085/SJL/E-Katalog/24",
      "nomor_kwitansi": "0085/KWT/E-Katalog/24",
      "read_status": "2",
      "tgl_ttd_kwitansi": null,
      "tgl_ttd_surat_pesanan": null,
      "tgl_ttd_surat_jalan": null,
      "tgl_ttd_invoice": null,
      "jum": "2",
      "jumkomplain": "0"
    }
  ]
}
*/

  String? result;
  List<PesananSellerModelData?>? data;

  PesananSellerModel({
    this.result,
    this.data,
  });
  PesananSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PesananSellerModelData>[];
      v.forEach((v) {
        arr0.add(PesananSellerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
