///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SellerHomeModelData {
/*
{
  "ID": "1183",
  "nama": "Barang Atria",
  "harga": "5000",
  "kode_produk": "ATR",
  "size": "",
  "qty": "86",
  "deskripsi": "Desc Barang Atria",
  "SellerID": "196",
  "SellerNama": "Atria Seller",
  "foto": "",
  "IDKategori": "1",
  "NamaKategori": "Consumable"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? SellerNama;
  String? foto;
  String? IDKategori;
  String? NamaKategori;

  SellerHomeModelData({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.SellerNama,
    this.foto,
    this.IDKategori,
    this.NamaKategori,
  });
  SellerHomeModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    SellerNama = json['SellerNama']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    NamaKategori = json['NamaKategori']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['SellerNama'] = SellerNama;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['NamaKategori'] = NamaKategori;
    return data;
  }
}

class SellerHomeModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1183",
      "nama": "Barang Atria",
      "harga": "5000",
      "kode_produk": "ATR",
      "size": "",
      "qty": "86",
      "deskripsi": "Desc Barang Atria",
      "SellerID": "196",
      "SellerNama": "Atria Seller",
      "foto": "",
      "IDKategori": "1",
      "NamaKategori": "Consumable"
    }
  ]
} 
*/

  String? result;
  List<SellerHomeModelData?>? data;

  SellerHomeModel({
    this.result,
    this.data,
  });
  SellerHomeModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <SellerHomeModelData>[];
      v.forEach((v) {
        arr0.add(SellerHomeModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
