///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KotaModelData {
/*
{
  "ID": "47",
  "kota": ""
} 
*/

  String? ID;
  String? kota;

  KotaModelData({
    this.ID,
    this.kota,
  });
  KotaModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    kota = json['kota']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['kota'] = kota;
    return data;
  }
}

class KotaModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "47",
      "kota": ""
    }
  ]
} 
*/

  String? result;
  List<KotaModelData?>? data;

  KotaModel({
    this.result,
    this.data,
  });
  KotaModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <KotaModelData>[];
  v.forEach((v) {
  arr0.add(KotaModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
