///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileSellerModelDataKotaSelected {
/*
{
  "ID": "264",
  "prov_id": "15",
  "nama": "Kota Surabaya"
} 
*/

  String? ID;
  String? provId;
  String? nama;

  ProfileSellerModelDataKotaSelected({
    this.ID,
    this.provId,
    this.nama,
  });
  ProfileSellerModelDataKotaSelected.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    provId = json['prov_id']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['prov_id'] = provId;
    data['nama'] = nama;
    return data;
  }
}

class ProfileSellerModelDataProvSelected {
/*
{
  "ID": "15",
  "nama": "Jawa Timur"
} 
*/

  String? ID;
  String? nama;

  ProfileSellerModelDataProvSelected({
    this.ID,
    this.nama,
  });
  ProfileSellerModelDataProvSelected.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    return data;
  }
}

class ProfileSellerModelDataGetSeller {
/*
{
  "ID": "435",
  "nama": "CV irfan jaya",
  "alamat": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
  "lokasi": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
  "lattitude": "-7.376541736680468",
  "longitude": "112.71929912219838",
  "email": "cvirfanjaya@yahoo.com",
  "telp": "081221555919",
  "kbli": "52362",
  "nama_pemilik": "sugianto darmadi ",
  "nama_cp": "antok",
  "telp_cp": "088801550095",
  "foto": "logo-2025-103125am-IMG-20250224-WA0007.jpg",
  "no_npwp": "",
  "npwp": "",
  "no_ktp": "3578290709750001",
  "ktp": "ktp-2025-103125am-IMG-20250224-WA0004.jpg",
  "sp_pkp": "",
  "prov": "Jawa Timur",
  "kota": "Kota Surabaya",
  "no_rek": "4720175318",
  "an_rek": "uji prasetyo zm",
  "bank": "bca",
  "buku_rekening": "bukurekening-2025-103125am-IMG-20250224-WA0013.jpg",
  "jabatan": "direktur",
  "kelengkapan_npwp": "2",
  "tgl_ttd_nonpkp": "2025-02-24",
  "file_ttd_nonpkp": "ttdnonpkp/signature_seller_435.png",
  "no_nib": "0220208261178",
  "nib": "nib-2025-103125am-NIBIRFANJAYA17102023.pdf"
} 
*/

  String? ID;
  String? nama;
  String? alamat;
  String? lokasi;
  String? lattitude;
  String? longitude;
  String? email;
  String? telp;
  String? kbli;
  String? namaPemilik;
  String? namaCp;
  String? telpCp;
  String? foto;
  String? noNpwp;
  String? npwp;
  String? noKtp;
  String? ktp;
  String? spPkp;
  String? prov;
  String? kota;
  String? noRek;
  String? anRek;
  String? bank;
  String? bukuRekening;
  String? jabatan;
  String? kelengkapanNpwp;
  String? tglTtdNonpkp;
  String? fileTtdNonpkp;
  String? noNib;
  String? nib;

  ProfileSellerModelDataGetSeller({
    this.ID,
    this.nama,
    this.alamat,
    this.lokasi,
    this.lattitude,
    this.longitude,
    this.email,
    this.telp,
    this.kbli,
    this.namaPemilik,
    this.namaCp,
    this.telpCp,
    this.foto,
    this.noNpwp,
    this.npwp,
    this.noKtp,
    this.ktp,
    this.spPkp,
    this.prov,
    this.kota,
    this.noRek,
    this.anRek,
    this.bank,
    this.bukuRekening,
    this.jabatan,
    this.kelengkapanNpwp,
    this.tglTtdNonpkp,
    this.fileTtdNonpkp,
    this.noNib,
    this.nib,
  });
  ProfileSellerModelDataGetSeller.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    nama = json['nama']?.toString() ?? json['name']?.toString() ?? json['company_name']?.toString();
    alamat = json['alamat']?.toString() ?? json['address']?.toString();
    lokasi = json['lokasi']?.toString();
    lattitude = json['lattitude']?.toString() ?? json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    email = json['email']?.toString();
    telp = json['telp']?.toString() ?? json['phone']?.toString();
    kbli = json['kbli']?.toString();
    namaPemilik = json['nama_pemilik']?.toString() ?? json['owner_name']?.toString();
    namaCp = json['nama_cp']?.toString() ?? json['cp_name']?.toString();
    telpCp = json['telp_cp']?.toString() ?? json['cp_phone']?.toString();
    foto = json['foto']?.toString() ?? json['photo']?.toString();
    noNpwp = json['no_npwp']?.toString() ?? json['npwp_number']?.toString();
    npwp = json['npwp']?.toString();
    noKtp = json['no_ktp']?.toString() ?? json['ktp_number']?.toString();
    ktp = json['ktp']?.toString();
    spPkp = json['sp_pkp']?.toString() ?? json['sp_pkp_file']?.toString();
    prov = json['prov']?.toString() ?? json['province']?.toString();
    kota = json['kota']?.toString() ?? json['city']?.toString();
    noRek = json['no_rek']?.toString() ?? json['bank_account_number']?.toString();
    anRek = json['an_rek']?.toString() ?? json['bank_account_name']?.toString();
    bank = json['bank']?.toString() ?? json['bank_name']?.toString();
    bukuRekening = json['buku_rekening']?.toString() ?? json['bank_book_file']?.toString();
    jabatan = json['jabatan']?.toString() ?? json['role_position']?.toString();
    kelengkapanNpwp = json['kelengkapan_npwp']?.toString();
    tglTtdNonpkp = json['tgl_ttd_nonpkp']?.toString();
    fileTtdNonpkp = json['file_ttd_nonpkp']?.toString();
    noNib = json['no_nib']?.toString() ?? json['nib_number']?.toString();
    nib = json['nib']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['lokasi'] = lokasi;
    data['lattitude'] = lattitude;
    data['longitude'] = longitude;
    data['email'] = email;
    data['telp'] = telp;
    data['kbli'] = kbli;
    data['nama_pemilik'] = namaPemilik;
    data['nama_cp'] = namaCp;
    data['telp_cp'] = telpCp;
    data['foto'] = foto;
    data['no_npwp'] = noNpwp;
    data['npwp'] = npwp;
    data['no_ktp'] = noKtp;
    data['ktp'] = ktp;
    data['sp_pkp'] = spPkp;
    data['prov'] = prov;
    data['kota'] = kota;
    data['no_rek'] = noRek;
    data['an_rek'] = anRek;
    data['bank'] = bank;
    data['buku_rekening'] = bukuRekening;
    data['jabatan'] = jabatan;
    data['kelengkapan_npwp'] = kelengkapanNpwp;
    data['tgl_ttd_nonpkp'] = tglTtdNonpkp;
    data['file_ttd_nonpkp'] = fileTtdNonpkp;
    data['no_nib'] = noNib;
    data['nib'] = nib;
    return data;
  }
}

class ProfileSellerModelData {
/*
{
  "title": "Edit Profil",
  "uri2": "profil",
  "getSeller": {
    "ID": "435",
    "nama": "CV irfan jaya",
    "alamat": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
    "lokasi": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
    "lattitude": "-7.376541736680468",
    "longitude": "112.71929912219838",
    "email": "cvirfanjaya@yahoo.com",
    "telp": "081221555919",
    "kbli": "52362",
    "nama_pemilik": "sugianto darmadi ",
    "nama_cp": "antok",
    "telp_cp": "088801550095",
    "foto": "logo-2025-103125am-IMG-20250224-WA0007.jpg",
    "no_npwp": "",
    "npwp": "",
    "no_ktp": "3578290709750001",
    "ktp": "ktp-2025-103125am-IMG-20250224-WA0004.jpg",
    "sp_pkp": "",
    "prov": "Jawa Timur",
    "kota": "Kota Surabaya",
    "no_rek": "4720175318",
    "an_rek": "uji prasetyo zm",
    "bank": "bca",
    "buku_rekening": "bukurekening-2025-103125am-IMG-20250224-WA0013.jpg",
    "jabatan": "direktur",
    "kelengkapan_npwp": "2",
    "tgl_ttd_nonpkp": "2025-02-24",
    "file_ttd_nonpkp": "ttdnonpkp/signature_seller_435.png",
    "no_nib": "0220208261178",
    "nib": "nib-2025-103125am-NIBIRFANJAYA17102023.pdf"
  },
  "provSelected": {
    "ID": "15",
    "nama": "Jawa Timur"
  },
  "kotaSelected": {
    "ID": "264",
    "prov_id": "15",
    "nama": "Kota Surabaya"
  },
  "fotoUrl": "https://mspeed.mitrakaryaprima.com/seller/435/logo-2025-103125am-IMG-20250224-WA0007.jpg",
  "ktpUrl": "https://mspeed.mitrakaryaprima.com/ktp/435/ktp-2025-103125am-IMG-20250224-WA0004.jpg",
  "npwpUrl": "",
  "nibUrl": "https://mspeed.mitrakaryaprima.com/nib/435/nib-2025-103125am-NIBIRFANJAYA17102023.pdf",
  "bukuRekeningUrl": "https://mspeed.mitrakaryaprima.com/buku_rekening/435/bukurekening-2025-103125am-IMG-20250224-WA0013.jpg",
  "spPkpUrl": ""
} 
*/

  String? title;
  String? uri2;
  ProfileSellerModelDataGetSeller? getSeller;
  ProfileSellerModelDataProvSelected? provSelected;
  ProfileSellerModelDataKotaSelected? kotaSelected;
  String? fotoUrl;
  String? ktpUrl;
  String? npwpUrl;
  String? nibUrl;
  String? bukuRekeningUrl;
  String? spPkpUrl;

  ProfileSellerModelData({
    this.title,
    this.uri2,
    this.getSeller,
    this.provSelected,
    this.kotaSelected,
    this.fotoUrl,
    this.ktpUrl,
    this.npwpUrl,
    this.nibUrl,
    this.bukuRekeningUrl,
    this.spPkpUrl,
  });
  ProfileSellerModelData.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    uri2 = json['uri2']?.toString();
    getSeller = (json['getSeller'] != null) ? ProfileSellerModelDataGetSeller.fromJson(json['getSeller']) : null;
    provSelected = (json['provSelected'] != null) ? ProfileSellerModelDataProvSelected.fromJson(json['provSelected']) : null;
    kotaSelected = (json['kotaSelected'] != null) ? ProfileSellerModelDataKotaSelected.fromJson(json['kotaSelected']) : null;
    fotoUrl = json['fotoUrl']?.toString();
    ktpUrl = json['ktpUrl']?.toString();
    npwpUrl = json['npwpUrl']?.toString();
    nibUrl = json['nibUrl']?.toString();
    bukuRekeningUrl = json['bukuRekeningUrl']?.toString();
    spPkpUrl = json['spPkpUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['uri2'] = uri2;
    if (getSeller != null) {
      data['getSeller'] = getSeller!.toJson();
    }
    if (provSelected != null) {
      data['provSelected'] = provSelected!.toJson();
    }
    if (kotaSelected != null) {
      data['kotaSelected'] = kotaSelected!.toJson();
    }
    data['fotoUrl'] = fotoUrl;
    data['ktpUrl'] = ktpUrl;
    data['npwpUrl'] = npwpUrl;
    data['nibUrl'] = nibUrl;
    data['bukuRekeningUrl'] = bukuRekeningUrl;
    data['spPkpUrl'] = spPkpUrl;
    return data;
  }
}

class ProfileSellerModel {
/*
{
  "result": "success",
  "data": {
    "title": "Edit Profil",
    "uri2": "profil",
    "getSeller": {
      "ID": "435",
      "nama": "CV irfan jaya",
      "alamat": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
      "lokasi": "jl kemlaten 11 nomor 7 kota surabaya provinsi jawa timur ",
      "lattitude": "-7.376541736680468",
      "longitude": "112.71929912219838",
      "email": "cvirfanjaya@yahoo.com",
      "telp": "081221555919",
      "kbli": "52362",
      "nama_pemilik": "sugianto darmadi ",
      "nama_cp": "antok",
      "telp_cp": "088801550095",
      "foto": "logo-2025-103125am-IMG-20250224-WA0007.jpg",
      "no_npwp": "",
      "npwp": "",
      "no_ktp": "3578290709750001",
      "ktp": "ktp-2025-103125am-IMG-20250224-WA0004.jpg",
      "sp_pkp": "",
      "prov": "Jawa Timur",
      "kota": "Kota Surabaya",
      "no_rek": "4720175318",
      "an_rek": "uji prasetyo zm",
      "bank": "bca",
      "buku_rekening": "bukurekening-2025-103125am-IMG-20250224-WA0013.jpg",
      "jabatan": "direktur",
      "kelengkapan_npwp": "2",
      "tgl_ttd_nonpkp": "2025-02-24",
      "file_ttd_nonpkp": "ttdnonpkp/signature_seller_435.png",
      "no_nib": "0220208261178",
      "nib": "nib-2025-103125am-NIBIRFANJAYA17102023.pdf"
    },
    "provSelected": {
      "ID": "15",
      "nama": "Jawa Timur"
    },
    "kotaSelected": {
      "ID": "264",
      "prov_id": "15",
      "nama": "Kota Surabaya"
    },
    "fotoUrl": "https://mspeed.mitrakaryaprima.com/seller/435/logo-2025-103125am-IMG-20250224-WA0007.jpg",
    "ktpUrl": "https://mspeed.mitrakaryaprima.com/ktp/435/ktp-2025-103125am-IMG-20250224-WA0004.jpg",
    "npwpUrl": "",
    "nibUrl": "https://mspeed.mitrakaryaprima.com/nib/435/nib-2025-103125am-NIBIRFANJAYA17102023.pdf",
    "bukuRekeningUrl": "https://mspeed.mitrakaryaprima.com/buku_rekening/435/bukurekening-2025-103125am-IMG-20250224-WA0013.jpg",
    "spPkpUrl": ""
  }
} 
*/

  String? result;
  ProfileSellerModelData? data;

  ProfileSellerModel({
    this.result,
    this.data,
  });
  ProfileSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? ProfileSellerModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
