///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProvinsiModelData {
/*
{
  "ID": "1",
  "nama": "Aceh"
} 
*/

  String? ID;
  String? nama;

  ProvinsiModelData({
    this.ID,
    this.nama,
  });
  ProvinsiModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    return data;
  }
}

class ProvinsiModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1",
      "nama": "Aceh"
    }
  ]
} 
*/

  String? result;
  List<ProvinsiModelData?>? data;

  ProvinsiModel({
    this.result,
    this.data,
  });
  ProvinsiModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ProvinsiModelData>[];
  v.forEach((v) {
  arr0.add(ProvinsiModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
