///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressShippingListModelData {
/*
{
  "id": 16,
  "title": "Office ABCS",
  "name": "test1",
  "address": "test",
  "phone": "test1",
  "is_default": 1
}
*/

  int? id;
  String? title;
  String? name;
  String? address;
  String? phone;
  int? isDefault;

  AddressShippingListModelData({
    this.id,
    this.title,
    this.name,
    this.address,
    this.phone,
    this.isDefault,
  });
  AddressShippingListModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    name = json['name']?.toString();
    address = json['address']?.toString();
    phone = json['phone']?.toString();
    isDefault = json['is_default']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['name'] = name;
    data['address'] = address;
    data['phone'] = phone;
    data['is_default'] = isDefault;
    return data;
  }
}

class AddressShippingListModel {
/*
{
  "success": true,
  "message": "",
  "data": [
    {
      "id": 16,
      "title": "Office ABCS",
      "name": "test1",
      "address": "test",
      "phone": "test1",
      "is_default": 1
    }
  ]
}
*/

  bool? success;
  String? message;
  List<AddressShippingListModelData?>? data;

  AddressShippingListModel({
    this.success,
    this.message,
    this.data,
  });
  AddressShippingListModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AddressShippingListModelData>[];
      v.forEach((v) {
        arr0.add(AddressShippingListModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
