///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressShippingDetailModelData {
/*
{
  "id": 13,
  "name": "test",
  "email": null,
  "phone": "test",
  "country": "test",
  "state": "test",
  "city": "test",
  "address": "test",
  "customer_id": 1,
  "is_default": 0,
  "created_at": "2024-03-19T04:26:14.000000Z",
  "updated_at": "2024-03-19T04:26:14.000000Z",
  "zip_code": "test",
  "title": "kantor",
  "latitude": "112.246454000",
  "longitude": "-7.213145000"
} 
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? country;
  String? state;
  String? city;
  String? address;
  int? customerId;
  int? isDefault;
  String? createdAt;
  String? updatedAt;
  String? zipCode;
  String? title;
  String? latitude;
  String? longitude;

  AddressShippingDetailModelData({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.country,
    this.state,
    this.city,
    this.address,
    this.customerId,
    this.isDefault,
    this.createdAt,
    this.updatedAt,
    this.zipCode,
    this.title,
    this.latitude,
    this.longitude,
  });
  AddressShippingDetailModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    address = json['address']?.toString();
    customerId = json['customer_id']?.toInt();
    isDefault = json['is_default']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    zipCode = json['zip_code']?.toString();
    title = json['title']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['address'] = address;
    data['customer_id'] = customerId;
    data['is_default'] = isDefault;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['zip_code'] = zipCode;
    data['title'] = title;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    return data;
  }
}

class AddressShippingDetailModel {
/*
{
  "success": true,
  "message": "",
  "data": {
    "id": 13,
    "name": "test",
    "email": null,
    "phone": "test",
    "country": "test",
    "state": "test",
    "city": "test",
    "address": "test",
    "customer_id": 1,
    "is_default": 0,
    "created_at": "2024-03-19T04:26:14.000000Z",
    "updated_at": "2024-03-19T04:26:14.000000Z",
    "zip_code": "test",
    "title": "kantor",
    "latitude": "112.246454000",
    "longitude": "-7.213145000"
  }
} 
*/

  bool? success;
  String? message;
  AddressShippingDetailModelData? data;

  AddressShippingDetailModel({
    this.success,
    this.message,
    this.data,
  });
  AddressShippingDetailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? AddressShippingDetailModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
