///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlamatBuyerModelData {
/*
{
  "id": "1",
  "prov_id": "15",
  "kota_id": "264",
  "nama": "Jalan Surabaya No 1"
}
*/

  String? id;
  String? provId;
  String? kotaId;
  String? nama;

  AlamatBuyerModelData({
    this.id,
    this.provId,
    this.kotaId,
    this.nama,
  });
  AlamatBuyerModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    provId = json['prov_id']?.toString();
    kotaId = json['kota_id']?.toString();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['prov_id'] = provId;
    data['kota_id'] = kotaId;
    data['nama'] = nama;
    return data;
  }
}

class AlamatBuyerModel {
/*
{
  "result": "success",
  "data": [
    {
      "id": "1",
      "prov_id": "15",
      "kota_id": "264",
      "nama": "Jalan Surabaya No 1"
    }
  ]
}
*/

  String? result;
  List<AlamatBuyerModelData?>? data;

  AlamatBuyerModel({
    this.result,
    this.data,
  });
  AlamatBuyerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AlamatBuyerModelData>[];
      v.forEach((v) {
        arr0.add(AlamatBuyerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
