///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StreetNameModelAddress {
/*
{
  "road": "Impasse Val Emeraude",
  "quarter": "Bompard",
  "suburb": "7e Arrondissement",
  "city": "Marseille",
  "municipality": "Marseille",
  "county": "Bouches-du-Rhône",
  "ISO3166-2-lvl6": "FR-13",
  "state": "Provence-Alpes-Côte d'Azur",
  "ISO3166-2-lvl4": "FR-PAC",
  "region": "France métropolitaine",
  "postcode": "13007",
  "country": "France",
  "country_code": "fr"
} 
*/

  String? road;
  String? quarter;
  String? suburb;
  String? city;
  String? municipality;
  String? county;
  String? iSO31662Lvl6;
  String? state;
  String? iSO31662Lvl4;
  String? region;
  String? postcode;
  String? country;
  String? countryCode;

  StreetNameModelAddress({
    this.road,
    this.quarter,
    this.suburb,
    this.city,
    this.municipality,
    this.county,
    this.iSO31662Lvl6,
    this.state,
    this.iSO31662Lvl4,
    this.region,
    this.postcode,
    this.country,
    this.countryCode,
  });
  StreetNameModelAddress.fromJson(Map<String, dynamic> json) {
    road = json['road']?.toString();
    quarter = json['quarter']?.toString();
    suburb = json['suburb']?.toString();
    city = json['city']?.toString();
    municipality = json['municipality']?.toString();
    county = json['county']?.toString();
    iSO31662Lvl6 = json['ISO3166-2-lvl6']?.toString();
    state = json['state']?.toString();
    iSO31662Lvl4 = json['ISO3166-2-lvl4']?.toString();
    region = json['region']?.toString();
    postcode = json['postcode']?.toString();
    country = json['country']?.toString();
    countryCode = json['country_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['road'] = road;
    data['quarter'] = quarter;
    data['suburb'] = suburb;
    data['city'] = city;
    data['municipality'] = municipality;
    data['county'] = county;
    data['ISO3166-2-lvl6'] = iSO31662Lvl6;
    data['state'] = state;
    data['ISO3166-2-lvl4'] = iSO31662Lvl4;
    data['region'] = region;
    data['postcode'] = postcode;
    data['country'] = country;
    data['country_code'] = countryCode;
    return data;
  }
}

class StreetNameModel {
/*
{
  "place_id": 70379884,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 40938376,
  "lat": "43.2832398",
  "lon": "5.3670688",
  "class": "highway",
  "type": "residential",
  "place_rank": 26,
  "importance": 0.10000999999999993,
  "addresstype": "road",
  "name": "Impasse Val Emeraude",
  "display_name": "Impasse Val Emeraude, Bompard, 7e Arrondissement, Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, 13007, France",
  "address": {
    "road": "Impasse Val Emeraude",
    "quarter": "Bompard",
    "suburb": "7e Arrondissement",
    "city": "Marseille",
    "municipality": "Marseille",
    "county": "Bouches-du-Rhône",
    "ISO3166-2-lvl6": "FR-13",
    "state": "Provence-Alpes-Côte d'Azur",
    "ISO3166-2-lvl4": "FR-PAC",
    "region": "France métropolitaine",
    "postcode": "13007",
    "country": "France",
    "country_code": "fr"
  },
  "boundingbox": [
    "43.2830452"
  ]
} 
*/

  int? placeId;
  String? licence;
  String? osmType;
  int? osmId;
  String? lat;
  String? lon;
  String? theClass;
  String? type;
  int? placeRank;
  double? importance;
  String? addresstype;
  String? name;
  String? displayName;
  StreetNameModelAddress? address;
  List<String?>? boundingbox;

  StreetNameModel({
    this.placeId,
    this.licence,
    this.osmType,
    this.osmId,
    this.lat,
    this.lon,
    this.theClass,
    this.type,
    this.placeRank,
    this.importance,
    this.addresstype,
    this.name,
    this.displayName,
    this.address,
    this.boundingbox,
  });
  StreetNameModel.fromJson(Map<String, dynamic> json) {
    placeId = json['place_id']?.toInt();
    licence = json['licence']?.toString();
    osmType = json['osm_type']?.toString();
    osmId = json['osm_id']?.toInt();
    lat = json['lat']?.toString();
    lon = json['lon']?.toString();
    theClass = json['class']?.toString();
    type = json['type']?.toString();
    placeRank = json['place_rank']?.toInt();
    importance = json['importance']?.toDouble();
    addresstype = json['addresstype']?.toString();
    name = json['name']?.toString();
    displayName = json['display_name']?.toString();
    address = (json['address'] != null)
        ? StreetNameModelAddress.fromJson(json['address'])
        : null;
    if (json['boundingbox'] != null) {
      final v = json['boundingbox'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      boundingbox = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['place_id'] = placeId;
    data['licence'] = licence;
    data['osm_type'] = osmType;
    data['osm_id'] = osmId;
    data['lat'] = lat;
    data['lon'] = lon;
    data['class'] = theClass;
    data['type'] = type;
    data['place_rank'] = placeRank;
    data['importance'] = importance;
    data['addresstype'] = addresstype;
    data['name'] = name;
    data['display_name'] = displayName;
    if (address != null) {
      data['address'] = address!.toJson();
    }
    if (boundingbox != null) {
      final v = boundingbox;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['boundingbox'] = arr0;
    }
    return data;
  }
}
