import 'package:intl/intl.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetailChatSellerModelData {
/*
{
  "ID": "11",
  "Created": "2024-07-16 13:51:35",
  "Edited": "2024-07-16 13:51:35",
  "PengirimID": "148",
  "PenerimaID": "196",
  "BuyerID": "148",
  "SellerID": "196",
  "pesan": "halo",
  "dibaca": "1",
  "hapus": "0",
  "jenis": null,
  "attachment": null
}
*/

  String? ID;
  String? Created;
  String? Edited;
  String? PengirimID;
  String? PenerimaID;
  String? BuyerID;
  String? SellerID;
  String? pesan;
  String? dibaca;
  String? hapus;
  String? jenis;
  String? attachment;

  DetailChatSellerModelData({
    this.ID,
    this.Created,
    this.Edited,
    this.PengirimID,
    this.PenerimaID,
    this.BuyerID,
    this.SellerID,
    this.pesan,
    this.dibaca,
    this.hapus,
    this.jenis,
    this.attachment,
  });

  DetailChatSellerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    Created = json['Created']?.toString() ?? json['created_at']?.toString();
    Edited = json['Edited']?.toString() ?? json['updated_at']?.toString();
    var sellerId = json['seller'] == null ? null : json['seller']['id']?.toString();
    var userId = json['user'] == null ? null : json['user']['id']?.toString();
    
    PengirimID = json['PengirimID']?.toString() ?? 
        (json['is_seller'] == true || json['is_seller'] == 1 ? sellerId : userId);
    PenerimaID = json['PenerimaID']?.toString() ?? 
        (json['is_seller'] == true || json['is_seller'] == 1 ? userId : sellerId);
    BuyerID = json['BuyerID']?.toString() ?? userId;
    SellerID = json['SellerID']?.toString() ?? sellerId;
    pesan = json['pesan']?.toString() ?? json['message']?.toString();
    dibaca = json['dibaca']?.toString() ?? (json['is_read'] == true || json['is_read'] == 1 ? "1" : "0");
    hapus = json['hapus']?.toString();
    jenis = json['jenis']?.toString();
    attachment = json['attachment']?.toString();
  }
  
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Edited'] = Edited;
    data['PengirimID'] = PengirimID;
    data['PenerimaID'] = PenerimaID;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['pesan'] = pesan;
    data['dibaca'] = dibaca;
    data['hapus'] = hapus;
    data['jenis'] = jenis;
    data['attachment'] = attachment;
    return data;
  }
}

class DetailChatSellerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "11",
      "Created": "2024-07-16 13:51:35",
      "Edited": "2024-07-16 13:51:35",
      "PengirimID": "148",
      "PenerimaID": "196",
      "BuyerID": "148",
      "SellerID": "196",
      "pesan": "halo",
      "dibaca": "1",
      "hapus": "0",
      "jenis": null,
      "attachment": null
    }
  ]
}
*/

  String? result;
  List<DetailChatSellerModelData?>? data;

  DetailChatSellerModel({
    this.result,
    this.data,
  });
  DetailChatSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DetailChatSellerModelData>[];
      v.forEach((v) {
        arr0.add(DetailChatSellerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }

  String formatDate(String dateString) {
    DateTime date = DateTime.parse(dateString);
    DateTime now = DateTime.now();
    DateFormat formatter;

    // Check if the date is from the current year
    if (date.year == now.year) {
      formatter = DateFormat('d MMM');
    } else {
      formatter = DateFormat('d MMM yyyy');
    }

    return formatter.format(date);
  }

  Map<String, List<DetailChatSellerModelData>> groupDataByCreatedDate() {
    final Map<String, List<DetailChatSellerModelData>> groupedData = {};
    final DateFormat formatter = DateFormat('yyyy-MM-dd');

    if (data != null) {
      for (var item in data!) {
        if (item != null && item.Created != null) {
          DateTime createdDate = DateTime.parse(item.Created!);
          String formattedDate = formatter.format(createdDate);

          if (!groupedData.containsKey(formatDate(formattedDate))) {
            groupedData[formatDate(formattedDate)] = [];
          }
          groupedData[formatDate(formattedDate)]!.add(item);
        }
      }
    }

    return groupedData;
  }
}
