import 'package:intl/intl.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RiwayatKomplainSellerModelData {
/*
{
  "ID": "15",
  "Created": "2024-08-15 16:32:46",
  "Edited": "2024-08-15 16:32:46",
  "PengirimID": "196",
  "SellerID": "124",
  "BuyerID": "124",
  "SellerID": "196",
  "pesan": "Barang rusak",
  "dibaca": "1",
  "hapus": "0",
  "jenis": "komplain",
  "OrderID": "736",
  "attachment": ""
} 
*/

  String? ID;
  String? Created;
  String? Edited;
  String? PengirimID;
  String? SellerID;
  String? BuyerID;
  String? PenerimaID;
  String? pesan;
  String? dibaca;
  String? hapus;
  String? jenis;
  String? OrderID;
  String? attachment;

  RiwayatKomplainSellerModelData({
    this.ID,
    this.Created,
    this.Edited,
    this.PengirimID,
    this.SellerID,
    this.BuyerID,
    this.PenerimaID,
    this.pesan,
    this.dibaca,
    this.hapus,
    this.jenis,
    this.OrderID,
    this.attachment,
  });
  RiwayatKomplainSellerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Edited = json['Edited']?.toString();
    PengirimID = json['PengirimID']?.toString();
    SellerID = json['SellerID']?.toString();
    BuyerID = json['BuyerID']?.toString();
    PenerimaID = json['PenerimaID']?.toString();
    pesan = json['pesan']?.toString();
    dibaca = json['dibaca']?.toString();
    hapus = json['hapus']?.toString();
    jenis = json['jenis']?.toString();
    OrderID = json['OrderID']?.toString();
    attachment = json['attachment']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Edited'] = Edited;
    data['PengirimID'] = PengirimID;
    data['SellerID'] = SellerID;
    data['BuyerID'] = BuyerID;
    data['PenerimaID'] = PenerimaID;
    data['pesan'] = pesan;
    data['dibaca'] = dibaca;
    data['hapus'] = hapus;
    data['jenis'] = jenis;
    data['OrderID'] = OrderID;
    data['attachment'] = attachment;
    return data;
  }
}

class RiwayatKomplainSellerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "15",
      "Created": "2024-08-15 16:32:46",
      "Edited": "2024-08-15 16:32:46",
      "PengirimID": "196",
      "SellerID": "124",
      "BuyerID": "124",
      "SellerID": "196",
      "pesan": "Barang rusak",
      "dibaca": "1",
      "hapus": "0",
      "jenis": "komplain",
      "OrderID": "736",
      "attachment": ""
    }
  ]
} 
*/

  String? result;
  List<RiwayatKomplainSellerModelData?>? data;

  RiwayatKomplainSellerModel({
    this.result,
    this.data,
  });
  RiwayatKomplainSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RiwayatKomplainSellerModelData>[];
      v.forEach((v) {
        arr0.add(RiwayatKomplainSellerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }

  String formatDate(String dateString) {
    DateTime date = DateTime.parse(dateString);
    DateTime now = DateTime.now();
    DateFormat formatter;

    // Check if the date is from the current year
    if (date.year == now.year) {
      formatter = DateFormat('d MMM');
    } else {
      formatter = DateFormat('d MMM yyyy');
    }

    return formatter.format(date);
  }

  Map<String, List<RiwayatKomplainSellerModelData>> groupDataByCreatedDate() {
    final Map<String, List<RiwayatKomplainSellerModelData>> groupedData = {};
    final DateFormat formatter = DateFormat('yyyy-MM-dd');

    if (data != null) {
      for (var item in data!) {
        if (item != null && item.Created != null) {
          DateTime createdDate = DateTime.parse(item.Created!);
          String formattedDate = formatter.format(createdDate);

          if (!groupedData.containsKey(formatDate(formattedDate))) {
            groupedData[formatDate(formattedDate)] = [];
          }
          groupedData[formatDate(formattedDate)]!.add(item);
        }
      }
    }

    return groupedData;
  }
}
