///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NegoSellerModelData {
/*
{
  "ID": "870",
  "nama": "Bat Base",
  "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
  "qty": "1",
  "harga_akhir": "10000",
  "nego": "50.000",
  "nego2": "null",
  "nego3": "null",
  "SellerID": "196",
  "BuyerID": "148",
  "BuyerName": "Atria Buyer"
} 
*/

  String? ID;
  String? nama;
  String? foto;
  String? qty;
  String? hargaAkhir;
  String? nego;
  String? nego2;
  String? nego3;
  String? SellerID;
  String? BuyerID;
  String? BuyerName;

  NegoSellerModelData({
    this.ID,
    this.nama,
    this.foto,
    this.qty,
    this.hargaAkhir,
    this.nego,
    this.nego2,
    this.nego3,
    this.SellerID,
    this.BuyerID,
    this.BuyerName,
  });
  NegoSellerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    nama = json['nama']?.toString() ?? json['cart']?['product']?['name']?.toString();
    foto = json['foto']?.toString();
    qty = json['qty']?.toString() ?? json['cart']?['qty']?.toString();
    hargaAkhir = json['harga_akhir']?.toString() ?? json['cart']?['final_price']?.toString();
    nego = json['nego']?.toString() ?? json['value']?.toString();
    nego2 = json['nego2']?.toString();
    nego3 = json['nego3']?.toString();
    SellerID = json['SellerID']?.toString();
    BuyerID = json['BuyerID']?.toString() ?? json['cart']?['buyer']?['id']?.toString();
    BuyerName = json['BuyerName']?.toString() ?? json['cart']?['buyer']?['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['foto'] = foto;
    data['qty'] = qty;
    data['harga_akhir'] = hargaAkhir;
    data['nego'] = nego;
    data['nego2'] = nego2;
    data['nego3'] = nego3;
    data['SellerID'] = SellerID;
    data['BuyerID'] = BuyerID;
    data['BuyerName'] = BuyerName;
    return data;
  }
}

class NegoSellerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "870",
      "nama": "Bat Base",
      "foto": "https://mspeed.erdata.id/produk/scaled_IMG-20240802-WA0000-1200.jpg",
      "qty": "1",
      "harga_akhir": "10000",
      "nego": "50.000",
      "nego2": "null",
      "nego3": "null",
      "SellerID": "196",
      "BuyerID": "148",
      "BuyerName": "Atria Buyer"
    }
  ]
} 
*/

  String? result;
  List<NegoSellerModelData?>? data;

  NegoSellerModel({
    this.result,
    this.data,
  });
  NegoSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NegoSellerModelData>[];
      v.forEach((v) {
        arr0.add(NegoSellerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
