///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DppAdminModelData {
/*
{
  "ID": "68",
  "nomor_permintaan": "796/DPP/H207/VI/2024",
  "jumlah_prk": "1",
  "nilai_prk": "555000000",
  "IDPrk": "1617",
  "BuyerID": "101",
  "status": "0",
  "sisa": "555000000",
  "subdit_id": "7",
  "description": null
}
*/

  String? ID;
  String? nomorPermintaan;
  String? jumlahPrk;
  String? nilaiPrk;
  String? IDPrk;
  String? BuyerID;
  String? status;
  String? sisa;
  String? subditId;
  String? description;

  DppAdminModelData({
    this.ID,
    this.nomorPermintaan,
    this.jumlahPrk,
    this.nilaiPrk,
    this.IDPrk,
    this.BuyerID,
    this.status,
    this.sisa,
    this.subditId,
    this.description,
  });
  DppAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = (json['ID'] ?? json['id'])?.toString();
    nomorPermintaan = (json['nomor_permintaan'] ?? json['request_number'])?.toString();
    jumlahPrk = (json['jumlah_prk'] ?? json['prk_total'])?.toString();
    nilaiPrk = (json['nilai_prk'] ?? json['prk_value'])?.toString();
    IDPrk = (json['IDPrk'] ?? json['loan_prk_id'])?.toString();
    BuyerID = (json['BuyerID'] ?? json['user_data_id'])?.toString();
    status = json['status']?.toString();
    sisa = (json['sisa'] ?? json['remainder'])?.toString();
    subditId = (json['subdit_id'] ?? json['sub_direktorate_id'])?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nomor_permintaan'] = nomorPermintaan;
    data['jumlah_prk'] = jumlahPrk;
    data['nilai_prk'] = nilaiPrk;
    data['IDPrk'] = IDPrk;
    data['BuyerID'] = BuyerID;
    data['status'] = status;
    data['sisa'] = sisa;
    data['subdit_id'] = subditId;
    data['description'] = description;
    return data;
  }
}

class DppAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "68",
      "nomor_permintaan": "796/DPP/H207/VI/2024",
      "jumlah_prk": "1",
      "nilai_prk": "555000000",
      "IDPrk": "1617",
      "BuyerID": "101",
      "status": "0",
      "sisa": "555000000",
      "subdit_id": "7",
      "description": null
    }
  ]
}
*/

  String? result;
  List<DppAdminModelData?>? data;

  DppAdminModel({
    this.result,
    this.data,
  });
  DppAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DppAdminModelData>[];
      v.forEach((v) {
        arr0.add(DppAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
