///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderAdminModelData {
/*
{
  "ID": "111",
  "Created": "2024-08-21 15:08:09",
  "Updated": "2024-08-21 15:08:09",
  "nomor_order": "0104/SPS/M-Speed/24",
  "subtotal": "20000",
  "pajak": "3300",
  "ongkir": "10000",
  "total": "33300",
  "BuyerID": "148",
  "SellerID": "204",
  "nama": "Operasi MKP KP",
  "alamat": "Jalan Probolinggo No 12",
  "telp": "",
  "status": "PESANAN_BARU",
  "PengajuanID": "49",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "124",
  "penerimaStr": "",
  "keuanganID": "",
  "keuanganStr": "",
  "estPengiriman": "2024-08-21",
  "estPengiriman2": "2024-08-21",
  "nomor_invoice": "0104/INV/M-Speed/24",
  "nomor_suratjalan": "0104/SJL/M-Speed/24",
  "nomor_kwitansi": "0104/KWT/M-Speed/24",
  "read_status": "1",
  "tgl_ttd_kwitansi": "",
  "tgl_ttd_surat_pesanan": "",
  "tgl_ttd_surat_jalan": "",
  "tgl_ttd_invoice": "",
  "TempOrderID": "",
  "BuyerName": "Atria Buyer",
  "PenerimaName": "Operasi MKP KP",
  "SellerName": "CV Palugada "
} 
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? TempOrderID;
  String? BuyerName;
  String? PenerimaName;
  String? SellerName;

  OrderAdminModelData({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.TempOrderID,
    this.BuyerName,
    this.PenerimaName,
    this.SellerName,
  });
  OrderAdminModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    TempOrderID = json['TempOrderID']?.toString();
    BuyerName = json['BuyerName']?.toString();
    PenerimaName = json['PenerimaName']?.toString();
    SellerName = json['SellerName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['TempOrderID'] = TempOrderID;
    data['BuyerName'] = BuyerName;
    data['PenerimaName'] = PenerimaName;
    data['SellerName'] = SellerName;
    return data;
  }
}

class OrderAdminModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "111",
      "Created": "2024-08-21 15:08:09",
      "Updated": "2024-08-21 15:08:09",
      "nomor_order": "0104/SPS/M-Speed/24",
      "subtotal": "20000",
      "pajak": "3300",
      "ongkir": "10000",
      "total": "33300",
      "BuyerID": "148",
      "SellerID": "204",
      "nama": "Operasi MKP KP",
      "alamat": "Jalan Probolinggo No 12",
      "telp": "",
      "status": "PESANAN_BARU",
      "PengajuanID": "49",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "124",
      "penerimaStr": "",
      "keuanganID": "",
      "keuanganStr": "",
      "estPengiriman": "2024-08-21",
      "estPengiriman2": "2024-08-21",
      "nomor_invoice": "0104/INV/M-Speed/24",
      "nomor_suratjalan": "0104/SJL/M-Speed/24",
      "nomor_kwitansi": "0104/KWT/M-Speed/24",
      "read_status": "1",
      "tgl_ttd_kwitansi": "",
      "tgl_ttd_surat_pesanan": "",
      "tgl_ttd_surat_jalan": "",
      "tgl_ttd_invoice": "",
      "TempOrderID": "",
      "BuyerName": "Atria Buyer",
      "PenerimaName": "Operasi MKP KP",
      "SellerName": "CV Palugada "
    }
  ]
} 
*/

  String? result;
  List<OrderAdminModelData?>? data;

  OrderAdminModel({
    this.result,
    this.data,
  });
  OrderAdminModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <OrderAdminModelData>[];
      v.forEach((v) {
        arr0.add(OrderAdminModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
