///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelJenis {
/*
{
  "ID": "148",
  "email": "atriabuyer@gmail.com",
  "password": "$2y$10$yFJMXDG9BgMmMSQi3bAwYuJkXBQoL1zv/Mi2Gh9qQjFiwi2pUpQG.",
  "jenis": "BUYER",
  "aktif": "1",
  "hapus": "0",
  "kelengkapan": "1",
  "nama_perusahaan": "",
  "alamat": "",
  "tagging": "",
  "kegiatan_usaha": "",
  "pemilik_toko": "",
  "firstname": "Atria",
  "lastname": "Buyer",
  "HakAksesID": null,
  "status_pilihalamat": "0",
  "telp": null,
  "kabkota": null,
  "subdit_id": null
} 
*/

  String? ID;
  String? email;
  String? password;
  String? jenis;
  String? aktif;
  String? hapus;
  String? kelengkapan;
  String? namaPerusahaan;
  String? alamat;
  String? tagging;
  String? kegiatanUsaha;
  String? pemilikToko;
  String? firstname;
  String? lastname;
  String? HakAksesID;
  String? statusPilihalamat;
  String? telp;
  String? kabkota;
  String? subditId;
  bool? isAdmin;

  LoginModelJenis({
    this.ID,
    this.email,
    this.password,
    this.jenis,
    this.aktif,
    this.hapus,
    this.kelengkapan,
    this.namaPerusahaan,
    this.alamat,
    this.tagging,
    this.kegiatanUsaha,
    this.pemilikToko,
    this.firstname,
    this.lastname,
    this.HakAksesID,
    this.statusPilihalamat,
    this.telp,
    this.kabkota,
    this.subditId,
    this.isAdmin,
  });
  LoginModelJenis.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    jenis = json['jenis']?.toString();
    aktif = json['aktif']?.toString();
    hapus = json['hapus']?.toString();
    kelengkapan = json['kelengkapan']?.toString();
    namaPerusahaan = json['nama_perusahaan']?.toString();
    alamat = json['alamat']?.toString();
    tagging = json['tagging']?.toString();
    kegiatanUsaha = json['kegiatan_usaha']?.toString();
    pemilikToko = json['pemilik_toko']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    HakAksesID = json['HakAksesID']?.toString();
    statusPilihalamat = json['status_pilihalamat']?.toString();
    telp = json['telp']?.toString();
    kabkota = json['kabkota']?.toString();
    subditId = json['subdit_id']?.toString();
    isAdmin = json['is_admin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['email'] = email;
    data['password'] = password;
    data['jenis'] = jenis;
    data['aktif'] = aktif;
    data['hapus'] = hapus;
    data['kelengkapan'] = kelengkapan;
    data['nama_perusahaan'] = namaPerusahaan;
    data['alamat'] = alamat;
    data['tagging'] = tagging;
    data['kegiatan_usaha'] = kegiatanUsaha;
    data['pemilik_toko'] = pemilikToko;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['HakAksesID'] = HakAksesID;
    data['status_pilihalamat'] = statusPilihalamat;
    data['telp'] = telp;
    data['kabkota'] = kabkota;
    data['subdit_id'] = subditId;
    data['is_admin'] = isAdmin;
    return data;
  }
}

class LoginModel {
/*
{
  "result": "success",
  "jenis": {
    "ID": "148",
    "email": "atriabuyer@gmail.com",
    "password": "$2y$10$yFJMXDG9BgMmMSQi3bAwYuJkXBQoL1zv/Mi2Gh9qQjFiwi2pUpQG.",
    "jenis": "BUYER",
    "aktif": "1",
    "hapus": "0",
    "kelengkapan": "1",
    "nama_perusahaan": "",
    "alamat": "",
    "tagging": "",
    "kegiatan_usaha": "",
    "pemilik_toko": "",
    "firstname": "Atria",
    "lastname": "Buyer",
    "HakAksesID": null,
    "status_pilihalamat": "0",
    "telp": null,
    "kabkota": null,
    "subdit_id": null
  }
} 
*/

  String? result;
  LoginModelJenis? jenis;

  LoginModel({
    this.result,
    this.jenis,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    jenis = (json['jenis'] != null && (json['jenis'] is Map))
        ? LoginModelJenis.fromJson(json['jenis'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (jenis != null) {
      data['jenis'] = jenis!.toJson();
    }
    return data;
  }
}
