///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BuyerSellerFavoritModelData {
/*
{
  "ID": "3",
  "SellerID": "196",
  "BuyerID": "148",
  "SellerName": "Atria Seller",
  "alamat": "",
  "foto": "https://mspeed.erdata.id/seller/",
  "BuyerName": "AtriaBuyer"
}
*/

  String? ID;
  String? SellerID;
  String? BuyerID;
  String? SellerName;
  String? alamat;
  String? foto;
  String? BuyerName;

  BuyerSellerFavoritModelData({
    this.ID,
    this.SellerID,
    this.BuyerID,
    this.SellerName,
    this.alamat,
    this.foto,
    this.BuyerName,
  });
  BuyerSellerFavoritModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    SellerID = json['SellerID']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerName = json['SellerName']?.toString();
    alamat = json['alamat']?.toString();
    foto = json['foto']?.toString();
    BuyerName = json['BuyerName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['SellerID'] = SellerID;
    data['BuyerID'] = BuyerID;
    data['SellerName'] = SellerName;
    data['alamat'] = alamat;
    data['foto'] = foto;
    data['BuyerName'] = BuyerName;
    return data;
  }
}

class BuyerSellerFavoritModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "3",
      "SellerID": "196",
      "BuyerID": "148",
      "SellerName": "Atria Seller",
      "alamat": "",
      "foto": "https://mspeed.erdata.id/seller/",
      "BuyerName": "AtriaBuyer"
    }
  ]
}
*/

  String? result;
  List<BuyerSellerFavoritModelData?>? data;

  BuyerSellerFavoritModel({
    this.result,
    this.data,
  });
  BuyerSellerFavoritModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BuyerSellerFavoritModelData>[];
      v.forEach((v) {
        arr0.add(BuyerSellerFavoritModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
