///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BuyerWishlistModelDataDetail {
/*
{
  "ID": "1188",
  "IDWishlist": "93",
  "foto": "https://mspeed.erdata.id/produk/PaluAlatTukangBangunan.jpg",
  "SellerID": "203",
  "nama": "Palugada",
  "harga": "500000",
  "qty": "7",
  "IDKategori": "3"
}
*/

  String? ID;
  String? IDWishlist;
  String? foto;
  String? SellerID;
  String? nama;
  String? harga;
  String? qty;
  String? IDKategori;

  BuyerWishlistModelDataDetail({
    this.ID,
    this.IDWishlist,
    this.foto,
    this.SellerID,
    this.nama,
    this.harga,
    this.qty,
    this.IDKategori,
  });
  BuyerWishlistModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    IDWishlist = json['IDWishlist']?.toString();
    foto = json['foto']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    qty = json['qty']?.toString();
    IDKategori = json['IDKategori']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['IDWishlist'] = IDWishlist;
    data['foto'] = foto;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['qty'] = qty;
    data['IDKategori'] = IDKategori;
    return data;
  }
}

class BuyerWishlistModelData {
/*
{
  "SellerID": "203",
  "namaseller": "PT Kreasi Mulia",
  "detail": [
    {
      "ID": "1188",
      "IDWishlist": "93",
      "foto": "https://mspeed.erdata.id/produk/PaluAlatTukangBangunan.jpg",
      "SellerID": "203",
      "nama": "Palugada",
      "harga": "500000",
      "qty": "7",
      "IDKategori": "3"
    }
  ]
}
*/

  String? SellerID;
  String? namaseller;
  List<BuyerWishlistModelDataDetail?>? detail;

  BuyerWishlistModelData({
    this.SellerID,
    this.namaseller,
    this.detail,
  });
  BuyerWishlistModelData.fromJson(Map<String, dynamic> json) {
    SellerID = json['SellerID']?.toString();
    namaseller = json['namaseller']?.toString();
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <BuyerWishlistModelDataDetail>[];
      v.forEach((v) {
        arr0.add(BuyerWishlistModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['SellerID'] = SellerID;
    data['namaseller'] = namaseller;
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    return data;
  }
}

class BuyerWishlistModel {
/*
{
  "result": "success",
  "data": [
    {
      "SellerID": "203",
      "namaseller": "PT Kreasi Mulia",
      "detail": [
        {
          "ID": "1188",
          "IDWishlist": "93",
          "foto": "https://mspeed.erdata.id/produk/PaluAlatTukangBangunan.jpg",
          "SellerID": "203",
          "nama": "Palugada",
          "harga": "500000",
          "qty": "7",
          "IDKategori": "3"
        }
      ]
    }
  ]
}
*/

  String? result;
  List<BuyerWishlistModelData?>? data;

  BuyerWishlistModel({
    this.result,
    this.data,
  });
  BuyerWishlistModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BuyerWishlistModelData>[];
      v.forEach((v) {
        arr0.add(BuyerWishlistModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
