///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetailSellerBuyerDataDataRiwayatDetail {
/*
{
  "ID": "1204",
  "nama": "BOR LISTRIK ",
  "harga": "2500000",
  "kode_produk": "BRG-270824",
  "size": "",
  "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  "SellerID": "196",
  "hapus": "0",
  "foto": "https://mspeed.erdata.id/produk/scaled_1000050497-1204.jpg",
  "IDKategori": "3",
  "SellerNama": "Atria Seller",
  "no_rek": "",
  "qty": "1",
  "harga_akhir": "2500000",
  "diterima": "NO",
  "dikomplain": "NO",
  "komplain": "",
  "IDOrder": "778"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;
  String? SellerNama;
  String? noRek;
  String? qty;
  String? hargaAkhir;
  String? diterima;
  String? dikomplain;
  String? komplain;
  String? IDOrder;

  DetailSellerBuyerDataDataRiwayatDetail({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
    this.SellerNama,
    this.noRek,
    this.qty,
    this.hargaAkhir,
    this.diterima,
    this.dikomplain,
    this.komplain,
    this.IDOrder,
  });
  DetailSellerBuyerDataDataRiwayatDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
    SellerNama = json['SellerNama']?.toString();
    noRek = json['no_rek']?.toString();
    qty = json['qty']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    diterima = json['diterima']?.toString();
    dikomplain = json['dikomplain']?.toString();
    komplain = json['komplain']?.toString();
    IDOrder = json['IDOrder']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    data['SellerNama'] = SellerNama;
    data['no_rek'] = noRek;
    data['qty'] = qty;
    data['harga_akhir'] = hargaAkhir;
    data['diterima'] = diterima;
    data['dikomplain'] = dikomplain;
    data['komplain'] = komplain;
    data['IDOrder'] = IDOrder;
    return data;
  }
}

class DetailSellerBuyerDataDataRiwayat {
/*
{
  "ID": "136",
  "Created": "2024-09-12 09:48:25",
  "Updated": "2024-09-12 09:48:25",
  "nomor_order": "0129/SPS/M-Speed/24",
  "subtotal": "2473600",
  "pajak": "26400",
  "ongkir": "0",
  "total": "2500000",
  "BuyerID": "148",
  "SellerID": "196",
  "nama": "Atria Buyer",
  "alamat": "Jalan Surabaya No 1",
  "telp": "",
  "status": "PESANAN_DITERIMA",
  "PengajuanID": "68",
  "keterangan": "",
  "bukti": "",
  "penerimaID": "148",
  "penerimaStr": "null",
  "keuanganID": "null",
  "keuanganStr": "null",
  "estPengiriman": "0000-00-00",
  "estPengiriman2": "0000-00-00",
  "nomor_invoice": "0129/INV/M-Speed/24",
  "nomor_suratjalan": "0129/SJL/M-Speed/24",
  "nomor_kwitansi": "0129/KWT/M-Speed/24",
  "read_status": "2",
  "tgl_ttd_kwitansi": "null",
  "tgl_ttd_surat_pesanan": "null",
  "tgl_ttd_surat_jalan": "null",
  "tgl_ttd_invoice": "null",
  "TempOrderID": "305",
  "jum": "1",
  "SellerNama": "Atria Seller",
  "detail": [
    {
      "ID": "1204",
      "nama": "BOR LISTRIK ",
      "harga": "2500000",
      "kode_produk": "BRG-270824",
      "size": "",
      "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SellerID": "196",
      "hapus": "0",
      "foto": "https://mspeed.erdata.id/produk/scaled_1000050497-1204.jpg",
      "IDKategori": "3",
      "SellerNama": "Atria Seller",
      "no_rek": "",
      "qty": "1",
      "harga_akhir": "2500000",
      "diterima": "NO",
      "dikomplain": "NO",
      "komplain": "",
      "IDOrder": "778"
    }
  ]
}
*/

  String? ID;
  String? Created;
  String? Updated;
  String? nomorOrder;
  String? subtotal;
  String? pajak;
  String? ongkir;
  String? total;
  String? BuyerID;
  String? SellerID;
  String? nama;
  String? alamat;
  String? telp;
  String? status;
  String? PengajuanID;
  String? keterangan;
  String? bukti;
  String? penerimaID;
  String? penerimaStr;
  String? keuanganID;
  String? keuanganStr;
  String? estPengiriman;
  String? estPengiriman2;
  String? nomorInvoice;
  String? nomorSuratjalan;
  String? nomorKwitansi;
  String? readStatus;
  String? tglTtdKwitansi;
  String? tglTtdSuratPesanan;
  String? tglTtdSuratJalan;
  String? tglTtdInvoice;
  String? TempOrderID;
  String? jum;
  String? SellerNama;
  List<DetailSellerBuyerDataDataRiwayatDetail?>? detail;

  DetailSellerBuyerDataDataRiwayat({
    this.ID,
    this.Created,
    this.Updated,
    this.nomorOrder,
    this.subtotal,
    this.pajak,
    this.ongkir,
    this.total,
    this.BuyerID,
    this.SellerID,
    this.nama,
    this.alamat,
    this.telp,
    this.status,
    this.PengajuanID,
    this.keterangan,
    this.bukti,
    this.penerimaID,
    this.penerimaStr,
    this.keuanganID,
    this.keuanganStr,
    this.estPengiriman,
    this.estPengiriman2,
    this.nomorInvoice,
    this.nomorSuratjalan,
    this.nomorKwitansi,
    this.readStatus,
    this.tglTtdKwitansi,
    this.tglTtdSuratPesanan,
    this.tglTtdSuratJalan,
    this.tglTtdInvoice,
    this.TempOrderID,
    this.jum,
    this.SellerNama,
    this.detail,
  });
  DetailSellerBuyerDataDataRiwayat.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    Created = json['Created']?.toString();
    Updated = json['Updated']?.toString();
    nomorOrder = json['nomor_order']?.toString();
    subtotal = json['subtotal']?.toString();
    pajak = json['pajak']?.toString();
    ongkir = json['ongkir']?.toString();
    total = json['total']?.toString();
    BuyerID = json['BuyerID']?.toString();
    SellerID = json['SellerID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    telp = json['telp']?.toString();
    status = json['status']?.toString();
    PengajuanID = json['PengajuanID']?.toString();
    keterangan = json['keterangan']?.toString();
    bukti = json['bukti']?.toString();
    penerimaID = json['penerimaID']?.toString();
    penerimaStr = json['penerimaStr']?.toString();
    keuanganID = json['keuanganID']?.toString();
    keuanganStr = json['keuanganStr']?.toString();
    estPengiriman = json['estPengiriman']?.toString();
    estPengiriman2 = json['estPengiriman2']?.toString();
    nomorInvoice = json['nomor_invoice']?.toString();
    nomorSuratjalan = json['nomor_suratjalan']?.toString();
    nomorKwitansi = json['nomor_kwitansi']?.toString();
    readStatus = json['read_status']?.toString();
    tglTtdKwitansi = json['tgl_ttd_kwitansi']?.toString();
    tglTtdSuratPesanan = json['tgl_ttd_surat_pesanan']?.toString();
    tglTtdSuratJalan = json['tgl_ttd_surat_jalan']?.toString();
    tglTtdInvoice = json['tgl_ttd_invoice']?.toString();
    TempOrderID = json['TempOrderID']?.toString();
    jum = json['jum']?.toString();
    SellerNama = json['SellerNama']?.toString();
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <DetailSellerBuyerDataDataRiwayatDetail>[];
      v.forEach((v) {
        arr0.add(DetailSellerBuyerDataDataRiwayatDetail.fromJson(v));
      });
      detail = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['Created'] = Created;
    data['Updated'] = Updated;
    data['nomor_order'] = nomorOrder;
    data['subtotal'] = subtotal;
    data['pajak'] = pajak;
    data['ongkir'] = ongkir;
    data['total'] = total;
    data['BuyerID'] = BuyerID;
    data['SellerID'] = SellerID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['telp'] = telp;
    data['status'] = status;
    data['PengajuanID'] = PengajuanID;
    data['keterangan'] = keterangan;
    data['bukti'] = bukti;
    data['penerimaID'] = penerimaID;
    data['penerimaStr'] = penerimaStr;
    data['keuanganID'] = keuanganID;
    data['keuanganStr'] = keuanganStr;
    data['estPengiriman'] = estPengiriman;
    data['estPengiriman2'] = estPengiriman2;
    data['nomor_invoice'] = nomorInvoice;
    data['nomor_suratjalan'] = nomorSuratjalan;
    data['nomor_kwitansi'] = nomorKwitansi;
    data['read_status'] = readStatus;
    data['tgl_ttd_kwitansi'] = tglTtdKwitansi;
    data['tgl_ttd_surat_pesanan'] = tglTtdSuratPesanan;
    data['tgl_ttd_surat_jalan'] = tglTtdSuratJalan;
    data['tgl_ttd_invoice'] = tglTtdInvoice;
    data['TempOrderID'] = TempOrderID;
    data['jum'] = jum;
    data['SellerNama'] = SellerNama;
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    return data;
  }
}

class DetailSellerBuyerDataDataKategori {
/*
{
  "nama": "Consumable"
}
*/

  String? nama;

  DetailSellerBuyerDataDataKategori({
    this.nama,
  });
  DetailSellerBuyerDataDataKategori.fromJson(Map<String, dynamic> json) {
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nama'] = nama;
    return data;
  }
}

class DetailSellerBuyerDataDataProduk {
/*
{
  "ID": "1183",
  "nama": "Barang Atria",
  "harga": "5000",
  "kode_produk": "ATR",
  "size": "",
  "qty": "85",
  "deskripsi": "Desc Barang Atria",
  "SellerID": "196",
  "hapus": "0",
  "foto": "",
  "IDKategori": "1"
}
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;

  DetailSellerBuyerDataDataProduk({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
  });
  DetailSellerBuyerDataDataProduk.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    return data;
  }
}

class DetailSellerBuyerDataGetSeller {
/*
{
  "ID": "196",
  "nama": "Atria Seller",
  "alamat": "Surabaya",
  "lokasi": "Lokasi Atria",
  "lattitude": "",
  "longitude": "",
  "email": "atriaseller@gmail.com",
  "telp": "08989898989",
  "kbli": "",
  "nama_pemilik": "Bayu Dibya Saputra",
  "nama_cp": "Bayu",
  "telp_cp": "098989898989",
  "foto": "",
  "no_npwp": "",
  "npwp": "",
  "no_ktp": "",
  "ktp": "",
  "sp_pkp": "",
  "prov": "null",
  "kota": "Sidoarjo",
  "no_rek": "",
  "an_rek": "",
  "bank": "",
  "buku_rekening": "null"
}
*/

  String? ID;
  String? nama;
  String? alamat;
  String? lokasi;
  String? lattitude;
  String? longitude;
  String? email;
  String? telp;
  String? kbli;
  String? namaPemilik;
  String? namaCp;
  String? telpCp;
  String? foto;
  String? noNpwp;
  String? npwp;
  String? noKtp;
  String? ktp;
  String? spPkp;
  String? prov;
  String? kota;
  String? noRek;
  String? anRek;
  String? bank;
  String? bukuRekening;

  DetailSellerBuyerDataGetSeller({
    this.ID,
    this.nama,
    this.alamat,
    this.lokasi,
    this.lattitude,
    this.longitude,
    this.email,
    this.telp,
    this.kbli,
    this.namaPemilik,
    this.namaCp,
    this.telpCp,
    this.foto,
    this.noNpwp,
    this.npwp,
    this.noKtp,
    this.ktp,
    this.spPkp,
    this.prov,
    this.kota,
    this.noRek,
    this.anRek,
    this.bank,
    this.bukuRekening,
  });
  DetailSellerBuyerDataGetSeller.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    alamat = json['alamat']?.toString();
    lokasi = json['lokasi']?.toString();
    lattitude = json['lattitude']?.toString();
    longitude = json['longitude']?.toString();
    email = json['email']?.toString();
    telp = json['telp']?.toString();
    kbli = json['kbli']?.toString();
    namaPemilik = json['nama_pemilik']?.toString();
    namaCp = json['nama_cp']?.toString();
    telpCp = json['telp_cp']?.toString();
    foto = json['foto']?.toString();
    noNpwp = json['no_npwp']?.toString();
    npwp = json['npwp']?.toString();
    noKtp = json['no_ktp']?.toString();
    ktp = json['ktp']?.toString();
    spPkp = json['sp_pkp']?.toString();
    prov = json['prov']?.toString();
    kota = json['kota']?.toString();
    noRek = json['no_rek']?.toString();
    anRek = json['an_rek']?.toString();
    bank = json['bank']?.toString();
    bukuRekening = json['buku_rekening']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['alamat'] = alamat;
    data['lokasi'] = lokasi;
    data['lattitude'] = lattitude;
    data['longitude'] = longitude;
    data['email'] = email;
    data['telp'] = telp;
    data['kbli'] = kbli;
    data['nama_pemilik'] = namaPemilik;
    data['nama_cp'] = namaCp;
    data['telp_cp'] = telpCp;
    data['foto'] = foto;
    data['no_npwp'] = noNpwp;
    data['npwp'] = npwp;
    data['no_ktp'] = noKtp;
    data['ktp'] = ktp;
    data['sp_pkp'] = spPkp;
    data['prov'] = prov;
    data['kota'] = kota;
    data['no_rek'] = noRek;
    data['an_rek'] = anRek;
    data['bank'] = bank;
    data['buku_rekening'] = bukuRekening;
    return data;
  }
}

class DetailSellerBuyerData {
/*
{
  "total_produk": "11",
  "jumlah_transaksi": "10",
  "jumlah_buyer": "10",
  "getSeller": {
    "ID": "196",
    "nama": "Atria Seller",
    "alamat": "Surabaya",
    "lokasi": "Lokasi Atria",
    "lattitude": "",
    "longitude": "",
    "email": "atriaseller@gmail.com",
    "telp": "08989898989",
    "kbli": "",
    "nama_pemilik": "Bayu Dibya Saputra",
    "nama_cp": "Bayu",
    "telp_cp": "098989898989",
    "foto": "",
    "no_npwp": "",
    "npwp": "",
    "no_ktp": "",
    "ktp": "",
    "sp_pkp": "",
    "prov": "null",
    "kota": "Sidoarjo",
    "no_rek": "",
    "an_rek": "",
    "bank": "",
    "buku_rekening": "null"
  },
  "dataProduk": [
    {
      "ID": "1183",
      "nama": "Barang Atria",
      "harga": "5000",
      "kode_produk": "ATR",
      "size": "",
      "qty": "85",
      "deskripsi": "Desc Barang Atria",
      "SellerID": "196",
      "hapus": "0",
      "foto": "",
      "IDKategori": "1"
    }
  ],
  "dataKategori": [
    {
      "nama": "Consumable"
    }
  ],
  "dataRiwayat": [
    {
      "ID": "136",
      "Created": "2024-09-12 09:48:25",
      "Updated": "2024-09-12 09:48:25",
      "nomor_order": "0129/SPS/M-Speed/24",
      "subtotal": "2473600",
      "pajak": "26400",
      "ongkir": "0",
      "total": "2500000",
      "BuyerID": "148",
      "SellerID": "196",
      "nama": "Atria Buyer",
      "alamat": "Jalan Surabaya No 1",
      "telp": "",
      "status": "PESANAN_DITERIMA",
      "PengajuanID": "68",
      "keterangan": "",
      "bukti": "",
      "penerimaID": "148",
      "penerimaStr": "null",
      "keuanganID": "null",
      "keuanganStr": "null",
      "estPengiriman": "0000-00-00",
      "estPengiriman2": "0000-00-00",
      "nomor_invoice": "0129/INV/M-Speed/24",
      "nomor_suratjalan": "0129/SJL/M-Speed/24",
      "nomor_kwitansi": "0129/KWT/M-Speed/24",
      "read_status": "2",
      "tgl_ttd_kwitansi": "null",
      "tgl_ttd_surat_pesanan": "null",
      "tgl_ttd_surat_jalan": "null",
      "tgl_ttd_invoice": "null",
      "TempOrderID": "305",
      "jum": "1",
      "SellerNama": "Atria Seller",
      "detail": [
        {
          "ID": "1204",
          "nama": "BOR LISTRIK ",
          "harga": "2500000",
          "kode_produk": "BRG-270824",
          "size": "",
          "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
          "SellerID": "196",
          "hapus": "0",
          "foto": "https://mspeed.erdata.id/produk/scaled_1000050497-1204.jpg",
          "IDKategori": "3",
          "SellerNama": "Atria Seller",
          "no_rek": "",
          "qty": "1",
          "harga_akhir": "2500000",
          "diterima": "NO",
          "dikomplain": "NO",
          "komplain": "",
          "IDOrder": "778"
        }
      ]
    }
  ]
}
*/

  String? totalProduk;
  String? jumlahTransaksi;
  String? jumlahBuyer;
  DetailSellerBuyerDataGetSeller? getSeller;
  List<DetailSellerBuyerDataDataProduk?>? dataProduk;
  List<DetailSellerBuyerDataDataKategori?>? dataKategori;
  List<DetailSellerBuyerDataDataRiwayat?>? dataRiwayat;

  DetailSellerBuyerData({
    this.totalProduk,
    this.jumlahTransaksi,
    this.jumlahBuyer,
    this.getSeller,
    this.dataProduk,
    this.dataKategori,
    this.dataRiwayat,
  });
  DetailSellerBuyerData.fromJson(Map<String, dynamic> json) {
    totalProduk = json['total_produk']?.toString();
    jumlahTransaksi = json['jumlah_transaksi']?.toString();
    jumlahBuyer = json['jumlah_buyer']?.toString();
    getSeller = (json['getSeller'] != null) ? DetailSellerBuyerDataGetSeller.fromJson(json['getSeller']) : null;
    if (json['dataProduk'] != null) {
      final v = json['dataProduk'];
      final arr0 = <DetailSellerBuyerDataDataProduk>[];
      v.forEach((v) {
        arr0.add(DetailSellerBuyerDataDataProduk.fromJson(v));
      });
      dataProduk = arr0;
    }
    if (json['dataKategori'] != null) {
      final v = json['dataKategori'];
      final arr0 = <DetailSellerBuyerDataDataKategori>[];
      v.forEach((v) {
        arr0.add(DetailSellerBuyerDataDataKategori.fromJson(v));
      });
      dataKategori = arr0;
    }
    if (json['dataRiwayat'] != null) {
      final v = json['dataRiwayat'];
      final arr0 = <DetailSellerBuyerDataDataRiwayat>[];
      v.forEach((v) {
        arr0.add(DetailSellerBuyerDataDataRiwayat.fromJson(v));
      });
      dataRiwayat = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_produk'] = totalProduk;
    data['jumlah_transaksi'] = jumlahTransaksi;
    data['jumlah_buyer'] = jumlahBuyer;
    if (getSeller != null) {
      data['getSeller'] = getSeller!.toJson();
    }
    if (dataProduk != null) {
      final v = dataProduk;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['dataProduk'] = arr0;
    }
    if (dataKategori != null) {
      final v = dataKategori;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['dataKategori'] = arr0;
    }
    if (dataRiwayat != null) {
      final v = dataRiwayat;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['dataRiwayat'] = arr0;
    }
    return data;
  }
}

class DetailSellerBuyer {
/*
{
  "result": "success",
  "data": {
    "total_produk": "11",
    "jumlah_transaksi": "10",
    "jumlah_buyer": "10",
    "getSeller": {
      "ID": "196",
      "nama": "Atria Seller",
      "alamat": "Surabaya",
      "lokasi": "Lokasi Atria",
      "lattitude": "",
      "longitude": "",
      "email": "atriaseller@gmail.com",
      "telp": "08989898989",
      "kbli": "",
      "nama_pemilik": "Bayu Dibya Saputra",
      "nama_cp": "Bayu",
      "telp_cp": "098989898989",
      "foto": "",
      "no_npwp": "",
      "npwp": "",
      "no_ktp": "",
      "ktp": "",
      "sp_pkp": "",
      "prov": "null",
      "kota": "Sidoarjo",
      "no_rek": "",
      "an_rek": "",
      "bank": "",
      "buku_rekening": "null"
    },
    "dataProduk": [
      {
        "ID": "1183",
        "nama": "Barang Atria",
        "harga": "5000",
        "kode_produk": "ATR",
        "size": "",
        "qty": "85",
        "deskripsi": "Desc Barang Atria",
        "SellerID": "196",
        "hapus": "0",
        "foto": "",
        "IDKategori": "1"
      }
    ],
    "dataKategori": [
      {
        "nama": "Consumable"
      }
    ],
    "dataRiwayat": [
      {
        "ID": "136",
        "Created": "2024-09-12 09:48:25",
        "Updated": "2024-09-12 09:48:25",
        "nomor_order": "0129/SPS/M-Speed/24",
        "subtotal": "2473600",
        "pajak": "26400",
        "ongkir": "0",
        "total": "2500000",
        "BuyerID": "148",
        "SellerID": "196",
        "nama": "Atria Buyer",
        "alamat": "Jalan Surabaya No 1",
        "telp": "",
        "status": "PESANAN_DITERIMA",
        "PengajuanID": "68",
        "keterangan": "",
        "bukti": "",
        "penerimaID": "148",
        "penerimaStr": "null",
        "keuanganID": "null",
        "keuanganStr": "null",
        "estPengiriman": "0000-00-00",
        "estPengiriman2": "0000-00-00",
        "nomor_invoice": "0129/INV/M-Speed/24",
        "nomor_suratjalan": "0129/SJL/M-Speed/24",
        "nomor_kwitansi": "0129/KWT/M-Speed/24",
        "read_status": "2",
        "tgl_ttd_kwitansi": "null",
        "tgl_ttd_surat_pesanan": "null",
        "tgl_ttd_surat_jalan": "null",
        "tgl_ttd_invoice": "null",
        "TempOrderID": "305",
        "jum": "1",
        "SellerNama": "Atria Seller",
        "detail": [
          {
            "ID": "1204",
            "nama": "BOR LISTRIK ",
            "harga": "2500000",
            "kode_produk": "BRG-270824",
            "size": "",
            "deskripsi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "SellerID": "196",
            "hapus": "0",
            "foto": "https://mspeed.erdata.id/produk/scaled_1000050497-1204.jpg",
            "IDKategori": "3",
            "SellerNama": "Atria Seller",
            "no_rek": "",
            "qty": "1",
            "harga_akhir": "2500000",
            "diterima": "NO",
            "dikomplain": "NO",
            "komplain": "",
            "IDOrder": "778"
          }
        ]
      }
    ]
  }
}
*/

  String? result;
  DetailSellerBuyerData? data;

  DetailSellerBuyer({
    this.result,
    this.data,
  });
  DetailSellerBuyer.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? DetailSellerBuyerData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
