///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishlistCreateKoleksiDataType {
/*
{
  "value": "whishlist",
  "label": "whishlist"
}
*/

  String? value;
  String? label;

  WishlistCreateKoleksiDataType({
    this.value,
    this.label,
  });
  WishlistCreateKoleksiDataType.fromJson(Map<String, dynamic> json) {
    value = json['value']?.toString();
    label = json['label']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['value'] = value;
    data['label'] = label;
    return data;
  }
}

class WishlistCreateKoleksiData {
/*
{
  "user_id": 11,
  "type": {
    "value": "whishlist",
    "label": "whishlist"
  },
  "name": "testing",
  "updated_at": "2024-04-17T03:24:01.000000Z",
  "created_at": "2024-04-17T03:24:01.000000Z",
  "id": 2
}
*/

  int? userId;
  WishlistCreateKoleksiDataType? type;
  String? name;
  String? updatedAt;
  String? createdAt;
  int? id;

  WishlistCreateKoleksiData({
    this.userId,
    this.type,
    this.name,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  WishlistCreateKoleksiData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    type = (json['type'] != null) ? WishlistCreateKoleksiDataType.fromJson(json['type']) : null;
    name = json['name']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    if (type != null) {
      data['type'] = type!.toJson();
    }
    data['name'] = name;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class WishlistCreateKoleksi {
/*
{
  "success": true,
  "message": "",
  "data": {
    "user_id": 11,
    "type": {
      "value": "whishlist",
      "label": "whishlist"
    },
    "name": "testing",
    "updated_at": "2024-04-17T03:24:01.000000Z",
    "created_at": "2024-04-17T03:24:01.000000Z",
    "id": 2
  }
}
*/

  bool? success;
  String? message;
  WishlistCreateKoleksiData? data;

  WishlistCreateKoleksi({
    this.success,
    this.message,
    this.data,
  });
  WishlistCreateKoleksi.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? WishlistCreateKoleksiData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
