///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishlistDetailModelDataItems {
/*
{
  "id": 14,
  "product_id": 91,
  "product_parent_id": 91,
  "slug": "/products/gergaji-kayu-hand-saw-16400mm-finder",
  "name": "GERGAJI KAYU HAND SAW 16\"/400mm FINDER",
  "qty": 1,
  "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/finder/sbm-191713-sampe-sbm-191715.jpg",
  "price": 160912.16,
  "price_desc": "Rp 160.912",
  "price_promo": 11,
  "price_promo_desc": "Rp 0",
  "option": "null",
  "subtotal_item": 160912.16,
  "subtotal_item_desc": "Rp 160.912",
  "product_variation": "",
  "allow_checkout_when_out_of_stock": 0,
  "stock": 10,
  "store_name": "Sinar Bintang Mulia",
  "store_slug": "sinar-bintang-mulia",
  "store_logo": "https://sibima.sgp1.cdn.digitaloceanspaces.com/sbm.jpeg",
  "rating": 0,
  "total_review": 0
}
*/

  int? id;
  int? productId;
  int? productParentId;
  String? slug;
  String? name;
  int? qty;
  String? image;
  double? price;
  String? priceDesc;
  int? pricePromo;
  String? pricePromoDesc;
  String? option;
  double? subtotalItem;
  String? subtotalItemDesc;
  String? productVariation;
  int? allowCheckoutWhenOutOfStock;
  int? stock;
  String? storeName;
  String? storeSlug;
  String? storeLogo;
  int? rating;
  int? totalReview;

  WishlistDetailModelDataItems({
    this.id,
    this.productId,
    this.productParentId,
    this.slug,
    this.name,
    this.qty,
    this.image,
    this.price,
    this.priceDesc,
    this.pricePromo,
    this.pricePromoDesc,
    this.option,
    this.subtotalItem,
    this.subtotalItemDesc,
    this.productVariation,
    this.allowCheckoutWhenOutOfStock,
    this.stock,
    this.storeName,
    this.storeSlug,
    this.storeLogo,
    this.rating,
    this.totalReview,
  });
  WishlistDetailModelDataItems.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    productId = json['product_id']?.toInt();
    productParentId = json['product_parent_id']?.toInt();
    slug = json['slug']?.toString();
    name = json['name']?.toString();
    qty = json['qty']?.toInt();
    image = json['image']?.toString();
    price = json['price']?.toDouble();
    priceDesc = json['price_desc']?.toString();
    pricePromo = json['price_promo']?.toInt();
    pricePromoDesc = json['price_promo_desc']?.toString();
    option = json['option']?.toString();
    subtotalItem = json['subtotal_item']?.toDouble();
    subtotalItemDesc = json['subtotal_item_desc']?.toString();
    productVariation = json['product_variation']?.toString();
    allowCheckoutWhenOutOfStock = json['allow_checkout_when_out_of_stock']?.toInt();
    stock = json['stock']?.toInt();
    storeName = json['store_name']?.toString();
    storeSlug = json['store_slug']?.toString();
    storeLogo = json['store_logo']?.toString();
    rating = json['rating']?.toInt();
    totalReview = json['total_review']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_id'] = productId;
    data['product_parent_id'] = productParentId;
    data['slug'] = slug;
    data['name'] = name;
    data['qty'] = qty;
    data['image'] = image;
    data['price'] = price;
    data['price_desc'] = priceDesc;
    data['price_promo'] = pricePromo;
    data['price_promo_desc'] = pricePromoDesc;
    data['option'] = option;
    data['subtotal_item'] = subtotalItem;
    data['subtotal_item_desc'] = subtotalItemDesc;
    data['product_variation'] = productVariation;
    data['allow_checkout_when_out_of_stock'] = allowCheckoutWhenOutOfStock;
    data['stock'] = stock;
    data['store_name'] = storeName;
    data['store_slug'] = storeSlug;
    data['store_logo'] = storeLogo;
    data['rating'] = rating;
    data['total_review'] = totalReview;
    return data;
  }
}

class WishlistDetailModelData {
/*
{
  "id": 4,
  "name": "ehe9",
  "created_at": "17 April 2024 16:23",
  "items": [
    {
      "id": 14,
      "product_id": 91,
      "product_parent_id": 91,
      "slug": "/products/gergaji-kayu-hand-saw-16400mm-finder",
      "name": "GERGAJI KAYU HAND SAW 16\"/400mm FINDER",
      "qty": 1,
      "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/finder/sbm-191713-sampe-sbm-191715.jpg",
      "price": 160912.16,
      "price_desc": "Rp 160.912",
      "price_promo": 11,
      "price_promo_desc": "Rp 0",
      "option": "null",
      "subtotal_item": 160912.16,
      "subtotal_item_desc": "Rp 160.912",
      "product_variation": "",
      "allow_checkout_when_out_of_stock": 0,
      "stock": 10,
      "store_name": "Sinar Bintang Mulia",
      "store_slug": "sinar-bintang-mulia",
      "store_logo": "https://sibima.sgp1.cdn.digitaloceanspaces.com/sbm.jpeg",
      "rating": 0,
      "total_review": 0
    }
  ]
}
*/

  int? id;
  String? name;
  String? createdAt;
  List<WishlistDetailModelDataItems?>? items;

  WishlistDetailModelData({
    this.id,
    this.name,
    this.createdAt,
    this.items,
  });
  WishlistDetailModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    createdAt = json['created_at']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <WishlistDetailModelDataItems>[];
      v.forEach((v) {
        arr0.add(WishlistDetailModelDataItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['created_at'] = createdAt;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}

class WishlistDetailModel {
/*
{
  "success": true,
  "message": "",
  "data": {
    "id": 4,
    "name": "ehe9",
    "created_at": "17 April 2024 16:23",
    "items": [
      {
        "id": 14,
        "product_id": 91,
        "product_parent_id": 91,
        "slug": "/products/gergaji-kayu-hand-saw-16400mm-finder",
        "name": "GERGAJI KAYU HAND SAW 16\"/400mm FINDER",
        "qty": 1,
        "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/finder/sbm-191713-sampe-sbm-191715.jpg",
        "price": 160912.16,
        "price_desc": "Rp 160.912",
        "price_promo": 11,
        "price_promo_desc": "Rp 0",
        "option": "null",
        "subtotal_item": 160912.16,
        "subtotal_item_desc": "Rp 160.912",
        "product_variation": "",
        "allow_checkout_when_out_of_stock": 0,
        "stock": 10,
        "store_name": "Sinar Bintang Mulia",
        "store_slug": "sinar-bintang-mulia",
        "store_logo": "https://sibima.sgp1.cdn.digitaloceanspaces.com/sbm.jpeg",
        "rating": 0,
        "total_review": 0
      }
    ]
  }
}
*/

  bool? success;
  String? message;
  WishlistDetailModelData? data;

  WishlistDetailModel({
    this.success,
    this.message,
    this.data,
  });
  WishlistDetailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? WishlistDetailModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
      return data;
  }
}
