///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishlistModelData {
/*
{
  "id": 4,
  "name": "ehe7",
  "created_at": "17 April 2024 16:23",
  "image": [
    "https://sibima.sgp1.cdn.digitaloceanspaces.com/no-image.png"
  ],
  "count_items": 2
}
*/

  int? id;
  String? name;
  String? createdAt;
  List<String?>? image;
  int? countItems;

  WishlistModelData({
    this.id,
    this.name,
    this.createdAt,
    this.image,
    this.countItems,
  });
  WishlistModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    createdAt = json['created_at']?.toString();
    if (json['image'] != null) {
      final v = json['image'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      image = arr0;
    }
    countItems = json['count_items']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['created_at'] = createdAt;
    if (image != null) {
      final v = image;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['image'] = arr0;
    }
    data['count_items'] = countItems;
    return data;
  }
}

class WishlistModel {
/*
{
  "success": true,
  "message": "ok",
  "data": [
    {
      "id": 4,
      "name": "ehe7",
      "created_at": "17 April 2024 16:23",
      "image": [
        "https://sibima.sgp1.cdn.digitaloceanspaces.com/no-image.png"
      ],
      "count_items": 2
    }
  ]
}
*/

  bool? success;
  String? message;
  List<WishlistModelData?>? data;

  WishlistModel({
    this.success,
    this.message,
    this.data,
  });
  WishlistModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WishlistModelData>[];
      v.forEach((v) {
        arr0.add(WishlistModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
