///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChatBuyerModelDataSeller {
/*
{
  "Buat": "2024-07-16 13:51:35",
  "isichat": "halo",
  "PengirimID": "148",
  "PenerimaID": "196",
  "dibaca": "0",
  "ID": "196",
  "email": "atriaseller@gmail.com",
  "password": "$2y$10$lpTWe8HzjIWOgtHXLxFrqu3OXZPuT2ZYAcNucXUsKG9mnI03WL5Eq",
  "jenis": "SELLER",
  "aktif": "1",
  "hapus": "0",
  "kelengkapan": "1",
  "nama_perusahaan": "",
  "alamat": "",
  "tagging": "",
  "kegiatan_usaha": "",
  "pemilik_toko": "",
  "firstname": "Atria",
  "lastname": "Seller",
  "HakAksesID": null,
  "status_pilihalamat": "0",
  "telp": null,
  "kabkota": null,
  "subdit_id": null
}
*/

  String? Buat;
  String? isichat;
  String? PengirimID;
  String? PenerimaID;
  String? dibaca;
  String? ID;
  String? email;
  String? password;
  String? jenis;
  String? aktif;
  String? hapus;
  String? kelengkapan;
  String? namaPerusahaan;
  String? alamat;
  String? tagging;
  String? kegiatanUsaha;
  String? pemilikToko;
  String? firstname;
  String? lastname;
  String? HakAksesID;
  String? statusPilihalamat;
  String? telp;
  String? kabkota;
  String? subditId;

  ChatBuyerModelDataSeller({
    this.Buat,
    this.isichat,
    this.PengirimID,
    this.PenerimaID,
    this.dibaca,
    this.ID,
    this.email,
    this.password,
    this.jenis,
    this.aktif,
    this.hapus,
    this.kelengkapan,
    this.namaPerusahaan,
    this.alamat,
    this.tagging,
    this.kegiatanUsaha,
    this.pemilikToko,
    this.firstname,
    this.lastname,
    this.HakAksesID,
    this.statusPilihalamat,
    this.telp,
    this.kabkota,
    this.subditId,
  });
  ChatBuyerModelDataSeller.fromJson(Map<String, dynamic> json) {
    Buat = json['Buat']?.toString();
    isichat = json['isichat']?.toString();
    PengirimID = json['PengirimID']?.toString();
    PenerimaID = json['PenerimaID']?.toString();
    dibaca = json['dibaca']?.toString();
    ID = json['ID']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    jenis = json['jenis']?.toString();
    aktif = json['aktif']?.toString();
    hapus = json['hapus']?.toString();
    kelengkapan = json['kelengkapan']?.toString();
    namaPerusahaan = json['nama_perusahaan']?.toString();
    alamat = json['alamat']?.toString();
    tagging = json['tagging']?.toString();
    kegiatanUsaha = json['kegiatan_usaha']?.toString();
    pemilikToko = json['pemilik_toko']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    HakAksesID = json['HakAksesID']?.toString();
    statusPilihalamat = json['status_pilihalamat']?.toString();
    telp = json['telp']?.toString();
    kabkota = json['kabkota']?.toString();
    subditId = json['subdit_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Buat'] = Buat;
    data['isichat'] = isichat;
    data['PengirimID'] = PengirimID;
    data['PenerimaID'] = PenerimaID;
    data['dibaca'] = dibaca;
    data['ID'] = ID;
    data['email'] = email;
    data['password'] = password;
    data['jenis'] = jenis;
    data['aktif'] = aktif;
    data['hapus'] = hapus;
    data['kelengkapan'] = kelengkapan;
    data['nama_perusahaan'] = namaPerusahaan;
    data['alamat'] = alamat;
    data['tagging'] = tagging;
    data['kegiatan_usaha'] = kegiatanUsaha;
    data['pemilik_toko'] = pemilikToko;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['HakAksesID'] = HakAksesID;
    data['status_pilihalamat'] = statusPilihalamat;
    data['telp'] = telp;
    data['kabkota'] = kabkota;
    data['subdit_id'] = subditId;
    return data;
  }
}

class ChatBuyerModelData {
/*
{
  "seller": [
    {
      "Buat": "2024-07-16 13:51:35",
      "isichat": "halo",
      "PengirimID": "148",
      "PenerimaID": "196",
      "dibaca": "0",
      "ID": "196",
      "email": "atriaseller@gmail.com",
      "password": "$2y$10$lpTWe8HzjIWOgtHXLxFrqu3OXZPuT2ZYAcNucXUsKG9mnI03WL5Eq",
      "jenis": "SELLER",
      "aktif": "1",
      "hapus": "0",
      "kelengkapan": "1",
      "nama_perusahaan": "",
      "alamat": "",
      "tagging": "",
      "kegiatan_usaha": "",
      "pemilik_toko": "",
      "firstname": "Atria",
      "lastname": "Seller",
      "HakAksesID": null,
      "status_pilihalamat": "0",
      "telp": null,
      "kabkota": null,
      "subdit_id": null
    }
  ]
}
*/

  List<ChatBuyerModelDataSeller?>? seller;

  ChatBuyerModelData({
    this.seller,
  });
  ChatBuyerModelData.fromJson(Map<String, dynamic> json) {
    if (json['seller'] != null) {
      final v = json['seller'];
      final arr0 = <ChatBuyerModelDataSeller>[];
      v.forEach((v) {
        arr0.add(ChatBuyerModelDataSeller.fromJson(v));
      });
      seller = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (seller != null) {
      final v = seller;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['seller'] = arr0;
    }
    return data;
  }
}

class ChatBuyerModel {
/*
{
  "result": "success",
  "data": {
    "seller": [
      {
        "Buat": "2024-07-16 13:51:35",
        "isichat": "halo",
        "PengirimID": "148",
        "PenerimaID": "196",
        "dibaca": "0",
        "ID": "196",
        "email": "atriaseller@gmail.com",
        "password": "$2y$10$lpTWe8HzjIWOgtHXLxFrqu3OXZPuT2ZYAcNucXUsKG9mnI03WL5Eq",
        "jenis": "SELLER",
        "aktif": "1",
        "hapus": "0",
        "kelengkapan": "1",
        "nama_perusahaan": "",
        "alamat": "",
        "tagging": "",
        "kegiatan_usaha": "",
        "pemilik_toko": "",
        "firstname": "Atria",
        "lastname": "Seller",
        "HakAksesID": null,
        "status_pilihalamat": "0",
        "telp": null,
        "kabkota": null,
        "subdit_id": null
      }
    ]
  }
}
*/

  String? result;
  ChatBuyerModelData? data;

  ChatBuyerModel({
    this.result,
    this.data,
  });
  ChatBuyerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? ChatBuyerModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
