///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AkunSayaBuyerModelData {
/*
{
  "total_pesanan": "6",
  "total_pesanan_price": "58950",
  "pesanan_ditolak": "0",
  "pesanan_ditolak_price": "",
  "pesanan_baru": "5",
  "pesanan_baru_price": "58800",
  "pesanan_diterima": "1",
  "pesanan_diterima_price": "150",
  "pesanan_dikirim": "0",
  "pesanan_dikirim_price": "",
  "barang_diterima": 0,
  "tagihan": 0,
  "siap_tagih": 0,
  "proses_pembayaran": 0,
  "barang_diterima_price": 0,
  "tagihan_price": 0,
  "siap_tagih_price": 0,
  "proses_pembayaran_price": 0,
  "telah_dibayar": "0",
  "telah_dibayar_price": 0
} 
*/

  String? totalPesanan;
  String? totalPesananPrice;
  String? pesananDitolak;
  String? pesananDitolakPrice;
  String? pesananBaru;
  String? pesananBaruPrice;
  String? pesananDiterima;
  String? pesananDiterimaPrice;
  String? pesananDikirim;
  String? pesananDikirimPrice;
  int? barangDiterima;
  int? tagihan;
  int? siapTagih;
  int? prosesPembayaran;
  int? barangDiterimaPrice;
  int? tagihanPrice;
  int? siapTagihPrice;
  int? prosesPembayaranPrice;
  String? telahDibayar;
  int? telahDibayarPrice;

  AkunSayaBuyerModelData({
    this.totalPesanan,
    this.totalPesananPrice,
    this.pesananDitolak,
    this.pesananDitolakPrice,
    this.pesananBaru,
    this.pesananBaruPrice,
    this.pesananDiterima,
    this.pesananDiterimaPrice,
    this.pesananDikirim,
    this.pesananDikirimPrice,
    this.barangDiterima,
    this.tagihan,
    this.siapTagih,
    this.prosesPembayaran,
    this.barangDiterimaPrice,
    this.tagihanPrice,
    this.siapTagihPrice,
    this.prosesPembayaranPrice,
    this.telahDibayar,
    this.telahDibayarPrice,
  });
  AkunSayaBuyerModelData.fromJson(Map<String, dynamic> json) {
    totalPesanan = json['total_pesanan']?.toString();
    totalPesananPrice = json['total_pesanan_price']?.toString();
    pesananDitolak = json['pesanan_ditolak']?.toString();
    pesananDitolakPrice = json['pesanan_ditolak_price']?.toString();
    pesananBaru = json['pesanan_baru']?.toString();
    pesananBaruPrice = json['pesanan_baru_price']?.toString();
    pesananDiterima = json['pesanan_diterima']?.toString();
    pesananDiterimaPrice = json['pesanan_diterima_price']?.toString();
    pesananDikirim = json['pesanan_dikirim']?.toString();
    pesananDikirimPrice = json['pesanan_dikirim_price']?.toString();
    barangDiterima = json['barang_diterima']?.toInt();
    tagihan = json['tagihan']?.toInt();
    siapTagih = json['siap_tagih']?.toInt();
    prosesPembayaran = json['proses_pembayaran']?.toInt();
    barangDiterimaPrice = json['barang_diterima_price']?.toInt();
    tagihanPrice = json['tagihan_price']?.toInt();
    siapTagihPrice = json['siap_tagih_price']?.toInt();
    prosesPembayaranPrice = json['proses_pembayaran_price']?.toInt();
    telahDibayar = json['telah_dibayar']?.toString();
    telahDibayarPrice = json['telah_dibayar_price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_pesanan'] = totalPesanan;
    data['total_pesanan_price'] = totalPesananPrice;
    data['pesanan_ditolak'] = pesananDitolak;
    data['pesanan_ditolak_price'] = pesananDitolakPrice;
    data['pesanan_baru'] = pesananBaru;
    data['pesanan_baru_price'] = pesananBaruPrice;
    data['pesanan_diterima'] = pesananDiterima;
    data['pesanan_diterima_price'] = pesananDiterimaPrice;
    data['pesanan_dikirim'] = pesananDikirim;
    data['pesanan_dikirim_price'] = pesananDikirimPrice;
    data['barang_diterima'] = barangDiterima;
    data['tagihan'] = tagihan;
    data['siap_tagih'] = siapTagih;
    data['proses_pembayaran'] = prosesPembayaran;
    data['barang_diterima_price'] = barangDiterimaPrice;
    data['tagihan_price'] = tagihanPrice;
    data['siap_tagih_price'] = siapTagihPrice;
    data['proses_pembayaran_price'] = prosesPembayaranPrice;
    data['telah_dibayar'] = telahDibayar;
    data['telah_dibayar_price'] = telahDibayarPrice;
    return data;
  }
}

class AkunSayaBuyerModel {
/*
{
  "result": "success",
  "data": {
    "total_pesanan": "6",
    "total_pesanan_price": "58950",
    "pesanan_ditolak": "0",
    "pesanan_ditolak_price": "",
    "pesanan_baru": "5",
    "pesanan_baru_price": "58800",
    "pesanan_diterima": "1",
    "pesanan_diterima_price": "150",
    "pesanan_dikirim": "0",
    "pesanan_dikirim_price": "",
    "barang_diterima": 0,
    "tagihan": 0,
    "siap_tagih": 0,
    "proses_pembayaran": 0,
    "barang_diterima_price": 0,
    "tagihan_price": 0,
    "siap_tagih_price": 0,
    "proses_pembayaran_price": 0,
    "telah_dibayar": "0",
    "telah_dibayar_price": 0
  }
} 
*/

  String? result;
  AkunSayaBuyerModelData? data;

  AkunSayaBuyerModel({
    this.result,
    this.data,
  });
  AkunSayaBuyerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null) ? AkunSayaBuyerModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
