///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubditModelData {
/*
{
  "ID": "49",
  "nomor_permintaan": "8/DPP-SP/X/2023",
  "jumlah_prk": "1",
  "nilai_prk": "229823000",
  "IDPrk": "4451",
  "BuyerID": "148",
  "status": "1",
  "sisa": "214814100",
  "subdit_id": "0",
  "description": "{\"id\":4451,\"nomor\":\"8/DPP-SP/X/2023\",\"tanggal\":\"2023-10-08T17:00:00Z\",\"catatan\":null,\"subjumlah\":229823000,\"ppn\":null,\"jumlah\":null,\"dibulatkan\":null,\"apprv1by\":\"8007011JA\",\"apprv1bynama\":\"HENDRA HARTANTO EFENDI\",\"apprv1byjabt\":\"DIREKTUR UTAMA (N)\",\"apprv2by\":\"7093272JA\",\"apprv2bynama\":\"SLAMET SUPRIYANTO\",\"apprv2byjabt\":\"DIREKTUR PEMASARAN DAN OPERASI (N)\",\"acknow1by\":\"8310108KP\",\"acknow1bynama\":\"DEDY TRIMARTHA WARDANA\",\"acknow1byjabt\":\"MANAJER KEUANGAN\",\"submit1by\":\"8312536KP\",\"submit1bynama\":\"SUPRIYANTO\",\"submit1byjabt\":\"MANAJER OPERASI (N)\",\"sudahpa\":false,\"detils\":null}",
  "subdit_name": null
}
*/

  String? ID;
  String? nomorPermintaan;
  String? jumlahPrk;
  String? nilaiPrk;
  String? IDPrk;
  String? BuyerID;
  String? status;
  String? sisa;
  String? subditId;
  String? description;
  String? subditName;

  SubditModelData({
    this.ID,
    this.nomorPermintaan,
    this.jumlahPrk,
    this.nilaiPrk,
    this.IDPrk,
    this.BuyerID,
    this.status,
    this.sisa,
    this.subditId,
    this.description,
    this.subditName,
  });
  SubditModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nomorPermintaan = json['nomor_permintaan']?.toString();
    jumlahPrk = json['jumlah_prk']?.toString();
    nilaiPrk = json['nilai_prk']?.toString();
    IDPrk = json['IDPrk']?.toString();
    BuyerID = json['BuyerID']?.toString();
    status = json['status']?.toString();
    sisa = json['sisa']?.toString();
    subditId = json['subdit_id']?.toString();
    description = json['description']?.toString();
    subditName = json['subdit_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nomor_permintaan'] = nomorPermintaan;
    data['jumlah_prk'] = jumlahPrk;
    data['nilai_prk'] = nilaiPrk;
    data['IDPrk'] = IDPrk;
    data['BuyerID'] = BuyerID;
    data['status'] = status;
    data['sisa'] = sisa;
    data['subdit_id'] = subditId;
    data['description'] = description;
    data['subdit_name'] = subditName;
    return data;
  }
}

class SubditModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "49",
      "nomor_permintaan": "8/DPP-SP/X/2023",
      "jumlah_prk": "1",
      "nilai_prk": "229823000",
      "IDPrk": "4451",
      "BuyerID": "148",
      "status": "1",
      "sisa": "214814100",
      "subdit_id": "0",
      "description": "{\"id\":4451,\"nomor\":\"8/DPP-SP/X/2023\",\"tanggal\":\"2023-10-08T17:00:00Z\",\"catatan\":null,\"subjumlah\":229823000,\"ppn\":null,\"jumlah\":null,\"dibulatkan\":null,\"apprv1by\":\"8007011JA\",\"apprv1bynama\":\"HENDRA HARTANTO EFENDI\",\"apprv1byjabt\":\"DIREKTUR UTAMA (N)\",\"apprv2by\":\"7093272JA\",\"apprv2bynama\":\"SLAMET SUPRIYANTO\",\"apprv2byjabt\":\"DIREKTUR PEMASARAN DAN OPERASI (N)\",\"acknow1by\":\"8310108KP\",\"acknow1bynama\":\"DEDY TRIMARTHA WARDANA\",\"acknow1byjabt\":\"MANAJER KEUANGAN\",\"submit1by\":\"8312536KP\",\"submit1bynama\":\"SUPRIYANTO\",\"submit1byjabt\":\"MANAJER OPERASI (N)\",\"sudahpa\":false,\"detils\":null}",
      "subdit_name": null
    }
  ]
}
*/

  String? result;
  List<SubditModelData?>? data;

  SubditModel({
    this.result,
    this.data,
  });
  SubditModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SubditModelData>[];
      v.forEach((v) {
        arr0.add(SubditModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
