///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BuyBuyerModelMessages {
/*
{
  "success": "Pembelian berhasil dilakukan",
  "IDTemp": 106
}
*/

  String? success;
  int? IDTemp;

  BuyBuyerModelMessages({
    this.success,
    this.IDTemp,
  });
  BuyBuyerModelMessages.fromJson(Map<String, dynamic> json) {
    success = json['success']?.toString();
    IDTemp = json['IDTemp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['IDTemp'] = IDTemp;
    return data;
  }
}

class BuyBuyerModel {
/*
{
  "status": "success",
  "error": "null",
  "messages": {
    "success": "Pembelian berhasil dilakukan",
    "IDTemp": 106
  }
}
*/

  String? status;
  String? error;
  BuyBuyerModelMessages? messages;

  BuyBuyerModel({
    this.status,
    this.error,
    this.messages,
  });
  BuyBuyerModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    error = json['error']?.toString();
    messages = (json['messages'] != null) ? BuyBuyerModelMessages.fromJson(json['messages']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['error'] = error;
    if (messages != null) {
      data['messages'] = messages!.toJson();
    }
    return data;
  }
}
