///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutModelDataAvailablePaylaters {
/*
{
  "paylater_type": "KREDIVO"
} 
*/

  String? paylaterType;

  CheckoutModelDataAvailablePaylaters({
    this.paylaterType,
  });
  CheckoutModelDataAvailablePaylaters.fromJson(Map<String, dynamic> json) {
    paylaterType = json['paylater_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['paylater_type'] = paylaterType;
    return data;
  }
}

class CheckoutModelDataAvailableDirectDebits {
/*
{
  "direct_debit_type": "DD_BRI"
} 
*/

  String? directDebitType;

  CheckoutModelDataAvailableDirectDebits({
    this.directDebitType,
  });
  CheckoutModelDataAvailableDirectDebits.fromJson(Map<String, dynamic> json) {
    directDebitType = json['direct_debit_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['direct_debit_type'] = directDebitType;
    return data;
  }
}

class CheckoutModelDataAvailableQrCodes {
/*
{
  "qr_code_type": "QRIS"
} 
*/

  String? qrCodeType;

  CheckoutModelDataAvailableQrCodes({
    this.qrCodeType,
  });
  CheckoutModelDataAvailableQrCodes.fromJson(Map<String, dynamic> json) {
    qrCodeType = json['qr_code_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qr_code_type'] = qrCodeType;
    return data;
  }
}

class CheckoutModelDataAvailableEwallets {
/*
{
  "ewallet_type": "SHOPEEPAY"
} 
*/

  String? ewalletType;

  CheckoutModelDataAvailableEwallets({
    this.ewalletType,
  });
  CheckoutModelDataAvailableEwallets.fromJson(Map<String, dynamic> json) {
    ewalletType = json['ewallet_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ewallet_type'] = ewalletType;
    return data;
  }
}

class CheckoutModelDataAvailableRetailOutlets {
/*
{
  "retail_outlet_name": "ALFAMART"
} 
*/

  String? retailOutletName;

  CheckoutModelDataAvailableRetailOutlets({
    this.retailOutletName,
  });
  CheckoutModelDataAvailableRetailOutlets.fromJson(Map<String, dynamic> json) {
    retailOutletName = json['retail_outlet_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['retail_outlet_name'] = retailOutletName;
    return data;
  }
}

class CheckoutModelDataAvailableBanks {
/*
{
  "bank_code": "MANDIRI",
  "collection_type": "POOL",
  "bank_branch": "Virtual Account",
  "account_holder_name": "SIBIMA BERKARYA MANDIRI",
  "transfer_amount": 52083750
} 
*/

  String? bankCode;
  String? collectionType;
  String? bankBranch;
  String? accountHolderName;
  int? transferAmount;

  CheckoutModelDataAvailableBanks({
    this.bankCode,
    this.collectionType,
    this.bankBranch,
    this.accountHolderName,
    this.transferAmount,
  });
  CheckoutModelDataAvailableBanks.fromJson(Map<String, dynamic> json) {
    bankCode = json['bank_code']?.toString();
    collectionType = json['collection_type']?.toString();
    bankBranch = json['bank_branch']?.toString();
    accountHolderName = json['account_holder_name']?.toString();
    transferAmount = json['transfer_amount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bank_code'] = bankCode;
    data['collection_type'] = collectionType;
    data['bank_branch'] = bankBranch;
    data['account_holder_name'] = accountHolderName;
    data['transfer_amount'] = transferAmount;
    return data;
  }
}

class CheckoutModelData {
/*
{
  "id": "661f4a994701c1156a3a880b",
  "external_id": "test1234",
  "user_id": "660e342e9da94936972f38f5",
  "description": "Test Invoice",
  "status": "PENDING",
  "merchant_name": "Sibima Berkarya Mandiri",
  "merchant_profile_picture_url": "https://xnd-merchant-logos.s3.amazonaws.com/business/production/660e342e9da94936972f38f5-1712207072296.png",
  "amount": 52083750,
  "expiry_date": "2024-04-19T04:05:45+00:00",
  "invoice_url": "https://checkout-staging.xendit.co/v2/661f4a994701c1156a3a880b",
  "available_banks": [
    {
      "bank_code": "MANDIRI",
      "collection_type": "POOL",
      "bank_branch": "Virtual Account",
      "account_holder_name": "SIBIMA BERKARYA MANDIRI",
      "transfer_amount": 52083750
    }
  ],
  "available_retail_outlets": [
    {
      "retail_outlet_name": "ALFAMART"
    }
  ],
  "available_ewallets": [
    {
      "ewallet_type": "SHOPEEPAY"
    }
  ],
  "available_qr_codes": [
    {
      "qr_code_type": "QRIS"
    }
  ],
  "available_direct_debits": [
    {
      "direct_debit_type": "DD_BRI"
    }
  ],
  "available_paylaters": [
    {
      "paylater_type": "KREDIVO"
    }
  ],
  "should_exclude_credit_card": false,
  "should_send_email": false,
  "created": "2024-04-17T04:05:45+00:00",
  "updated": "2024-04-17T04:05:45+00:00",
  "currency": "IDR",
  "reminder_date": "2024-04-18T04:05:45+00:00",
  "order_id": 21
} 
*/

  String? id;
  String? externalId;
  String? userId;
  String? description;
  String? status;
  String? merchantName;
  String? merchantProfilePictureUrl;
  int? amount;
  String? expiryDate;
  String? invoiceUrl;
  List<CheckoutModelDataAvailableBanks?>? availableBanks;
  List<CheckoutModelDataAvailableRetailOutlets?>? availableRetailOutlets;
  List<CheckoutModelDataAvailableEwallets?>? availableEwallets;
  List<CheckoutModelDataAvailableQrCodes?>? availableQrCodes;
  List<CheckoutModelDataAvailableDirectDebits?>? availableDirectDebits;
  List<CheckoutModelDataAvailablePaylaters?>? availablePaylaters;
  bool? shouldExcludeCreditCard;
  bool? shouldSendEmail;
  String? created;
  String? updated;
  String? currency;
  String? reminderDate;
  int? orderId;

  CheckoutModelData({
    this.id,
    this.externalId,
    this.userId,
    this.description,
    this.status,
    this.merchantName,
    this.merchantProfilePictureUrl,
    this.amount,
    this.expiryDate,
    this.invoiceUrl,
    this.availableBanks,
    this.availableRetailOutlets,
    this.availableEwallets,
    this.availableQrCodes,
    this.availableDirectDebits,
    this.availablePaylaters,
    this.shouldExcludeCreditCard,
    this.shouldSendEmail,
    this.created,
    this.updated,
    this.currency,
    this.reminderDate,
    this.orderId,
  });
  CheckoutModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    externalId = json['external_id']?.toString();
    userId = json['user_id']?.toString();
    description = json['description']?.toString();
    status = json['status']?.toString();
    merchantName = json['merchant_name']?.toString();
    merchantProfilePictureUrl =
        json['merchant_profile_picture_url']?.toString();
    amount = json['amount']?.toInt();
    expiryDate = json['expiry_date']?.toString();
    invoiceUrl = json['invoice_url']?.toString();
    if (json['available_banks'] != null) {
      final v = json['available_banks'];
      final arr0 = <CheckoutModelDataAvailableBanks>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailableBanks.fromJson(v));
      });
      availableBanks = arr0;
    }
    if (json['available_retail_outlets'] != null) {
      final v = json['available_retail_outlets'];
      final arr0 = <CheckoutModelDataAvailableRetailOutlets>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailableRetailOutlets.fromJson(v));
      });
      availableRetailOutlets = arr0;
    }
    if (json['available_ewallets'] != null) {
      final v = json['available_ewallets'];
      final arr0 = <CheckoutModelDataAvailableEwallets>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailableEwallets.fromJson(v));
      });
      availableEwallets = arr0;
    }
    if (json['available_qr_codes'] != null) {
      final v = json['available_qr_codes'];
      final arr0 = <CheckoutModelDataAvailableQrCodes>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailableQrCodes.fromJson(v));
      });
      availableQrCodes = arr0;
    }
    if (json['available_direct_debits'] != null) {
      final v = json['available_direct_debits'];
      final arr0 = <CheckoutModelDataAvailableDirectDebits>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailableDirectDebits.fromJson(v));
      });
      availableDirectDebits = arr0;
    }
    if (json['available_paylaters'] != null) {
      final v = json['available_paylaters'];
      final arr0 = <CheckoutModelDataAvailablePaylaters>[];
      v.forEach((v) {
        arr0.add(CheckoutModelDataAvailablePaylaters.fromJson(v));
      });
      availablePaylaters = arr0;
    }
    shouldExcludeCreditCard = json['should_exclude_credit_card'];
    shouldSendEmail = json['should_send_email'];
    created = json['created']?.toString();
    updated = json['updated']?.toString();
    currency = json['currency']?.toString();
    reminderDate = json['reminder_date']?.toString();
    orderId = json['order_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['external_id'] = externalId;
    data['user_id'] = userId;
    data['description'] = description;
    data['status'] = status;
    data['merchant_name'] = merchantName;
    data['merchant_profile_picture_url'] = merchantProfilePictureUrl;
    data['amount'] = amount;
    data['expiry_date'] = expiryDate;
    data['invoice_url'] = invoiceUrl;
    if (availableBanks != null) {
      final v = availableBanks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_banks'] = arr0;
    }
    if (availableRetailOutlets != null) {
      final v = availableRetailOutlets;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_retail_outlets'] = arr0;
    }
    if (availableEwallets != null) {
      final v = availableEwallets;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_ewallets'] = arr0;
    }
    if (availableQrCodes != null) {
      final v = availableQrCodes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_qr_codes'] = arr0;
    }
    if (availableDirectDebits != null) {
      final v = availableDirectDebits;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_direct_debits'] = arr0;
    }
    if (availablePaylaters != null) {
      final v = availablePaylaters;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['available_paylaters'] = arr0;
    }
    data['should_exclude_credit_card'] = shouldExcludeCreditCard;
    data['should_send_email'] = shouldSendEmail;
    data['created'] = created;
    data['updated'] = updated;
    data['currency'] = currency;
    data['reminder_date'] = reminderDate;
    data['order_id'] = orderId;
    return data;
  }
}

class CheckoutModel {
/*
{
  "success": true,
  "message": "Data berhasil disimpan",
  "data": {
    "id": "661f4a994701c1156a3a880b",
    "external_id": "test1234",
    "user_id": "660e342e9da94936972f38f5",
    "description": "Test Invoice",
    "status": "PENDING",
    "merchant_name": "Sibima Berkarya Mandiri",
    "merchant_profile_picture_url": "https://xnd-merchant-logos.s3.amazonaws.com/business/production/660e342e9da94936972f38f5-1712207072296.png",
    "amount": 52083750,
    "expiry_date": "2024-04-19T04:05:45+00:00",
    "invoice_url": "https://checkout-staging.xendit.co/v2/661f4a994701c1156a3a880b",
    "available_banks": [
      {
        "bank_code": "MANDIRI",
        "collection_type": "POOL",
        "bank_branch": "Virtual Account",
        "account_holder_name": "SIBIMA BERKARYA MANDIRI",
        "transfer_amount": 52083750
      }
    ],
    "available_retail_outlets": [
      {
        "retail_outlet_name": "ALFAMART"
      }
    ],
    "available_ewallets": [
      {
        "ewallet_type": "SHOPEEPAY"
      }
    ],
    "available_qr_codes": [
      {
        "qr_code_type": "QRIS"
      }
    ],
    "available_direct_debits": [
      {
        "direct_debit_type": "DD_BRI"
      }
    ],
    "available_paylaters": [
      {
        "paylater_type": "KREDIVO"
      }
    ],
    "should_exclude_credit_card": false,
    "should_send_email": false,
    "created": "2024-04-17T04:05:45+00:00",
    "updated": "2024-04-17T04:05:45+00:00",
    "currency": "IDR",
    "reminder_date": "2024-04-18T04:05:45+00:00",
    "order_id": 21
  }
} 
*/

  bool? success;
  String? message;
  CheckoutModelData? data;

  CheckoutModel({
    this.success,
    this.message,
    this.data,
  });
  CheckoutModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null)
        ? CheckoutModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
