///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RiwayatNegoModelData {
/*
{
  "ID": "852",
  "ProdukID": "1188",
  "BuyerID": "148",
  "qty": "1",
  "harga_awal": "500000",
  "harga_akhir": "450000",
  "nego": "450000",
  "nego2": "null",
  "nego3": "null",
  "status_nego": "1",
  "hapus": "0",
  "status": "1",
  "catatan": "",
  "nama": "Palugada",
  "foto": "https://mspeed.erdata.id/produk/PaluAlatTukangBangunan.jpg",
  "SellerID": "203",
  "fixprice": "450000",
  "fixstatus": "Nego Disetujui"
}
*/

  String? ID;
  String? ProdukID;
  String? BuyerID;
  String? qty;
  String? hargaAwal;
  String? hargaAkhir;
  String? nego;
  String? nego2;
  String? nego3;
  String? statusNego;
  String? hapus;
  String? status;
  String? catatan;
  String? nama;
  String? foto;
  String? SellerID;
  String? fixprice;
  String? fixstatus;

  RiwayatNegoModelData({
    this.ID,
    this.ProdukID,
    this.BuyerID,
    this.qty,
    this.hargaAwal,
    this.hargaAkhir,
    this.nego,
    this.nego2,
    this.nego3,
    this.statusNego,
    this.hapus,
    this.status,
    this.catatan,
    this.nama,
    this.foto,
    this.SellerID,
    this.fixprice,
    this.fixstatus,
  });
  RiwayatNegoModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    ProdukID = json['ProdukID']?.toString();
    BuyerID = json['BuyerID']?.toString();
    qty = json['qty']?.toString();
    hargaAwal = json['harga_awal']?.toString();
    hargaAkhir = json['harga_akhir']?.toString();
    nego = json['nego']?.toString();
    nego2 = json['nego2']?.toString();
    nego3 = json['nego3']?.toString();
    statusNego = json['status_nego']?.toString();
    hapus = json['hapus']?.toString();
    status = json['status']?.toString();
    catatan = json['catatan']?.toString();
    nama = json['nama']?.toString();
    foto = json['foto']?.toString();
    SellerID = json['SellerID']?.toString();
    fixprice = json['fixprice']?.toString();
    fixstatus = json['fixstatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['ProdukID'] = ProdukID;
    data['BuyerID'] = BuyerID;
    data['qty'] = qty;
    data['harga_awal'] = hargaAwal;
    data['harga_akhir'] = hargaAkhir;
    data['nego'] = nego;
    data['nego2'] = nego2;
    data['nego3'] = nego3;
    data['status_nego'] = statusNego;
    data['hapus'] = hapus;
    data['status'] = status;
    data['catatan'] = catatan;
    data['nama'] = nama;
    data['foto'] = foto;
    data['SellerID'] = SellerID;
    data['fixprice'] = fixprice;
    data['fixstatus'] = fixstatus;
    return data;
  }
}

class RiwayatNegoModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "852",
      "ProdukID": "1188",
      "BuyerID": "148",
      "qty": "1",
      "harga_awal": "500000",
      "harga_akhir": "450000",
      "nego": "450000",
      "nego2": "null",
      "nego3": "null",
      "status_nego": "1",
      "hapus": "0",
      "status": "1",
      "catatan": "",
      "nama": "Palugada",
      "foto": "https://mspeed.erdata.id/produk/PaluAlatTukangBangunan.jpg",
      "SellerID": "203",
      "fixprice": "450000",
      "fixstatus": "Nego Disetujui"
    }
  ]
}
*/

  String? result;
  List<RiwayatNegoModelData?>? data;

  RiwayatNegoModel({
    this.result,
    this.data,
  });
  RiwayatNegoModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RiwayatNegoModelData>[];
      v.forEach((v) {
        arr0.add(RiwayatNegoModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
