///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShoppingCartModelPajak {
/*
{
  "id": "1",
  "nama": "Pajak",
  "persentase": "11"
} 
*/

  String? id;
  String? nama;
  String? persentase;

  ShoppingCartModelPajak({
    this.id,
    this.nama,
    this.persentase,
  });
  ShoppingCartModelPajak.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    nama = json['nama']?.toString();
    persentase = json['persentase']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama'] = nama;
    data['persentase'] = persentase;
    return data;
  }
}

class ShoppingCartModelDataDetail {
/*
{
  "ID": "975",
  "IDProduk": "1204",
  "SellerID": "196",
  "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
  "nama": "BOR LISTRIK THERMAL",
  "harga_sebelum_nego": "2850000",
  "harga_awal": "2650000",
  "harga_akhir": 5300000,
  "qty": "2",
  "stok": "8",
  "nego": "2500000",
  "nego2": "2700000",
  "nego3": "2650000",
  "status_nego": "1",
  "ProdukID": "1204",
  "namaseller": "Atria Seller",
  "catatan": "",
  "fixprice": "2650000",
  "fixstatus": "Nego Disetujui"
}
*/

  String? ID;
  String? IDProduk;
  String? SellerID;
  String? foto;
  String? nama;
  String? hargaSebelumNego;
  String? hargaAwal;
  int? hargaAkhir;
  String? qty;
  String? stok;
  String? nego;
  String? nego2;
  String? nego3;
  String? statusNego;
  String? ProdukID;
  String? namaseller;
  String? catatan;
  String? fixprice;
  String? fixstatus;

  ShoppingCartModelDataDetail({
    this.ID,
    this.IDProduk,
    this.SellerID,
    this.foto,
    this.nama,
    this.hargaSebelumNego,
    this.hargaAwal,
    this.hargaAkhir,
    this.qty,
    this.stok,
    this.nego,
    this.nego2,
    this.nego3,
    this.statusNego,
    this.ProdukID,
    this.namaseller,
    this.catatan,
    this.fixprice,
    this.fixstatus,
  });
  ShoppingCartModelDataDetail.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    IDProduk = json['IDProduk']?.toString();
    SellerID = json['SellerID']?.toString();
    foto = json['foto']?.toString();
    nama = json['nama']?.toString();
    hargaSebelumNego = json['harga_sebelum_nego']?.toString();
    hargaAwal = json['harga_awal']?.toString();
    hargaAkhir = json['harga_akhir']?.toInt();
    qty = json['qty']?.toString();
    stok = json['stok']?.toString();
    nego = json['nego']?.toString();
    nego2 = json['nego2']?.toString();
    nego3 = json['nego3']?.toString();
    statusNego = json['status_nego']?.toString();
    ProdukID = json['ProdukID']?.toString();
    namaseller = json['namaseller']?.toString();
    catatan = json['catatan']?.toString();
    fixprice = json['fixprice']?.toString();
    fixstatus = json['fixstatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['IDProduk'] = IDProduk;
    data['SellerID'] = SellerID;
    data['foto'] = foto;
    data['nama'] = nama;
    data['harga_sebelum_nego'] = hargaSebelumNego;
    data['harga_awal'] = hargaAwal;
    data['harga_akhir'] = hargaAkhir;
    data['qty'] = qty;
    data['stok'] = stok;
    data['nego'] = nego;
    data['nego2'] = nego2;
    data['nego3'] = nego3;
    data['status_nego'] = statusNego;
    data['ProdukID'] = ProdukID;
    data['namaseller'] = namaseller;
    data['catatan'] = catatan;
    data['fixprice'] = fixprice;
    data['fixstatus'] = fixstatus;
    return data;
  }
}

class ShoppingCartModelData {
/*
{
  "SellerID": "196",
  "namaseller": "Atria Seller",
  "detail": [
    {
      "ID": "975",
      "IDProduk": "1204",
      "SellerID": "196",
      "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
      "nama": "BOR LISTRIK THERMAL",
      "harga_sebelum_nego": "2850000",
      "harga_awal": "2650000",
      "harga_akhir": 5300000,
      "qty": "2",
      "stok": "8",
      "nego": "2500000",
      "nego2": "2700000",
      "nego3": "2650000",
      "status_nego": "1",
      "ProdukID": "1204",
      "namaseller": "Atria Seller",
      "catatan": "",
      "fixprice": "2650000",
      "fixstatus": "Nego Disetujui"
    }
  ],
  "total": 5150000
}
*/

  String? SellerID;
  String? namaseller;
  List<ShoppingCartModelDataDetail?>? detail;
  int? total;

  ShoppingCartModelData({
    this.SellerID,
    this.namaseller,
    this.detail,
    this.total,
  });
  ShoppingCartModelData.fromJson(Map<String, dynamic> json) {
    SellerID = json['SellerID']?.toString();
    namaseller = json['namaseller']?.toString();
    if (json['detail'] != null) {
      final v = json['detail'];
      final arr0 = <ShoppingCartModelDataDetail>[];
      v.forEach((v) {
        arr0.add(ShoppingCartModelDataDetail.fromJson(v));
      });
      detail = arr0;
    }
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['SellerID'] = SellerID;
    data['namaseller'] = namaseller;
    if (detail != null) {
      final v = detail;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail'] = arr0;
    }
    data['total'] = total;
    return data;
  }
}

class ShoppingCartModel {
/*
{
  "result": "success",
  "data": [
    {
      "SellerID": "196",
      "namaseller": "Atria Seller",
      "detail": [
        {
          "ID": "975",
          "IDProduk": "1204",
          "SellerID": "196",
          "foto": "https://mspeed.erdata.id/produk/5f645c17b668a-1204.jpg",
          "nama": "BOR LISTRIK THERMAL",
          "harga_sebelum_nego": "2850000",
          "harga_awal": "2650000",
          "harga_akhir": 5300000,
          "qty": "2",
          "stok": "8",
          "nego": "2500000",
          "nego2": "2700000",
          "nego3": "2650000",
          "status_nego": "1",
          "ProdukID": "1204",
          "namaseller": "Atria Seller",
          "catatan": "",
          "fixprice": "2650000",
          "fixstatus": "Nego Disetujui"
        }
      ],
      "total": 5150000
    }
  ],
  "pajak": [
    {
      "id": "1",
      "nama": "Pajak",
      "persentase": "11"
    }
  ]
} 
*/

  String? result;
  List<ShoppingCartModelData?>? data;
  List<ShoppingCartModelPajak?>? pajak;

  ShoppingCartModel({
    this.result,
    this.data,
    this.pajak,
  });
  ShoppingCartModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ShoppingCartModelData>[];
      v.forEach((v) {
        arr0.add(ShoppingCartModelData.fromJson(v));
      });
      this.data = arr0;
    }
    if (json['pajak'] != null) {
      final v = json['pajak'];
      final arr0 = <ShoppingCartModelPajak>[];
      v.forEach((v) {
        arr0.add(ShoppingCartModelPajak.fromJson(v));
      });
      pajak = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pajak != null) {
      final v = pajak;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['pajak'] = arr0;
    }
    return data;
  }
}
