///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShoppingCartConfirmModelDataTax {
/*
{
  "name": "VAT"
}
*/

  String? name;

  ShoppingCartConfirmModelDataTax({
    this.name,
  });
  ShoppingCartConfirmModelDataTax.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    return data;
  }
}

class ShoppingCartConfirmModelDataAddress {
/*
{
  "name": "Testing",
  "address": "Jalan Pumpungan I, RW 02, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur, Jawa, 60118, Indonesia",
  "phone": "098"
}
*/

  String? name;
  String? address;
  String? phone;

  ShoppingCartConfirmModelDataAddress({
    this.name,
    this.address,
    this.phone,
  });
  ShoppingCartConfirmModelDataAddress.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    address = json['address']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['address'] = address;
    data['phone'] = phone;
    return data;
  }
}

class ShoppingCartConfirmModelDataCartItem {
/*
{
  "product_id": 1,
  "name": "MESIN DIESEL GX-999 SOLAR TEST ENGINE",
  "qty": 1,
  "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/diesel-l.webp",
  "price": 250000,
  "price_desc": "Rp 250.000",
  "price_promo": "Rp 0",
  "price_promo_desc": "Rp 0",
  "subtotal_item": 250000,
  "subtotal_item_desc": "Rp 250.000"
}
*/

  int? productId;
  String? name;
  int? qty;
  String? image;
  int? price;
  String? priceDesc;
  int? pricePromo;
  String? pricePromoDesc;
  int? subtotalItem;
  String? subtotalItemDesc;

  ShoppingCartConfirmModelDataCartItem({
    this.productId,
    this.name,
    this.qty,
    this.image,
    this.price,
    this.priceDesc,
    this.pricePromo,
    this.pricePromoDesc,
    this.subtotalItem,
    this.subtotalItemDesc,
  });
  ShoppingCartConfirmModelDataCartItem.fromJson(Map<String, dynamic> json) {
    productId = json['product_id']?.toInt();
    name = json['name']?.toString();
    qty = json['qty']?.toInt();
    image = json['image']?.toString();
    price = json['price']?.toInt();
    priceDesc = json['price_desc']?.toString();
    pricePromo = json['price_promo']?.toInt();
    pricePromoDesc = json['price_promo_desc']?.toString();
    subtotalItem = json['subtotal_item']?.toInt();
    subtotalItemDesc = json['subtotal_item_desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['product_id'] = productId;
    data['name'] = name;
    data['qty'] = qty;
    data['image'] = image;
    data['price'] = price;
    data['price_desc'] = priceDesc;
    data['price_promo'] = pricePromo;
    data['price_promo_desc'] = pricePromoDesc;
    data['subtotal_item'] = subtotalItem;
    data['subtotal_item_desc'] = subtotalItemDesc;
    return data;
  }
}

class ShoppingCartConfirmModelDataCart {
/*
{
  "cart_id": "null",
  "count_item": 1,
  "item": [
    {
      "product_id": 1,
      "name": "MESIN DIESEL GX-999 SOLAR TEST ENGINE",
      "qty": 1,
      "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/diesel-l.webp",
      "price": 250000,
      "price_desc": "Rp 250.000",
      "price_promo": "Rp 0",
      "price_promo_desc": "Rp 0",
      "subtotal_item": 250000,
      "subtotal_item_desc": "Rp 250.000"
    }
  ]
}
*/

  String? cartId;
  int? countItem;
  List<ShoppingCartConfirmModelDataCartItem?>? item;

  ShoppingCartConfirmModelDataCart({
    this.cartId,
    this.countItem,
    this.item,
  });
  ShoppingCartConfirmModelDataCart.fromJson(Map<String, dynamic> json) {
    cartId = json['cart_id']?.toString();
    countItem = json['count_item']?.toInt();
    if (json['item'] != null) {
      final v = json['item'];
      final arr0 = <ShoppingCartConfirmModelDataCartItem>[];
      v.forEach((v) {
        arr0.add(ShoppingCartConfirmModelDataCartItem.fromJson(v));
      });
      item = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cart_id'] = cartId;
    data['count_item'] = countItem;
    if (item != null) {
      final v = item;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['item'] = arr0;
    }
    return data;
  }
}

class ShoppingCartConfirmModelData {
/*
{
  "cart": {
    "cart_id": "null",
    "count_item": 1,
    "item": [
      {
        "product_id": 1,
        "name": "MESIN DIESEL GX-999 SOLAR TEST ENGINE",
        "qty": 1,
        "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/diesel-l.webp",
        "price": 250000,
        "price_desc": "Rp 250.000",
        "price_promo": "Rp 0",
        "price_promo_desc": "Rp 0",
        "subtotal_item": 250000,
        "subtotal_item_desc": "Rp 250.000"
      }
    ]
  },
  "address": {
    "name": "Testing",
    "address": "Jalan Pumpungan I, RW 02, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur, Jawa, 60118, Indonesia",
    "phone": "098"
  },
  "tax": {
    "name": "VAT"
  },
  "payment": "[]",
  "shipping": 50001,
  "sub_total": 250000,
  "sub_total_desc": "Rp 250.000",
  "discount": 0,
  "discount_desc": "Rp 0",
  "total": 300001,
  "total_desc": "Rp 250.000"
}
*/

  ShoppingCartConfirmModelDataCart? cart;
  ShoppingCartConfirmModelDataAddress? address;
  ShoppingCartConfirmModelDataTax? tax;
  String? payment;
  int? shipping;
  int? subTotal;
  String? subTotalDesc;
  int? discount;
  String? discountDesc;
  String? feeAdmin;
  String? feeAdminDesc;
  int? total;
  String? totalDesc;

  ShoppingCartConfirmModelData({
    this.cart,
    this.address,
    this.tax,
    this.payment,
    this.shipping,
    this.subTotal,
    this.subTotalDesc,
    this.discount,
    this.discountDesc,
    this.feeAdmin,
    this.feeAdminDesc,
    this.total,
    this.totalDesc,
  });
  ShoppingCartConfirmModelData.fromJson(Map<String, dynamic> json) {
    cart = (json['cart'] != null)
        ? ShoppingCartConfirmModelDataCart.fromJson(json['cart'])
        : null;
    address = (json['address'] != null)
        ? ShoppingCartConfirmModelDataAddress.fromJson(json['address'])
        : null;
    tax = (json['tax'] != null)
        ? ShoppingCartConfirmModelDataTax.fromJson(json['tax'])
        : null;
    payment = json['payment']?.toString();
    shipping = json['shipping']?.toInt();
    subTotal = json['sub_total']?.toInt();
    subTotalDesc = json['sub_total_desc']?.toString();
    discount = json['discount']?.toInt();
    discountDesc = json['discount_desc']?.toString();
    feeAdmin = json['fee_admin']?.toString();
    feeAdminDesc = json['fee_admin_desc']?.toString();
    total = json['total']?.toInt();
    totalDesc = json['total_desc']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cart != null) {
      data['cart'] = cart!.toJson();
    }
    if (address != null) {
      data['address'] = address!.toJson();
    }
    if (tax != null) {
      data['tax'] = tax!.toJson();
    }
    data['payment'] = payment;
    data['shipping'] = shipping;
    data['sub_total'] = subTotal;
    data['sub_total_desc'] = subTotalDesc;
    data['discount'] = discount;
    data['discount_desc'] = discountDesc;
    data['fee_admin'] = feeAdmin;
    data['fee_admin_desc'] = feeAdminDesc;
    data['total'] = total;
    data['total_desc'] = totalDesc;
    return data;
  }
}

class ShoppingCartConfirmModel {
/*
{
  "success": true,
  "message": "",
  "data": {
    "cart": {
      "cart_id": "null",
      "count_item": 1,
      "item": [
        {
          "product_id": 1,
          "name": "MESIN DIESEL GX-999 SOLAR TEST ENGINE",
          "qty": 1,
          "image": "https://sibima.sgp1.cdn.digitaloceanspaces.com/diesel-l.webp",
          "price": 250000,
          "price_desc": "Rp 250.000",
          "price_promo": "Rp 0",
          "price_promo_desc": "Rp 0",
          "subtotal_item": 250000,
          "subtotal_item_desc": "Rp 250.000"
        }
      ]
    },
    "address": {
      "name": "Testing",
      "address": "Jalan Pumpungan I, RW 02, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur, Jawa, 60118, Indonesia",
      "phone": "098"
    },
    "tax": {
      "name": "VAT"
    },
    "payment": "[]",
    "shipping": 50001,
    "sub_total": 250000,
    "sub_total_desc": "Rp 250.000",
    "discount": 0,
    "discount_desc": "Rp 0",
    "total": 300001,
    "total_desc": "Rp 250.000"
  }
}
*/

  bool? success;
  String? message;
  ShoppingCartConfirmModelData? data;

  ShoppingCartConfirmModel({
    this.success,
    this.message,
    this.data,
  });
  ShoppingCartConfirmModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null)
        ? ShoppingCartConfirmModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
