///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubditModelData {
/*
{
  "ID": "68",
  "nomor_permintaan": "796/DPP/H207/VI/2024",
  "jumlah_prk": "1",
  "nilai_prk": "555000000",
  "IDPrk": "1617",
  "BuyerID": "0",
  "status": "0",
  "sisa": "555000000",
  "subdit_id": "7",
  "description": "null",
  "tanggal": "null",
  "judul": "null",
  "subdit_name": "SUBDIT OPERASI"
}
*/

  String? ID;
  String? nomorPermintaan;
  String? jumlahPrk;
  String? nilaiPrk;
  String? IDPrk;
  String? BuyerID;
  String? status;
  String? sisa;
  String? subditId;
  String? description;
  String? tanggal;
  String? judul;
  String? subditName;

  SubditModelData({
    this.ID,
    this.nomorPermintaan,
    this.jumlahPrk,
    this.nilaiPrk,
    this.IDPrk,
    this.BuyerID,
    this.status,
    this.sisa,
    this.subditId,
    this.description,
    this.tanggal,
    this.judul,
    this.subditName,
  });
  SubditModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nomorPermintaan = json['nomor_permintaan']?.toString();
    jumlahPrk = json['jumlah_prk']?.toString();
    nilaiPrk = json['nilai_prk']?.toString();
    IDPrk = json['IDPrk']?.toString();
    BuyerID = json['BuyerID']?.toString();
    status = json['status']?.toString();
    sisa = json['sisa']?.toString();
    subditId = json['subdit_id']?.toString();
    description = json['description']?.toString();
    tanggal = json['tanggal']?.toString();
    judul = json['judul']?.toString();
    subditName = json['subdit_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nomor_permintaan'] = nomorPermintaan;
    data['jumlah_prk'] = jumlahPrk;
    data['nilai_prk'] = nilaiPrk;
    data['IDPrk'] = IDPrk;
    data['BuyerID'] = BuyerID;
    data['status'] = status;
    data['sisa'] = sisa;
    data['subdit_id'] = subditId;
    data['description'] = description;
    data['tanggal'] = tanggal;
    data['judul'] = judul;
    data['subdit_name'] = subditName;
    return data;
  }
}

class SubditModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "68",
      "nomor_permintaan": "796/DPP/H207/VI/2024",
      "jumlah_prk": "1",
      "nilai_prk": "555000000",
      "IDPrk": "1617",
      "BuyerID": "0",
      "status": "0",
      "sisa": "555000000",
      "subdit_id": "7",
      "description": "null",
      "tanggal": "null",
      "judul": "null",
      "subdit_name": "SUBDIT OPERASI"
    }
  ]
}
*/

  String? result;
  List<SubditModelData?>? data;

  SubditModel({
    this.result,
    this.data,
  });
  SubditModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SubditModelData>[];
      v.forEach((v) {
        arr0.add(SubditModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
