///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KategoriModelData {
  String? id;
  String? name;
  String? status;

  KategoriModelData({
    this.id,
    this.name,
    this.status,
  });
  KategoriModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['status'] = status;
    return data;
  }
}

class KategoriModel {
  List<KategoriModelData?>? data;

  KategoriModel({
    this.data,
  });
  KategoriModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <KategoriModelData>[];
      v.forEach((v) {
        arr0.add(KategoriModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
