///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProdukListSellerModelData {
/*
{
  "ID": "1185",
  "nama": "Skincare Pria",
  "harga": "467000",
  "kode_produk": "002",
  "size": "",
  "qty": "11",
  "deskripsi": "Membuat kulit cerah",
  "SellerID": "196",
  "hapus": "0",
  "foto": "KAHF-FOTO-3-1344x800.png",
  "IDKategori": "1"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;

  ProdukListSellerModelData({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
  });
  ProdukListSellerModelData.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    harga = json['harga']?.toString();
    kodeProduk = json['kode_produk']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString();
    SellerID = json['SellerID']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    return data;
  }
}

class ProdukListSellerModel {
/*
{
  "result": "success",
  "data": [
    {
      "ID": "1185",
      "nama": "Skincare Pria",
      "harga": "467000",
      "kode_produk": "002",
      "size": "",
      "qty": "11",
      "deskripsi": "Membuat kulit cerah",
      "SellerID": "196",
      "hapus": "0",
      "foto": "KAHF-FOTO-3-1344x800.png",
      "IDKategori": "1"
    }
  ]
} 
*/

  String? result;
  List<ProdukListSellerModelData?>? data;

  ProdukListSellerModel({
    this.result,
    this.data,
  });
  ProdukListSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProdukListSellerModelData>[];
      v.forEach((v) {
        arr0.add(ProdukListSellerModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
