///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProdukDetailSellerModelDataFotoProduk {
/*
{
  "ID": "52",
  "nama": "Frame-9-e1681578823773.png",
  "foto": "Frame-9-e1681578823773.png",
  "ProdukID": "1185"
} 
*/

  String? ID;
  String? nama;
  String? foto;
  String? ProdukID;

  ProdukDetailSellerModelDataFotoProduk({
    this.ID,
    this.nama,
    this.foto,
    this.ProdukID,
  });
  ProdukDetailSellerModelDataFotoProduk.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString();
    nama = json['nama']?.toString();
    foto = json['foto']?.toString();
    ProdukID = json['ProdukID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['foto'] = foto;
    data['ProdukID'] = ProdukID;
    return data;
  }
}

class ProdukDetailSellerModelDataProduk {
/*
{
  "ID": "1185",
  "nama": "Skincare Pria",
  "harga": "467000",
  "kode_produk": "002",
  "size": "",
  "qty": "11",
  "deskripsi": "Membuat kulit cerah",
  "SellerID": "196",
  "hapus": "0",
  "foto": "KAHF-FOTO-3-1344x800.png",
  "IDKategori": "1"
} 
*/

  String? ID;
  String? nama;
  String? harga;
  String? kodeProduk;
  String? size;
  String? qty;
  String? deskripsi;
  String? SellerID;
  String? hapus;
  String? foto;
  String? IDKategori;

  ProdukDetailSellerModelDataProduk({
    this.ID,
    this.nama,
    this.harga,
    this.kodeProduk,
    this.size,
    this.qty,
    this.deskripsi,
    this.SellerID,
    this.hapus,
    this.foto,
    this.IDKategori,
  });
  ProdukDetailSellerModelDataProduk.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toString() ?? json['id']?.toString();
    nama = json['nama']?.toString() ?? json['name']?.toString();
    harga = json['harga']?.toString() ?? json['price']?.toString();
    kodeProduk = json['kode_produk']?.toString() ?? json['product_code']?.toString();
    size = json['size']?.toString();
    qty = json['qty']?.toString();
    deskripsi = json['deskripsi']?.toString() ?? json['description']?.toString();
    SellerID = json['SellerID']?.toString() ?? json['seller']?['id']?.toString();
    hapus = json['hapus']?.toString();
    foto = json['foto']?.toString();
    IDKategori = json['IDKategori']?.toString() ?? json['category']?['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['nama'] = nama;
    data['harga'] = harga;
    data['kode_produk'] = kodeProduk;
    data['size'] = size;
    data['qty'] = qty;
    data['deskripsi'] = deskripsi;
    data['SellerID'] = SellerID;
    data['hapus'] = hapus;
    data['foto'] = foto;
    data['IDKategori'] = IDKategori;
    return data;
  }
}

class ProdukDetailSellerModelData {
/*
{
  "produk": {
    "ID": "1185",
    "nama": "Skincare Pria",
    "harga": "467000",
    "kode_produk": "002",
    "size": "",
    "qty": "11",
    "deskripsi": "Membuat kulit cerah",
    "SellerID": "196",
    "hapus": "0",
    "foto": "KAHF-FOTO-3-1344x800.png",
    "IDKategori": "1"
  },
  "foto_produk": [
    {
      "ID": "52",
      "nama": "Frame-9-e1681578823773.png",
      "foto": "Frame-9-e1681578823773.png",
      "ProdukID": "1185"
    }
  ]
} 
*/

  ProdukDetailSellerModelDataProduk? produk;
  List<ProdukDetailSellerModelDataFotoProduk?>? fotoProduk;

  ProdukDetailSellerModelData({
    this.produk,
    this.fotoProduk,
  });
  ProdukDetailSellerModelData.fromJson(Map<String, dynamic> json) {
    produk = (json['produk'] != null)
        ? ProdukDetailSellerModelDataProduk.fromJson(json['produk'])
        : null;
    if (json['foto_produk'] != null) {
      final v = json['foto_produk'];
      final arr0 = <ProdukDetailSellerModelDataFotoProduk>[];
      v.forEach((v) {
        arr0.add(ProdukDetailSellerModelDataFotoProduk.fromJson(v));
      });
      fotoProduk = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (produk != null) {
      data['produk'] = produk!.toJson();
    }
    if (fotoProduk != null) {
      final v = fotoProduk;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['foto_produk'] = arr0;
    }
    return data;
  }
}

class ProdukDetailSellerModel {
/*
{
  "result": "success",
  "data": {
    "produk": {
      "ID": "1185",
      "nama": "Skincare Pria",
      "harga": "467000",
      "kode_produk": "002",
      "size": "",
      "qty": "11",
      "deskripsi": "Membuat kulit cerah",
      "SellerID": "196",
      "hapus": "0",
      "foto": "KAHF-FOTO-3-1344x800.png",
      "IDKategori": "1"
    },
    "foto_produk": [
      {
        "ID": "52",
        "nama": "Frame-9-e1681578823773.png",
        "foto": "Frame-9-e1681578823773.png",
        "ProdukID": "1185"
      }
    ]
  }
} 
*/

  String? result;
  ProdukDetailSellerModelData? data;

  ProdukDetailSellerModel({
    this.result,
    this.data,
  });
  ProdukDetailSellerModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    data = (json['data'] != null)
        ? ProdukDetailSellerModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['data'] = this.data!.toJson();
      return data;
  }
}
